export const PROGRESS_ACTION = 'PROGRESS_ACTION';
export const SET_CONNECTION_CHECKED = 'SET_CONNECTION_CHECKED';
export const UPDATE_NETWORK_STATUS = 'UPDATE_NETWORK_STATUS';
export const UPDATE_LACK_CONNECTION_MESSAGE_STATUS = 'UPDATE_LACK_CONNECTION_MESSAGE_STATUS';
export const UPDATE_SYNC_STATUS = 'UPDATE_SYNC_STATUS';


