export const SEARCH_EVENTS_ACTION = 'SEARCH_EVENTS_ACTION';
export const SEARCH_EVENTS_SUCCESS_ACTION = 'SEARCH_EVENTS_SUCCESS_ACTION';
export const SEARCH_EVENTS_ERROR_ACTION = 'SEARCH_EVENTS_ERROR_ACTION';
export const CLEAR_EVENTS_ACTION = 'CLEAR_EVENTS_ACTION';
export const LOAD_EVENT = 'events/LOAD_EVENT';
export const LOAD_EVENT_SUCCESS = 'events/LOAD_EVENT_SUCCESS';
export const LOAD_EVENTS_ERROR = 'events/LOAD_EVENT_ERROR';
export const CLEAN_EVENT = 'events/CLEAN_EVENT';

