export const SEARCH_EVENTS_ACTION = 'SEARCH_EVENTS_ACTION';
export const SEARCH_EVENTS_SUCCESS_ACTION = 'SEARCH_EVENTS_SUCCESS_ACTION';
export const SEARCH_EVENTS_ERROR_ACTION = 'SEARCH_EVENTS_ERROR_ACTION';
export const CLEAR_EVENTS_ACTION = 'CLEAR_EVENTS_ACTION';