export const SEARCH_TRASH_POINTS_ACTION = 'SEARCH_TRASH_POINTS_ACTION';
export const SEARCH_TRASH_POINTS_SUCCESS_ACTION = 'SEARCH_TRASH_POINTS_SUCCESS_ACTION';
export const SEARCH_TRASH_POINTS_ERROR_ACTION = 'SEARCH_TRASH_POINTS_ERROR_ACTION';
export const CLEAR_TRASH_POINTS_ACTION = 'CLEAR_TRASH_POINTS_ACTION';
// create
export const CREATE_TRASH_POINT_ACTION = 'CREATE_TRASH_POINT_ACTION';
export const UPDATE_TRASH_POINT_ACTION = 'UPDATE_TRASH_POINT_ACTION';
export const GET_TRASH_POINT_DETAILS_ACTION = 'GET_TRASH_POINT_DETAILS_ACTION';
export const GET_TRASH_POINT_ORIGIN_ACTION = 'GET_TRASH_POINT_ORIGIN_ACTION';
export const GET_TRASH_POINT_DETAILS_SUCCESS_ACTION =
  'GET_TRASH_POINT_DETAILS_SUCCESS_ACTION';
export const DELETE_TRASH_POINT_ACTION = 'DELETE_TRASH_POINT_ACTION';
export const DELETE_TRASH_POINT_IMAGE_ACTION = 'DELETE_TRASH_POINT_IMAGE_ACTION';
export const DISMISS_SUCCESS_UPDATE = 'DISMISS_SUCCESS_UPDATE';
export const DELETE_TRASH_POINT_IMAGE_SUCCESS_ACTION =
  'DELETE_TRASH_POINT_IMAGE_SUCCESS_ACTION';
export const GET_TRASH_POINT_IMAGES_ACTION = 'GET_TRASH_POINT_IMAGES_ACTION';
export const GET_TRASH_POINT_IMAGES_SUCCESS_ACTION =
  'GET_TRASH_POINT_IMAGES_SUCCESS_ACTION';
export const CREATE_TRASH_POINT_SUCCESS_ACTION = 'CREATE_TRASH_POINT_SUCCESS_ACTION';
export const UPDATE_TRASH_POINT_SUCCESS_ACTION = 'CREATE_TRASH_POINT_SUCCESS_ACTION';
export const DELETE_TRASH_POINT_SUCCESS_ACTION = 'DELETE_TRASH_POINT_SUCCESS_ACTION';
export const DELETE_TRASH_POINT_COMPLETE_ACTION = 'DELETE_TRASH_POINT_COMPLETE_ACTION';
export const CREATE_TRASH_POINT_ERROR_ACTION = 'CREATE_TRASH_POINT_ERROR_ACTION';
// map
export const REQUEST_TRASH_POINTS_MAP_ACTION =
  'REQUEST_TRASH_POINTS_MAP_ACTION';
export const SHOW_NEW_DELTA_TRASH_POINTS_MAP_ACTION =
  'SHOW_NEW_DELTA_TRASH_POINTS_MAP_ACTION';
export const LOAD_TRASH_POINTS_FOR_MAP_SUCCESS_ACTION =
  'LOAD_TRASH_POINTS_FOR_MAP_SUCCESS_ACTION';
export const LOAD_TRASH_POINTS_FOR_MAP_ERROR_ACTION =
  'LOAD_TRASH_POINTS_FOR_MAP_ERROR_ACTION';
export const LOAD_TRASH_POINT_FROM_CLUSTER_ACTION =
  'LOAD_TRASH_POINT_FROM_CLUSTER_ACTION';
// trashpoint details
export const TRASH_POINT_DETAILS_SUCCESS = 'TRASH_POINT_DETAILS_SUCCESS';

export const IS_TRASH_POINTS_EMPTY =
  'IS_TRASH_POINTS_EMPTY';

export const LOAD_TRASH_POINT = 'trashpoint/LOAD_TRASH_POINT';
export const LOAD_TRASH_POINT_SUCCESS = 'trashpoint/LOAD_TRASH_POINT_SUCCESS';
export const CLEAN_TRASH_POINT = 'trashpoint/TRASH_POINT';
export const CLEAN_TRASH_POINT_DETAILS = 'trashpoint/CLEAN_TRASH_POINT_DETAILS';
export const CLEAN_TRASH_POINT_IMAGE_DETAILS =
  'trashpoint/CLEAN_TRASH_POINT_IMAGE_DETAILS';
