export const SEARCH_TRASH_POINTS_ACTION = 'SEARCH_TRASH_POINTS_ACTION';
export const SEARCH_TRASH_POINTS_SUCCESS_ACTION = 'SEARCH_TRASH_POINTS_SUCCESS_ACTION';
export const SEARCH_TRASH_POINTS_ERROR_ACTION = 'SEARCH_TRASH_POINTS_ERROR_ACTION';
export const CLEAR_TRASH_POINTS_ACTION = 'CLEAR_TRASH_POINTS_ACTION';
// create
export const CREATE_TRASH_POINT_ACTION = 'CREATE_TRASH_POINT_ACTION';
export const CREATE_TRASH_POINT_SUCCESS_ACTION = 'CREATE_TRASH_POINT_SUCCESS_ACTION';
export const CREATE_TRASH_POINT_ERROR_ACTION = 'CREATE_TRASH_POINT_ERROR_ACTION';
// map
export const REQUEST_TRASH_POINTS_MAP_ACTION =
'REQUEST_TRASH_POINTS_MAP_ACTION';
export const SHOW_NEW_DELTA_TRASH_POINTS_MAP_ACTION =
'SHOW_NEW_DELTA_TRASH_POINTS_MAP_ACTION';
export const LOAD_TRASH_POINTS_FOR_MAP_SUCCESS_ACTION =
'LOAD_TRASH_POINTS_FOR_MAP_SUCCESS_ACTION';
export const LOAD_TRASH_POINTS_FOR_MAP_ERROR_ACTION =
'LOAD_TRASH_POINTS_FOR_MAP_ERROR_ACTION';
export const LOAD_TRASH_POINT_FROM_CLUSTER_ACTION =
'LOAD_TRASH_POINT_FROM_CLUSTER_ACTION';

export const IS_TRASH_POINTS_EMPTY =
'IS_TRASH_POINTS_EMPTY';
