export default {
    FETCH_TEAMS_REQUEST: 'FETCH_TEAMS_REQUEST',
    FETCH_TEAMS_SUCCESS: 'FETCH_TEAMS_SUCCESS',
    FETCH_TEAMS_FAILED: 'FETCH_TEAMS_FAILED',
    FETCH_TEAM_REQUEST: 'FETCH_TEAM_REQUEST',
    FETCH_TEAM_SUCCESS: 'FETCH_TEAM_SUCCESS',
    FETCH_TEAM_FAILED: 'FETCH_TEAM_FAILED',
};
