export const images = [
  require('../assets/images/icon_menu_map.png'),
  // require('../assets/images/icon_menu_map@2x.png'),
  // require('../assets/images/icon_menu_map@3x.png'),
  require('../assets/images/icon_menu_map_active.png'),
  // require('../assets/images/icon_menu_map_active@2x.png'),
  // require('../assets/images/icon_menu_map_active@3x.png'),
  require('../assets/images/icon_menu_activity.png'),
  // require('../assets/images/icon_menu_activity@2x.png'),
  // require('../assets/images/icon_menu_activity@3x.png'),
  require('../assets/images/icon_menu_profile.png'),
  // require('../assets/images/icon_menu_profile@2x.png'),
  // require('../assets/images/icon_menu_profile@3x.png'),
  require('../assets/images/icon_menu_updates.png'),
  // require('../assets/images/icon_menu_updates@2x.png'),
  // require('../assets/images/icon_menu_updates@3x.png'),
  require('../assets/images/icon_menu_activity_active.png'),
  // require('../assets/images/icon_menu_activity_active@2x.png'),
  // require('../assets/images/icon_menu_activity_active@3x.png'),
  require('../assets/images/icon_menu_profile_active.png'),
  // require('../assets/images/icon_menu_profile_active@2x.png'),
  // require('../assets/images/icon_menu_profile_active@3x.png'),
  require('../assets/images/icon_menu_updates_active.png'),
  // require('../assets/images/icon_menu_updates_active@2x.png'),
  // require('../assets/images/icon_menu_updates_active@3x.png'),
  require('../components/Map/images/pointer_cleaned.png'),
  // require('../components/Map/images/pointer_cleaned@2x.png'),
  // require('../components/Map/images/pointer_cleaned@3x.png'),
  require('../components/Map/images/pointer_outdated.png'),
  // require('../components/Map/images/pointer_outdated@2x.png'),
  // require('../components/Map/images/pointer_outdated@3x.png'),
  require('../components/Map/images/pointer_regular.png'),
  // require('../components/Map/images/pointer_regular@2x.png'),
  // require('../components/Map/images/pointer_regular@3x.png'),
  require('../components/Map/images/pointer_threat.png'),
  // require('../components/Map/images/pointer_threat@2x.png'),
  // require('../components/Map/images/pointer_threat@3x.png'),
  require('../components/Map/images/label_one_digit.png'),
  // require('../components/Map/images/label_one_digit@2x.png'),
  // require('../components/Map/images/label_one_digit@3x.png'),
  require('../components/Map/images/label_two_digit.png'),
  // require('../components/Map/images/label_two_digit@2x.png'),
  // require('../components/Map/images/label_two_digit@3x.png'),
  require('../components/Map/images/label_three_digit.png'),
  // require('../components/Map/images/label_three_digit@2x.png'),
  // require('../components/Map/images/label_three_digit@3x.png'),
  require('../components/Map/images/location_pointer.png'),
  // require('../components/Map/images/location_pointer@2x.png'),
  // require('../components/Map/images/location_pointer@3x.png'),
  require('../components/Map/images/change_location_pin.png'),
  // require('../components/Map/images/change_location_pin@2x.png'),
  // require('../components/Map/images/change_location_pin@3x.png'),
  require('../screens/Details/images/icon_status_small_threat.png'),
  // require('../screens/Details/images/icon_status_small_threat@2x.png'),
  // require('../screens/Details/images/icon_status_small_threat@3x.png'),
  require('../screens/Details/images/icon_creation.png'),
  // require('../screens/Details/images/icon_creation@2x.png'),
  // require('../screens/Details/images/icon_creation@3x.png'),
  require('../screens/Details/images/icon_updated.png'),
  // require('../screens/Details/images/icon_updated@2x.png'),
  // require('../screens/Details/images/icon_updated@3x.png'),
  require('../components/AmountPicker/images/icon_bagful_blue_fill.png'),
  // require('../components/AmountPicker/images/icon_bagful_blue_fill@2x.png'),
  // require('../components/AmountPicker/images/icon_bagful_blue_fill@3x.png'),
  require('../components/AmountPicker/images/icon_bagful_blue_outline.png'),
  // require('../components/AmountPicker/images/icon_bagful_blue_outline@2x.png'),
  // require('../components/AmountPicker/images/icon_bagful_blue_outline@3x.png'),
  require('../components/AmountPicker/images/icon_bagful_grey_fill.png'),
  // require('../components/AmountPicker/images/icon_bagful_grey_fill@2x.png'),
  // require('../components/AmountPicker/images/icon_bagful_grey_fill@3x.png'),
  require('../components/AmountPicker/images/icon_cartload_blue_fill.png'),
  // require('../components/AmountPicker/images/icon_cartload_blue_fill@2x.png'),
  // require('../components/AmountPicker/images/icon_cartload_blue_fill@3x.png'),
  require('../components/AmountPicker/images/icon_cartload_blue_outline.png'),
  // require('../components/AmountPicker/images/icon_cartload_blue_outline@2x.png'),
  // require('../components/AmountPicker/images/icon_cartload_blue_outline@3x.png'),
  require('../components/AmountPicker/images/icon_cartload_grey_fill.png'),
  // require('../components/AmountPicker/images/icon_cartload_grey_fill@2x.png'),
  // require('../components/AmountPicker/images/icon_cartload_grey_fill@3x.png'),
  require('../components/AmountPicker/images/icon_handful_blue_fill.png'),
  // require('../components/AmountPicker/images/icon_handful_blue_fill@2x.png'),
  // require('../components/AmountPicker/images/icon_handful_blue_fill@3x.png'),
  require('../components/AmountPicker/images/icon_handful_blue_outline.png'),
  // require('../components/AmountPicker/images/icon_handful_blue_outline@2x.png'),
  // require('../components/AmountPicker/images/icon_handful_blue_outline@3x.png'),
  require('../components/AmountPicker/images/icon_handful_grey_fill.png'),
  // require('../components/AmountPicker/images/icon_handful_grey_fill@2x.png'),
  // require('../components/AmountPicker/images/icon_handful_grey_fill@3x.png'),
  require('../components/AmountPicker/images/icon_truck_blue_fill.png'),
  // require('../components/AmountPicker/images/icon_truck_blue_fill@2x.png'),
  // require('../components/AmountPicker/images/icon_truck_blue_fill@3x.png'),
  require('../components/AmountPicker/images/icon_truck_blue_outline.png'),
  // require('../components/AmountPicker/images/icon_truck_blue_outline@2x.png'),
  // require('../components/AmountPicker/images/icon_truck_blue_outline@3x.png'),
  require('../components/AmountPicker/images/icon_truck_grey_fill.png'),
  // require('../components/AmountPicker/images/icon_truck_grey_fill@2x.png'),
  // require('../components/AmountPicker/images/icon_truck_grey_fill@3x.png'),
  require('../assets/images/img.png'),
  // require('../assets/images/img@2x.png'),
  // require('../assets/images/img@3x.png'),
  require('../assets/images/icon_notification_warning.png'),
  // require('../assets/images/icon_notification_warning@2x.png'),
  // require('../assets/images/icon_notification_warning@3x.png'),
  require('../components/Header/images/icon_menu_arrowback.png'),
  // require('../components/Header/images/icon_menu_arrowback@2x.png'),
  // require('../components/Header/images/icon_menu_arrowback@3x.png'),
  require('../components/Header/images/settings.png'),
  // require('../components/Header/images/settings@2x.png'),
  // require('../components/Header/images/settings@3x.png'),
  require('../screens/CreateMarker/components/CongratsModal/images/image.png'),
  require('../assets/images/icon_location.png'),
  // require('../assets/images/icon_location@2x.png'),
  // require('../assets/images/icon_location@3x.png'),
  require('../assets/images/icon_menu_arrowforward.png'),
  // require('../assets/images/icon_menu_arrowforward@2x.png'),
  // require('../assets/images/icon_menu_arrowforward@3x.png'),
  require('../components/StatusText/images/icon_status_small_threat.png'),
  // require('../components/StatusText/images/icon_status_small_threat@2x.png'),
  // require('../components/StatusText/images/icon_status_small_threat@3x.png'),
  require('../components/StatusText/images/icon_status_small_clean.png'),
  // require('../components/StatusText/images/icon_status_small_clean@2x.png'),
  // require('../components/StatusText/images/icon_status_small_clean@3x.png'),
  require('../components/StatusText/images/icon_status_small_outdated.png'),
  // require('../components/StatusText/images/icon_status_small_outdated@2x.png'),
  // require('../components/StatusText/images/icon_status_small_outdated@3x.png'),
  require('../components/StatusText/images/icon_status_small_regular.png'),
  // require('../components/StatusText/images/icon_status_small_regular@2x.png'),
  // require('../components/StatusText/images/icon_status_small_regular@3x.png'),
  require('../components/TrashpointDate/images/icon_updated.png'),
  // require('../components/TrashpointDate/images/icon_updated@2x.png'),
  // require('../components/TrashpointDate/images/icon_updated@3x.png'),
  require('../components/TrashpointDate/images/icon_creation.png'),
  // require('../components/TrashpointDate/images/icon_creation@2x.png'),
  // require('../components/TrashpointDate/images/icon_creation@3x.png'),
  require('../screens/CreateMarker/components/StatusPicker/images/default-status-clean.png'),
  // require('../screens/CreateMarker/components/StatusPicker/images/default-status-clean@2x.png'),
  // require('../screens/CreateMarker/components/StatusPicker/images/default-status-clean@3x.png'),
  require('../screens/CreateMarker/components/StatusPicker/images/selected-status-clean.png'),
  // require('../screens/CreateMarker/components/StatusPicker/images/selected-status-clean@3x.png'),
  require('../components/EmptyStateScreen/images/cat_300x300.png'),
  // require('../components/EmptyStateScreen/images/cat_300x300@2x.png'),
  // require('../components/EmptyStateScreen/images/cat_300x300@3x.png'),
  require('../screens/MyActivity/images/arrow.png'),
  require('../screens/MyActivity/images/arrow.png'),
  require('../screens/MyActivity/images/arrow.png'),
  require('../components/AlertModal/images/icon_notification_warning.png'),
  require('../screens/CreateMarker/components/CongratsModal/images/image.png'),
  require('../components/Logo/images/logo.png'),
  require('../components/TabMiddleButton/components/download.png'),
  require('../screens/Login/images/background.png'),
  require('../screens/Profile/images/avatar.png'),
  require('../screens/Profile/images/img_increaseimpact_jointeam.png'),
  // require('../screens/Profile/images/img_increaseimpact_jointeam@1,5x.png'),
  // require('../screens/Profile/images/img_increaseimpact_jointeam@2x.png'),
  // require('../screens/Profile/images/img_increaseimpact_jointeam@3x.png'),
  require('../screens/Profile/images/icon_ui_arrowdown.png'),
  // require('../screens/Profile/images/icon_ui_arrowdown@2x.png'),
  // require('../screens/Profile/images/icon_ui_arrowdown@3x.png'),
  require('../services/Error/sad.png'),
  require('../components/PhotoPicker/components/img_loading.png'),
  require('../services/Loading/lazy.png'),
];
export const fonts = {
  'noto-sans-bold': require('../assets/fonts/NotoSans-Bold.ttf'),
  'noto-sans-regular': require('../assets/fonts/NotoSans-Regular.ttf'),
};
