const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
const SET_LOCATION_PERMISSION = 'SET_LOCATION_PERMISSION';
const SET_LOCATION_ACTIVE = 'SET_LOCATION_ACTIVE';
const SET_SHOW_MODAL = 'location/SET_SHOW_MODAL';

export default {
  UPDATE_USER_LOCATION,
  SET_LOCATION_ACTIVE,
  SET_LOCATION_PERMISSION,
  SET_SHOW_MODAL,
};
