const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST';
const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
const FETCH_TEAMS_FAILED = 'FETCH_TEAMS_FAILED';

export default {
  FETCH_TEAMS_REQUEST,
  FETCH_TEAMS_SUCCESS,
  FETCH_TEAMS_FAILED,
};
