const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST';
const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
const FETCH_TEAMS_FAILED = 'FETCH_TEAMS_FAILED';
const CLEAR_TEAMS_SUCCESS = 'CLEAR_TEAMS_SUCCESS';

export default {
  FETCH_TEAMS_REQUEST,
  FETCH_TEAMS_SUCCESS,
  FETCH_TEAMS_FAILED,
  CLEAR_TEAMS_SUCCESS,
};
