const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST';
const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
const FETCH_TEAMS_FAILED = 'FETCH_TEAMS_FAILED';
const CLEAR_TEAMS_SUCCESS = 'CLEAR_TEAMS_SUCCESS';
const FETCH_TEAMS_BY_COUNTRY_REQUEST = 'FETCH_TEAMS_BY_COUNTRY_REQUEST';
const FETCH_TEAMS_BY_COUNTRY_SUCCESS = 'FETCH_TEAMS_BY_COUNTRY_SUCCESS';
const FETCH_TEAMS_BY_COUNTRY_FAILED = 'FETCH_TEAMS_BY_COUNTRY_FAILED';

export default {
  FETCH_TEAMS_REQUEST,
  FETCH_TEAMS_SUCCESS,
  FETCH_TEAMS_FAILED,
  CLEAR_TEAMS_SUCCESS,
  FETCH_TEAMS_BY_COUNTRY_REQUEST,
  FETCH_TEAMS_BY_COUNTRY_SUCCESS,
  FETCH_TEAMS_BY_COUNTRY_FAILED
};
