const FETCH_ALL_MARKERS_REQUEST = 'FETCH_ALL_MARKERS_REQUEST';
const FETCH_ALL_MARKERS_SUCCESS = 'FETCH_ALL_MARKERS_SUCCESS';
const FETCH_ALL_MARKERS_FAILED = 'FETCH_ALL_MARKERS_FAILED';
const CREATE_MARKER_REQUEST = 'CREATE_MARKER_REQUEST';
const CREATE_MARKER_SUCCESS = 'CREATE_MARKER_SUCCESS';
const CREATE_MARKER_FAILED = 'CREATE_MARKER_FAILED';
const FETCH_MARKER_DETAILS_REQUEST = 'FETCH_MARKER_DETAILS_REQUEST';
const FETCH_MARKER_DETAILS_SUCCESS = 'FETCH_MARKER_DETAILS_SUCCESS';
const FETCH_MARKER_DETAILS_FAILED = 'FETCH_MARKER_DETAILS_FAILED';
const FETCH_ALL_CLUSTERS_REQUEST = 'FETCH_ALL_CLUSTERS_REQUEST';
const FETCH_ALL_CLUSTERS_SUCCESS = 'FETCH_ALL_CLUSTERS_SUCCESS';
const FETCH_ALL_CLUSTERS_FAILED = 'FETCH_ALL_CLUSTERS_FAILED';

const RESET_MARKER_DETAILS = 'RESET_MARKER_DETAILS';

const FETCH_USER_TRASHPOINTS_REQUEST = 'FETCH_USER_TRASHPOINTS_REQUEST';
const FETCH_USER_TRASHPOINTS_SUCCESS = 'FETCH_USER_TRASHPOINTS_SUCCESS';
const FETCH_USER_TRASHPOINTS_FAILED = 'FETCH_USER_TRASHPOINTS_FAILED';
const USER_TRASHPOINTS_RESET = 'USER_TRASHPOINTS_RESET';
const SET_GRID_VALUE = 'SET_GRID_VALUE';

const DELETE_MARKER = 'DELETE_MARKER';
const DELETE_MARKER_SUCCESS = 'DELETE_MARKER_SUCCESS';
const DELETE_MARKER_ERROR = 'DELETE_MARKER_ERROR';

export default {
  FETCH_ALL_MARKERS_REQUEST,
  FETCH_ALL_MARKERS_SUCCESS,
  FETCH_ALL_MARKERS_FAILED,
  CREATE_MARKER_REQUEST,
  CREATE_MARKER_SUCCESS,
  CREATE_MARKER_FAILED,
  FETCH_MARKER_DETAILS_REQUEST,
  FETCH_MARKER_DETAILS_SUCCESS,
  FETCH_MARKER_DETAILS_FAILED,
  FETCH_USER_TRASHPOINTS_REQUEST,
  FETCH_USER_TRASHPOINTS_SUCCESS,
  FETCH_USER_TRASHPOINTS_FAILED,
  USER_TRASHPOINTS_RESET,
  FETCH_ALL_CLUSTERS_REQUEST,
  FETCH_ALL_CLUSTERS_SUCCESS,
  FETCH_ALL_CLUSTERS_FAILED,
  RESET_MARKER_DETAILS,
  SET_GRID_VALUE,

  DELETE_MARKER,
  DELETE_MARKER_SUCCESS,
  DELETE_MARKER_ERROR,
};
