# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'mobileapp' do
    
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'
  # Pods for mobileapp

  # use_frameworks!


 # pod 'FBSDKCoreKit'
 # pod 'FBSDKLoginKit'
 # pod 'FBSDKShareKit'
 # pod 'FBSDKPlacesKit'
 # pod 'FBSDKMessengerShareKit'

 # target 'mobileapp-tvOSTests' do
 #   inherit! :search_paths
    # Pods for testing
 # end


 # target 'mobileappTests' do
 #   inherit! :search_paths
    # Pods for testing
 # end

# end

# target 'mobileapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobileapp-tvOS

 # target 'mobileapp-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
 # end

 end

