const SET_POPOVER_SHOWN = 'app/SET_POPOVER_SHOWN';
const SET_POPOVER_MESSAGE = 'app/SET_POPOVER_MESSAGE';
const SET_ERROR_MESSAGE = 'app/SET_ERROR_MESSAGE';
const HIDE_ERROR_MESSAGE = 'app/HIDE_ERROR_MESSAGE';
const FETCH_DATASETS_REQUEST = 'FETCH_DATASETS_REQUEST';
const FETCH_DATASETS_SUCCESS = 'FETCH_DATASETS_SUCCESS';
const FETCH_DATASETS_FAILED = 'FETCH_DATASETS_FAILED';
const SET_ACTIVE_SCREEN = 'SET_ACTIVE_SCREEN';
const UPDATE_NETWORK_STATUS = 'UPDATE_NETWORK_STATUS';
const SET_CONNECTION_CHECKED = 'SET_CONNECTION_CHECKED';
const PROGRESS_ACTION = 'PROGRESS_ACTION';

export default {
  SET_POPOVER_SHOWN,
  SET_POPOVER_MESSAGE,
  SET_ERROR_MESSAGE,
  HIDE_ERROR_MESSAGE,
  FETCH_DATASETS_REQUEST,
  FETCH_DATASETS_SUCCESS,
  FETCH_DATASETS_FAILED,
  SET_ACTIVE_SCREEN,
  UPDATE_NETWORK_STATUS,
  SET_CONNECTION_CHECKED,
    PROGRESS_ACTION
};
