version: '3.1'

services:
  api:
    image: registry.ops.worldcleanupday.com/api
    networks:
      - ${NETWORK}
    env_file:
      - api.env
      - .globalenv
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=api.app.worldcleanupday.com
        - com.df.servicePath=/
        # - com.df.srcPort=443
        - com.df.port=80
        # do ssl and http -> https redirect
        - com.df.httpsOnly=true
        - com.df.xForwardedProto=true
        - com.df.redirectWhenHttpProto=true
        - com.ldiw.description="${DEPLOYMENT_LABEL}"

  auth:
    image: registry.ops.worldcleanupday.com/auth
    networks:
      - ${NETWORK}
    env_file:
      - auth.env
      - .globalenv
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - com.ldiw.description="${DEPLOYMENT_LABEL}"

  db:
    image: registry.ops.worldcleanupday.com/db
    networks:
      - ${NETWORK}
    env_file:
      - db.env
      - .globalenv
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - com.ldiw.description="${DEPLOYMENT_LABEL}"

  geo:
    image: registry.ops.worldcleanupday.com/geo
    networks:
      - ${NETWORK}
    env_file:
      - geo.env
      - .globalenv
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - com.ldiw.description="${DEPLOYMENT_LABEL}"

  couchdb:
    image: registry.ops.worldcleanupday.com/couchdb_geocouch:2
    networks:
      - ${NETWORK}
    environment:
      - "LCB_LOGLEVEL=5"
      - "COUCHDB_USER=backenddb"
      - "COUCHDB_PASSWORD=rockychrome"
    env_file:
      - couchdb.env
      - .globalenv
    volumes:
      - couchdb-${ENV_LABEL}:/usr/local/var/lib/couchdb
      - $PWD/local.ini:/usr/local/etc/couchdb/local.ini
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role!=manager
      labels:
        - com.ldiw.description="${DEPLOYMENT_LABEL}"

  webapp:
    image: registry.ops.worldcleanupday.com/webapp
    networks:
      - ${NETWORK}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=app.worldcleanupday.com
        - com.df.servicePath=/
        # - com.df.srcPort=443
        - com.df.port=80
        # do ssl and http -> https redirect
        - com.df.httpsOnly=true
        - com.df.reqMode=http
        - com.df.xForwardedProto=true
        - com.df.redirectWhenHttpProto=true
        - com.ldiw.description="${DEPLOYMENT_LABEL}"


networks:
  ${NETWORK}:
    driver: overlay
    external: true


volumes:
  couchdb-${ENV_LABEL}:
    driver: "azurefile"
    driver_opts:
      share: "couch-${ENV_LABEL}"