export const SEARCH_TRASH_POINTS_ACTION = 'SEARCH_TRASH_POINTS_ACTION';
export const SEARCH_TRASH_POINTS_SUCCESS_ACTION = 'SEARCH_TRASH_POINTS_SUCCESS_ACTION';
export const SEARCH_TRASH_POINTS_ERROR_ACTION = 'SEARCH_TRASH_POINTS_ERROR_ACTION';
export const CLEAR_TRASH_POINTS_ACTION = 'CLEAR_TRASH_POINTS_ACTION';