module.exports = {
    hashCountries: {
        AFG: 'Afghanistan',
        ALA: 'Åland Islands',
        ALB: 'Albania',
        DZA: 'Algeria',
        ASM: 'American Samoa',
        AND: 'Andorra',
        AGO: 'Angola',
        AIA: 'Anguilla',
        ATA: 'Antarctica',
        ATG: 'Antigua and Barbuda',
        ARG: 'Argentina',
        ARM: 'Armenia',
        ABW: 'Aruba',
        AUS: 'Australia',
        AUT: 'Austria',
        AZE: 'Azerbaijan',
        BHS: 'Bahamas',
        BHR: 'Bahrain',
        BGD: 'Bangladesh',
        BRB: 'Barbados',
        BLR: 'Belarus',
        BEL: 'Belgium',
        BLZ: 'Belize',
        BEN: 'Benin',
        BMU: 'Bermuda',
        BTN: 'Bhutan',
        BOL: 'Bolivia (Plurinational State of)',
        BES: 'Bonaire, Sint Eustatius and Saba',
        BIH: 'Bosnia and Herzegovina',
        BWA: 'Botswana',
        BVT: 'Bouvet Island',
        BRA: 'Brazil',
        IOT: 'British Indian Ocean Territory',
        VGB: 'British Virgin Islands',
        BRN: 'Brunei Darussalam',
        BGR: 'Bulgaria',
        BFA: 'Burkina Faso',
        BDI: 'Burundi',
        CPV: 'Cabo Verde',
        KHM: 'Cambodia',
        CMR: 'Cameroon',
        CAN: 'Canada',
        CYM: 'Cayman Islands',
        CAF: 'Central African Republic',
        TCD: 'Chad',
        CHL: 'Chile',
        CHN: 'China',
        HKG: 'China, Hong Kong Special Administrative Region',
        MAC: 'China, Macao Special Administrative Region',
        CXR: 'Christmas Island',
        CCK: 'Cocos (Keeling) Islands',
        COL: 'Colombia',
        COM: 'Comoros',
        COG: 'Congo',
        COK: 'Cook Islands',
        CRI: 'Costa Rica',
        CIV: "Côte d'Ivoire",
        HRV: 'Croatia',
        CUB: 'Cuba',
        CUW: 'Curaçao',
        CYP: 'Cyprus',
        CZE: 'Czechia',
        PRK: "Democratic People's Republic of Korea",
        COD: 'Democratic Republic of the Congo',
        DNK: 'Denmark',
        DJI: 'Djibouti',
        DMA: 'Dominica',
        DOM: 'Dominican Republic',
        ECU: 'Ecuador',
        EGY: 'Egypt',
        SLV: 'El Salvador',
        GNQ: 'Equatorial Guinea',
        ERI: 'Eritrea',
        EST: 'Estonia',
        ETH: 'Ethiopia',
        FLK: 'Falkland Islands (Malvinas)',
        FRO: 'Faroe Islands',
        FJI: 'Fiji',
        FIN: 'Finland',
        FRA: 'France',
        GUF: 'French Guiana',
        PYF: 'French Polynesia',
        ATF: 'French Southern Territories',
        GAB: 'Gabon',
        GMB: 'Gambia',
        GEO: 'Georgia',
        DEU: 'Germany',
        GHA: 'Ghana',
        GIB: 'Gibraltar',
        GRC: 'Greece',
        GRL: 'Greenland',
        GRD: 'Grenada',
        GLP: 'Guadeloupe',
        GUM: 'Guam',
        GTM: 'Guatemala',
        GGY: 'Guernsey',
        GIN: 'Guinea',
        GNB: 'Guinea-Bissau',
        GUY: 'Guyana',
        HTI: 'Haiti',
        HMD: 'Heard Island and McDonald Islands',
        VAT: 'Holy See',
        HND: 'Honduras',
        HUN: 'Hungary',
        ISL: 'Iceland',
        IND: 'India',
        IDN: 'Indonesia',
        IRN: 'Iran (Islamic Republic of)',
        IRQ: 'Iraq',
        IRL: 'Ireland',
        IMN: 'Isle of Man',
        ISR: 'Israel',
        ITA: 'Italy',
        JAM: 'Jamaica',
        JPN: 'Japan',
        JEY: 'Jersey',
        JOR: 'Jordan',
        KAZ: 'Kazakhstan',
        KEN: 'Kenya',
        KIR: 'Kiribati',
        KWT: 'Kuwait',
        KGZ: 'Kyrgyzstan',
        LAO: "Lao People's Democratic Republic",
        LVA: 'Latvia',
        LBN: 'Lebanon',
        LSO: 'Lesotho',
        LBR: 'Liberia',
        LBY: 'Libya',
        LIE: 'Liechtenstein',
        LTU: 'Lithuania',
        LUX: 'Luxembourg',
        MDG: 'Madagascar',
        MWI: 'Malawi',
        MYS: 'Malaysia',
        MDV: 'Maldives',
        MLI: 'Mali',
        MLT: 'Malta',
        MHL: 'Marshall Islands',
        MTQ: 'Martinique',
        MRT: 'Mauritania',
        MUS: 'Mauritius',
        MYT: 'Mayotte',
        MEX: 'Mexico',
        FSM: 'Micronesia (Federated States of)',
        MCO: 'Monaco',
        MNG: 'Mongolia',
        MNE: 'Montenegro',
        MSR: 'Montserrat',
        MAR: 'Morocco',
        MOZ: 'Mozambique',
        MMR: 'Myanmar',
        NAM: 'Namibia',
        NRU: 'Nauru',
        NPL: 'Nepal',
        NLD: 'Netherlands',
        NCL: 'New Caledonia',
        NZL: 'New Zealand',
        NIC: 'Nicaragua',
        NER: 'Niger',
        NGA: 'Nigeria',
        NIU: 'Niue',
        NFK: 'Norfolk Island',
        MNP: 'Northern Mariana Islands',
        NOR: 'Norway',
        OMN: 'Oman',
        PAK: 'Pakistan',
        PLW: 'Palau',
        PAN: 'Panama',
        PNG: 'Papua New Guinea',
        PRY: 'Paraguay',
        PER: 'Peru',
        PHL: 'Philippines',
        PCN: 'Pitcairn',
        POL: 'Poland',
        PRT: 'Portugal',
        PRI: 'Puerto Rico',
        QAT: 'Qatar',
        KOR: 'Republic of Korea',
        MDA: 'Republic of Moldova',
        REU: 'Réunion',
        ROU: 'Romania',
        RUS: 'Russian Federation',
        RWA: 'Rwanda',
        BLM: 'Saint Barthélemy',
        SHN: 'Saint Helena',
        KNA: 'Saint Kitts and Nevis',
        LCA: 'Saint Lucia',
        MAF: 'Saint Martin (French Part)',
        SPM: 'Saint Pierre and Miquelon',
        VCT: 'Saint Vincent and the Grenadines',
        WSM: 'Samoa',
        SMR: 'San Marino',
        STP: 'Sao Tome and Principe',
        SAU: 'Sark 680 Saudi Arabia',
        SEN: 'Senegal',
        SRB: 'Serbia',
        SYC: 'Seychelles',
        SLE: 'Sierra Leone',
        SGP: 'Singapore',
        SXM: 'Sint Maarten (Dutch part)',
        SVK: 'Slovakia',
        SVN: 'Slovenia',
        SLB: 'Solomon Islands',
        SOM: 'Somalia',
        ZAF: 'South Africa',
        SGS: 'South Georgia and the South Sandwich Islands',
        SSD: 'South Sudan',
        ESP: 'Spain',
        LKA: 'Sri Lanka',
        PSE: 'State of Palestine',
        SDN: 'Sudan',
        SUR: 'Suriname',
        SJM: 'Svalbard and Jan Mayen Islands',
        SWZ: 'Swaziland',
        SWE: 'Sweden',
        CHE: 'Switzerland',
        SYR: 'Syrian Arab Republic',
        TJK: 'Tajikistan',
        THA: 'Thailand',
        MKD: 'The former Yugoslav Republic of Macedonia',
        TLS: 'Timor-Leste',
        TGO: 'Togo',
        TKL: 'Tokelau',
        TON: 'Tonga',
        TTO: 'Trinidad and Tobago',
        TUN: 'Tunisia',
        TUR: 'Turkey',
        TKM: 'Turkmenistan',
        TCA: 'Turks and Caicos Islands',
        TUV: 'Tuvalu',
        UGA: 'Uganda',
        UKR: 'Ukraine',
        ARE: 'United Arab Emirates',
        GBR: 'United Kingdom of Great Britain and Northern Ireland',
        TZA: 'United Republic of Tanzania',
        UMI: 'United States Minor Outlying Islands',
        USA: 'United States of America',
        VIR: 'United States Virgin Islands',
        URY: 'Uruguay',
        UZB: 'Uzbekistan',
        VUT: 'Vanuatu',
        VEN: 'Venezuela (Bolivarian Republic of)',
        VNM: 'Viet Nam',
        WLF: 'Wallis and Futuna Islands',
        ESH: 'Western Sahara',
        YEM: 'Yemen',
        ZMB: 'Zambia',
        ZWE: 'Zimbabwe',
    },

    countries: [
        { name: 'Afghanistan', code: 'AFG' },
        { name: 'Åland Islands', code: 'ALA' },
        {
            name: 'Albania',
            code: 'ALB',
        },
        { name: 'Algeria', code: 'DZA' },
        { name: 'American Samoa', code: 'ASM' },
        {
            name: 'Andorra',
            code: 'AND',
        },
        { name: 'Angola', code: 'AGO' },
        { name: 'Anguilla', code: 'AIA' },
        {
            name: 'Antarctica',
            code: 'ATA',
        },
        { name: 'Antigua and Barbuda', code: 'ATG' },
        { name: 'Argentina', code: 'ARG' },
        {
            name: 'Armenia',
            code: 'ARM',
        },
        { name: 'Aruba', code: 'ABW' },
        { name: 'Australia', code: 'AUS' },
        {
            name: 'Austria',
            code: 'AUT',
        },
        { name: 'Azerbaijan', code: 'AZE' },
        { name: 'Bahamas', code: 'BHS' },
        {
            name: 'Bahrain',
            code: 'BHR',
        },
        { name: 'Bangladesh', code: 'BGD' },
        { name: 'Barbados', code: 'BRB' },
        {
            name: 'Belarus',
            code: 'BLR',
        },
        { name: 'Belgium', code: 'BEL' },
        { name: 'Belize', code: 'BLZ' },
        {
            name: 'Benin',
            code: 'BEN',
        },
        { name: 'Bermuda', code: 'BMU' },
        {
            name: 'Bhutan',
            code: 'BTN',
        },
        { name: 'Bolivia (Plurinational State of)', code: 'BOL' },
        {
            name: 'Bonaire, Sint Eustatius and Saba',
            code: 'BES',
        },
        { name: 'Bosnia and Herzegovina', code: 'BIH' },
        {
            name: 'Botswana',
            code: 'BWA',
        },
        { name: 'Bouvet Island', code: 'BVT' },
        {
            name: 'Brazil',
            code: 'BRA',
        },
        { name: 'British Indian Ocean Territory', code: 'IOT' },
        {
            name: 'British Virgin Islands',
            code: 'VGB',
        },
        { name: 'Brunei Darussalam', code: 'BRN' },
        { name: 'Bulgaria', code: 'BGR' },
        {
            name: 'Burkina Faso',
            code: 'BFA',
        },
        { name: 'Burundi', code: 'BDI' },
        { name: 'Cabo Verde', code: 'CPV' },
        {
            name: 'Cambodia',
            code: 'KHM',
        },
        { name: 'Cameroon', code: 'CMR' },
        { name: 'Canada', code: 'CAN' },
        {
            name: 'Cayman Islands',
            code: 'CYM',
        },
        { name: 'Central African Republic', code: 'CAF' },
        { name: 'Chad', code: 'TCD' },
        {
            name: 'Chile',
            code: 'CHL',
        },
        { name: 'China', code: 'CHN' },
        {
            name: 'China, Hong Kong Special Administrative Region',
            code: 'HKG',
        },
        { name: 'China, Macao Special Administrative Region', code: 'MAC' },
        {
            name: 'Christmas Island',
            code: 'CXR',
        },
        { name: 'Cocos (Keeling) Islands', code: 'CCK' },
        { name: 'Colombia', code: 'COL' },
        {
            name: 'Comoros',
            code: 'COM',
        },
        { name: 'Congo', code: 'COG' },
        { name: 'Cook Islands', code: 'COK' },
        {
            name: 'Costa Rica',
            code: 'CRI',
        },
        { name: "Côte d'Ivoire", code: 'CIV' },
        { name: 'Croatia', code: 'HRV' },
        {
            name: 'Cuba',
            code: 'CUB',
        },
        { name: 'Curaçao', code: 'CUW' },
        { name: 'Cyprus', code: 'CYP' },
        {
            name: 'Czechia',
            code: 'CZE',
        },
        { name: "Democratic People's Republic of Korea", code: 'PRK' },
        {
            name: 'Democratic Republic of the Congo',
            code: 'COD',
        },
        { name: 'Denmark', code: 'DNK' },
        { name: 'Djibouti', code: 'DJI' },
        {
            name: 'Dominica',
            code: 'DMA',
        },
        { name: 'Dominican Republic', code: 'DOM' },
        { name: 'Ecuador', code: 'ECU' },
        {
            name: 'Egypt',
            code: 'EGY',
        },
        { name: 'El Salvador', code: 'SLV' },
        { name: 'Equatorial Guinea', code: 'GNQ' },
        {
            name: 'Eritrea',
            code: 'ERI',
        },
        { name: 'Estonia', code: 'EST' },
        { name: 'Ethiopia', code: 'ETH' },
        {
            name: 'Falkland Islands (Malvinas)',
            code: 'FLK',
        },
        { name: 'Faroe Islands', code: 'FRO' },
        { name: 'Fiji', code: 'FJI' },
        {
            name: 'Finland',
            code: 'FIN',
        },
        { name: 'France', code: 'FRA' },
        { name: 'French Guiana', code: 'GUF' },
        {
            name: 'French Polynesia',
            code: 'PYF',
        },
        { name: 'French Southern Territories', code: 'ATF' },
        { name: 'Gabon', code: 'GAB' },
        {
            name: 'Gambia',
            code: 'GMB',
        },
        { name: 'Georgia', code: 'GEO' },
        { name: 'Germany', code: 'DEU' },
        {
            name: 'Ghana',
            code: 'GHA',
        },
        { name: 'Gibraltar', code: 'GIB' },
        { name: 'Greece', code: 'GRC' },
        {
            name: 'Greenland',
            code: 'GRL',
        },
        { name: 'Grenada', code: 'GRD' },
        { name: 'Guadeloupe', code: 'GLP' },
        {
            name: 'Guam',
            code: 'GUM',
        },
        { name: 'Guatemala', code: 'GTM' },
        { name: 'Guernsey', code: 'GGY' },
        {
            name: 'Guinea',
            code: 'GIN',
        },
        { name: 'Guinea-Bissau', code: 'GNB' },
        { name: 'Guyana', code: 'GUY' },
        {
            name: 'Haiti',
            code: 'HTI',
        },
        { name: 'Heard Island and McDonald Islands', code: 'HMD' },
        {
            name: 'Holy See',
            code: 'VAT',
        },
        { name: 'Honduras', code: 'HND' },
        { name: 'Hungary', code: 'HUN' },
        {
            name: 'Iceland',
            code: 'ISL',
        },
        { name: 'India', code: 'IND' },
        { name: 'Indonesia', code: 'IDN' },
        {
            name: 'Iran (Islamic Republic of)',
            code: 'IRN',
        },
        { name: 'Iraq', code: 'IRQ' },
        { name: 'Ireland', code: 'IRL' },
        {
            name: 'Isle of Man',
            code: 'IMN',
        },
        { name: 'Israel', code: 'ISR' },
        { name: 'Italy', code: 'ITA' },
        {
            name: 'Jamaica',
            code: 'JAM',
        },
        { name: 'Japan', code: 'JPN' },
        { name: 'Jersey', code: 'JEY' },
        {
            name: 'Jordan',
            code: 'JOR',
        },
        { name: 'Kazakhstan', code: 'KAZ' },
        { name: 'Kenya', code: 'KEN' },
        {
            name: 'Kiribati',
            code: 'KIR',
        },
        { name: 'Kuwait', code: 'KWT' },
        {
            name: 'Kyrgyzstan',
            code: 'KGZ',
        },
        { name: "Lao People's Democratic Republic", code: 'LAO' },
        {
            name: 'Latvia',
            code: 'LVA',
        },
        { name: 'Lebanon', code: 'LBN' },
        { name: 'Lesotho', code: 'LSO' },
        {
            name: 'Liberia',
            code: 'LBR',
        },
        { name: 'Libya', code: 'LBY' },
        { name: 'Liechtenstein', code: 'LIE' },
        {
            name: 'Lithuania',
            code: 'LTU',
        },
        { name: 'Luxembourg', code: 'LUX' },
        { name: 'Madagascar', code: 'MDG' },
        {
            name: 'Malawi',
            code: 'MWI',
        },
        { name: 'Malaysia', code: 'MYS' },
        { name: 'Maldives', code: 'MDV' },
        {
            name: 'Mali',
            code: 'MLI',
        },
        { name: 'Malta', code: 'MLT' },
        { name: 'Marshall Islands', code: 'MHL' },
        {
            name: 'Martinique',
            code: 'MTQ',
        },
        { name: 'Mauritania', code: 'MRT' },
        { name: 'Mauritius', code: 'MUS' },
        {
            name: 'Mayotte',
            code: 'MYT',
        },
        { name: 'Mexico', code: 'MEX' },
        {
            name: 'Micronesia (Federated States of)',
            code: 'FSM',
        },
        { name: 'Monaco', code: 'MCO' },
        { name: 'Mongolia', code: 'MNG' },
        {
            name: 'Montenegro',
            code: 'MNE',
        },
        { name: 'Montserrat', code: 'MSR' },
        { name: 'Morocco', code: 'MAR' },
        {
            name: 'Mozambique',
            code: 'MOZ',
        },
        { name: 'Myanmar', code: 'MMR' },
        { name: 'Namibia', code: 'NAM' },
        {
            name: 'Nauru',
            code: 'NRU',
        },
        { name: 'Nepal', code: 'NPL' },
        { name: 'Netherlands', code: 'NLD' },
        {
            name: 'New Caledonia',
            code: 'NCL',
        },
        { name: 'New Zealand', code: 'NZL' },
        { name: 'Nicaragua', code: 'NIC' },
        {
            name: 'Niger',
            code: 'NER',
        },
        { name: 'Nigeria', code: 'NGA' },
        { name: 'Niue', code: 'NIU' },
        {
            name: 'Norfolk Island',
            code: 'NFK',
        },
        { name: 'Northern Mariana Islands', code: 'MNP' },
        { name: 'Norway', code: 'NOR' },
        {
            name: 'Oman',
            code: 'OMN',
        },
        { name: 'Pakistan', code: 'PAK' },
        { name: 'Palau', code: 'PLW' },
        {
            name: 'Panama',
            code: 'PAN',
        },
        { name: 'Papua New Guinea', code: 'PNG' },
        { name: 'Paraguay', code: 'PRY' },
        {
            name: 'Peru',
            code: 'PER',
        },
        { name: 'Philippines', code: 'PHL' },
        { name: 'Pitcairn', code: 'PCN' },
        {
            name: 'Poland',
            code: 'POL',
        },
        { name: 'Portugal', code: 'PRT' },
        { name: 'Puerto Rico', code: 'PRI' },
        {
            name: 'Qatar',
            code: 'QAT',
        },
        { name: 'Republic of Korea', code: 'KOR' },
        {
            name: 'Republic of Moldova',
            code: 'MDA',
        },
        { name: 'Réunion', code: 'REU' },
        { name: 'Romania', code: 'ROU' },
        {
            name: 'Russian Federation',
            code: 'RUS',
        },
        { name: 'Rwanda', code: 'RWA' },
        { name: 'Saint Barthélemy', code: 'BLM' },
        {
            name: 'Saint Helena',
            code: 'SHN',
        },
        { name: 'Saint Kitts and Nevis', code: 'KNA' },
        {
            name: 'Saint Lucia',
            code: 'LCA',
        },
        { name: 'Saint Martin (French Part)', code: 'MAF' },
        {
            name: 'Saint Pierre and Miquelon',
            code: 'SPM',
        },
        { name: 'Saint Vincent and the Grenadines', code: 'VCT' },
        {
            name: 'Samoa',
            code: 'WSM',
        },
        { name: 'San Marino', code: 'SMR' },
        {
            name: 'Sao Tome and Principe',
            code: 'STP',
        },
        { name: 'Sark 680 Saudi Arabia', code: 'SAU' },
        { name: 'Senegal', code: 'SEN' },
        {
            name: 'Serbia',
            code: 'SRB',
        },
        { name: 'Seychelles', code: 'SYC' },
        { name: 'Sierra Leone', code: 'SLE' },
        {
            name: 'Singapore',
            code: 'SGP',
        },
        { name: 'Sint Maarten (Dutch part)', code: 'SXM' },
        { name: 'Slovakia', code: 'SVK' },
        {
            name: 'Slovenia',
            code: 'SVN',
        },
        { name: 'Solomon Islands', code: 'SLB' },
        { name: 'Somalia', code: 'SOM' },
        {
            name: 'South Africa',
            code: 'ZAF',
        },
        { name: 'South Georgia and the South Sandwich Islands', code: 'SGS' },
        {
            name: 'South Sudan',
            code: 'SSD',
        },
        { name: 'Spain', code: 'ESP' },
        { name: 'Sri Lanka', code: 'LKA' },
        {
            name: 'State of Palestine',
            code: 'PSE',
        },
        { name: 'Sudan', code: 'SDN' },
        {
            name: 'Suriname',
            code: 'SUR',
        },
        { name: 'Svalbard and Jan Mayen Islands', code: 'SJM' },
        {
            name: 'Swaziland',
            code: 'SWZ',
        },
        { name: 'Sweden', code: 'SWE' },
        { name: 'Switzerland', code: 'CHE' },
        {
            name: 'Syrian Arab Republic',
            code: 'SYR',
        },
        { name: 'Tajikistan', code: 'TJK' },
        {
            name: 'Thailand',
            code: 'THA',
        },
        { name: 'The former Yugoslav Republic of Macedonia', code: 'MKD' },
        {
            name: 'Timor-Leste',
            code: 'TLS',
        },
        { name: 'Togo', code: 'TGO' },
        { name: 'Tokelau', code: 'TKL' },
        {
            name: 'Tonga',
            code: 'TON',
        },
        { name: 'Trinidad and Tobago', code: 'TTO' },
        { name: 'Tunisia', code: 'TUN' },
        {
            name: 'Turkey',
            code: 'TUR',
        },
        { name: 'Turkmenistan', code: 'TKM' },
        { name: 'Turks and Caicos Islands', code: 'TCA' },
        {
            name: 'Tuvalu',
            code: 'TUV',
        },
        { name: 'Uganda', code: 'UGA' },
        { name: 'Ukraine', code: 'UKR' },
        {
            name: 'United Arab Emirates',
            code: 'ARE',
        },
        {
            name: 'United Kingdom of Great Britain and Northern Ireland',
            code: 'GBR',
        },
        { name: 'United Republic of Tanzania', code: 'TZA' },
        {
            name: 'United States Minor Outlying Islands',
            code: 'UMI',
        },
        { name: 'United States of America', code: 'USA' },
        {
            name: 'United States Virgin Islands',
            code: 'VIR',
        },
        { name: 'Uruguay', code: 'URY' },
        { name: 'Uzbekistan', code: 'UZB' },
        {
            name: 'Vanuatu',
            code: 'VUT',
        },
        { name: 'Venezuela (Bolivarian Republic of)', code: 'VEN' },
        {
            name: 'Viet Nam', code: 'VNM',
        },
        { name: 'Wallis and Futuna Islands', code: 'WLF' },
        { name: 'Western Sahara', code: 'ESH', },
        { name: 'Yemen', code: 'YEM' },
        { name: 'Zambia', code: 'ZMB' },
        { name: 'Zimbabwe', code: 'ZWE' },
    ]
};
