{
  "label_text_app_subtitle":"Limpiemos el mundo juntos!",
  "label_button_facebook":"Ingresar con Facebook",
  "label_button_google":"Ingresar con Google",
  "label_button_try_app":"Probar la aplicación sin cuenta",
  "label_button_acknowledge":"Ok, lo consiguió!",
  "label_button_cancel":"Cancelar",
  "label_button_continue":"Continuar",
  "label_trash_status_threat":"amenaza",
  "label_trash_status_regular":"regular",
  "label_trash_status_cleaned":"limpiado",
  "label_trash_status_outdated":"desactualizado",
  "label_trash_status_user":"usuario",
  "label_trash_status_change_location":"cambiar ubicación",
  "label_trash_status_state_threat":"Este punto es una amenaza!",
  "label_trash_status_state_regular":"Se trata de un punto de basura cotidiano.",
  "label_trash_status_state_cleaned":"Este punto se limpió!",
  "label_trash_status_state_outdated":"Este punto esta desactualizado!",
  "label_TP_created_date":"Creado",
  "label_TP_updated_date":"Actualizado",
  "label_TP_by":" por ",
  "label_trash_amount_handful":"puñado",
  "label_trash_amount_bagful":"bolsa llena",
  "label_trash_amount_cartloadl":"carro lleno",
  "label_trash_amount_truckload":"camión",
  "label_trash_type_plastic":"Plástico",
  "label_trash_type_metal":"Metal",
  "label_trash_type_glass":"Vidrio",
  "label_trash_type_electro":"Electrónicos",
  "label_trash_type_paper":"Papel/Madera",
  "label_trash_type_tyres":"Neumáticos",
  "label_trash_type_dom_waste":"Residuos domiciliarios",
  "label_trash_type_furniture":"Muebles",
  "label_trash_type_org_waste":"Residuos orgánicos",
  "label_header_tc":"Términos y condiciones",
  "label_button_tc_agree":"Estoy de acuerdo con los términos y condiciones",
  "label_header_map":"Mapa",
  "label_text_popover_subtitle":"Únete a otras personas que están mapeando puntos de basura!",
  "label_text_popover_text":"Empieza a crear puntos de basura para hacer tu comunidad limpia y saludable.",
  "label_header_activity":"Mi actividad",
  "label_text_activity_empty_subtitle":"Nada para ver aquí!",
  "label_text_activity_empty_text":"Todavía no ha añadido ningún punto de basura. Cuando lo haga, se listarán aquí.",
  "label_text_activity_empty_hint":"Añade un punto de basura!",
  "label_header_notific":"Notificaciones",
  "label_text_notific_empty_subtitle":"Nada para ver aquí!",
  "label_text_notific_empty_text":"No hemos visto ninguna notificación ingresante todavía, pero le haremos saber cuando lo hagamos!",
  "label_header_profile":"Mi perfil",
  "label_header_settings":"Configuración de la cuenta",
  "label_button_country_empty":"País",
  "label_text_country":"País",
  "label_header_select_country":"Seleccione un país",
  "label_text_select_country_hint":"Búsqueda",
  "label_button_tc":"Términos y condiciones",
  "label_button_logout":"Cerrar sesión",
  "label_text_congrats_image":"Basura capturada",
  "label_text_congrats_subtitle":"Buen trabajo!",
  "label_text_congrats_text":"Ahora guarde el punto mediante la verificación de los datos.",
  "label_header_createTP":"Crear un punto de basura",
  "label_button_createTP_editloc":"Editar ubicación",
  "label_header_edit_loc":"Editar ubicación",
  "label_button_edit_loc_set":"Configurar ubicación del punto de basura",
  "label_text_createTP_status_subtitle":"Estado de los puntos",
  "label_text_createTP_status_text":"Si una acción rápida es necesaria (residuos tóxicos, metales pesados), por favor configúrelo como amenaza.",
  "label_text_createTP_add_photos":"Añadir fotos de basura",
  "label_text_createTP_select_amount":"Seleccione la cantidad de basura",
  "label_text_createTP_select_type":"Seleccione el tipo de basura",
  "label_text_createTP_add_hashtags":"Agregue etiquetas adicionales",
  "label_text_createTP_add_hashtags_hint":"ejemplo: #nombremarca, #latas",
  "label_button_createTP_confirm_create":"Crear un punto de basura",
  "label_alert_createTP_success":"Punto de basura creado exitosamente",
  "label_text_detailsTP_photos":"Fotos de la basura",
  "label_text_detailsTP_amount":"Cantidad de basura",
  "label_text_detailsTP_type":"Tipo de basura",
  "label_text_editTP_ask":"Esta información del punto de basura todavía es correcta y actualizada?",
  "label_text_editTP_letsconfirm":"Sí, confirmo",
  "label_alert_editTP_confirm":"Punto de basura confirmado exitosamente",
  "label_text_editTP_letsedit":"No, vamos a editarlo",
  "label_header_editTP":"Edite un punto de basura",
  "label_button_editTP_save":"Guardar los cambios del punto de basura",
  "label_alert_editTP_edit":"Punto de basura actualizado exitosamente",
  "label_alert_editTP_delete":"Punto de basura borrado exitosamente",
  "label_error_editTP_out_of_rng_subtitle":"Fuera de rango",
  "label_error_editTP_out_of_rng_text":"Un punto sólo puede ser editado si usted se encuentra en un radio de 100 metros de el.",
  "label_error_saveTP_subtitle":"Guardar punto de basura",
  "label_error_saveTP_pic_and_type":"Es más útil para nosotros si por lo menos toma una foto del punto de basura y nos dice los tipos de basura que contiene.",
  "label_error_saveTP_picture":"Es más útil para nosotros si por lo menos toma una foto del punto de basura antes de guardarlo.",
  "label_error_saveTP_trash_type":"Es más útil para nosotros si se establece el tipo de basura en el punto antes de guardar.",
  "label_error_change_loc_subtitle":"Fuera de los límites",
  "label_error_change_loc_text":"Favor de establezca un punto dentro de los 100 metros de su ubicación.",
  "label_error_generic_error_subtitle":"Fuera de los límites",
  "label_error_generic_error_text":"Hubo un error en el servidor.",
  "label_error_network_subtitle":"Sin conexión de red",
  "label_error_network_text":"Datos móviles desactivados. Activar datos móviles o conectar el teléfono con Wi-Fi para utilizar la aplicación.",
  "label_error_location_subtitle":"Habilitar ubicación",
  "label_error_location_text":"Servicios de localización están apagados. Por favor, active el GPS en Configuración, para utilizar la aplicación.",
  "label_error_loc_permission_text":"Servicios de localización, no permitidos. Por favor habilítelos para poder utilizar la aplicación.",
  "label_trash_details_header":"Detalles del punto de basura",
  "label_privacy_policy_header":"Política de privacidad",
  "label_about_header":"Acerca de",
  "label_edit_trashpoint_button":"Edite un punto de basura",
  "label_100m_limit_modal":"A point can only be edited if you are within 100 meters of it.",
  "label_retry_button":"Retry",
  "label_country_picker_placeholder":"Choose your country",
  "label_camera_permission_warning_ios":"You must change camera access permissions. To do this, go to Settings > Privacy > Camera",
  "label_camera_permission_warning_android":"You must change camera access permissions. To do this, go to Settings > Apps",
  "label_camera_error_title":"Camera Access Denied",
  "label_error_modal_default_title":"Oh noes!",
  "label_error_modal_default_subtitle":"The fail whale detected a server error!",
  "label_location_permission_warning_ios":"You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android":"You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning":"Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title":"Enable location",
  "label_network_off_warning_title":"No network connection",
  "label_network_off_warning":"Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text":"Almost there...",
  "label_loading_image_subtext":"Please wait while we save your actions.",
  "label_create_marker_missing_photos":"The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos":"The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos":"The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete":"Delete",
  "label_delete_photo_title":"Delete photo",
  "label_delete_photo_subtitle":"Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1":"This app is an initiative by Let's Do It World",
  "label_text_about_2":"All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3":"This app is a joint cooperation with",
  "label_button_editTP_delete":"Delete trashpoint",
  "label_locked_account_warning":"Your account is locked. For details contact an administrator."
}