{
  "label_text_app_subtitle": "Vamos a limpiar el mundo juntos!",
  "label_button_facebook": "Continuar con Facebook",
  "label_button_google": "Continuar con Google",
  "label_button_try_app": "Probar la aplicación sin cuenta",
  "label_button_acknowledge": "¡Ok, lo entiendo!",
  "label_button_cancel": "Cancelar",
  "label_button_continue": "Continuar",
  "label_trash_status_threat": "amenaza",
  "label_trash_status_regular": "regular",
  "label_trash_status_cleaned": "limpio",
  "label_trash_status_outdated": "obsoleto",
  "label_trash_status_user": "usuario",
  "label_trash_status_change_location": "changeLocation",
  "label_trash_status_state_threat": "¡Este punto es una amenaza!",
  "label_trash_status_state_regular": "This is a regular trashpoint.",
  "label_trash_status_state_cleaned": "¡Este punto está limpio!",
  "label_trash_status_state_outdated": "¡Este punto es obsoleto!",
  "label_TP_created_date": "Creado",
  "label_TP_updated_date": "Actualizado",
  "label_TP_by": " por ",
  "label_trash_amount_handful": "handful",
  "label_trash_amount_bagful": "bagful",
  "label_trash_amount_cartloadl": "cartload",
  "label_trash_amount_truckload": "truckload",
  "label_trash_type_plastic": "Plástico",
  "label_trash_type_metal": "Metal",
  "label_trash_type_glass": "Vidrio",
  "label_trash_type_electro": "Electrónicos",
  "label_trash_type_paper": "Papel/Madera",
  "label_trash_type_tyres": "Neumáticos",
  "label_trash_type_dom_waste": "Desechos domésticos",
  "label_trash_type_furniture": "Muebles",
  "label_trash_type_org_waste": "Residuos orgánicos",
  "label_header_tc": "Términos y condiciones",
  "label_button_tc_agree": "Estoy de acuerdo con los términos y condiciones",
  "label_header_map": "Mapa",
  "label_text_popover_subtitle": "Únete a otras personas que están mapeando basura!",
  "label_text_popover_text": "Start creating trashpoints to make your community cleaner and healthier.",
  "label_header_activity": "Mi actividad",
  "label_text_activity_empty_subtitle": "Nada que ver aquí!",
  "label_text_activity_empty_text": "You haven't added any trashpoints yet. When you do, they will be listed here.",
  "label_text_activity_empty_hint": "Add a trashpoint!",
  "label_header_notific": "Notificaciones",
  "label_text_notific_empty_subtitle": "Nada que ver aquí!",
  "label_text_notific_empty_text": "No hemos visto ninguna notificación todavía, pero te lo haremos saber cuando lo hagamos.",
  "label_header_profile": "Mi perfil",
  "label_header_settings": "Configuración de la cuenta",
  "label_button_country_empty": "País",
  "label_text_country": "País",
  "label_header_select_country": "Seleccione un país",
  "label_text_select_country_hint": "Buscar",
  "label_button_tc": "Terms and Conditions",
  "label_button_logout": "Log out",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Great job!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Edit location",
  "label_header_edit_loc": "Edit location",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Habilitar ubicación",
  "label_error_location_text": "Los servicios de localización están desactivados. Active el GPS en la configuración para usar la aplicación.",
  "label_error_loc_permission_text": "No están permitidos los servicios de localización. Permítalos para poder usar la aplicación.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Política de privacidad",
  "label_about_header": "Acerca de",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "Un punto sólo puede editarse estando a 100 metros o menos de él.",
  "label_retry_button": "Reintentar",
  "label_country_picker_placeholder": "Elija su país",
  "label_camera_permission_warning_ios": "Debe cambiar los permisos de acceso de la cámara. Para ello, vaya a Configuración > Privacidad > Cámara",
  "label_camera_permission_warning_android": "Debe cambiar los permisos de acceso de la cámara. Para ello, vaya a Configuración > Aplicaciones",
  "label_camera_error_title": "Acceso denegado a la cámara",
  "label_error_modal_default_title": "Oh no!",
  "label_error_modal_default_subtitle": "La ballena de los errores ha detectado un error de servidor.",
  "label_location_permission_warning_ios": "You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Habilitar localización",
  "label_network_off_warning_title": "Ninguna conexión de red",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Ya casi...",
  "label_loading_image_subtext": "Espere mientras guardamos sus acciones.",
  "label_create_marker_missing_photos": "No se pudieron cargar las fotos de marcador. Trate de agregarlas otra vez.",
  "label_edit_marker_missing_photos": "No se pudieron cargar las fotos de marcador. Trate de agregarlas otra vez.",
  "label_confirm_marker_missing_photos": "No se pudieron cargar las fotos de marcador. Trate de agregarlas otra vez.",
  "label_button_delete": "Eliminar",
  "label_delete_photo_title": "Borrar foto",
  "label_delete_photo_subtitle": "¿Seguro que desea eliminar la foto? No se puede deshacer.",
  "label_text_about_1": "Esta aplicación es una iniciativa de Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Producto de Estonia, patrocinado por el país y el gobierno",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}