{
  "label_text_app_subtitle": "Koristame maailma koos!",
  "label_button_facebook": "Logi sisse Facebookiga",
  "label_button_google": " Logi sisse Google'iga",
  "label_button_try_app": "Proovi rakendust ilma sisselogimata",
  "label_button_acknowledge": "Selge, sain aru!",
  "label_button_cancel": "Loobu",
  "label_button_continue": "Jätka",
  "label_trash_status_threat": "oht",
  "label_trash_status_regular": "tavaline",
  "label_trash_status_cleaned": "koristatud",
  "label_trash_status_outdated": "aegunud",
  "label_trash_status_user": "kasutaja",
  "label_trash_status_change_location": "muuda asukohta",
  "label_trash_status_state_threat": "Ohtlik prügi punkt!",
  "label_trash_status_state_regular": "Tavaline prügi punkt.",
  "label_trash_status_state_cleaned": "Koristatud punkt!",
  "label_trash_status_state_outdated": "Aegunud punkt!",
  "label_TP_created_date": "Loodud",
  "label_TP_updated_date": "Uuendatud",
  "label_TP_by": " ",
  "label_trash_amount_handful": "peotäis",
  "label_trash_amount_bagful": "kotitäis",
  "label_trash_amount_cartloadl": "kärutäis",
  "label_trash_amount_truckload": "autokoorem",
  "label_trash_type_plastic": "Plastik",
  "label_trash_type_metal": "Metall",
  "label_trash_type_glass": "Klaas",
  "label_trash_type_electro": "Elektroonika",
  "label_trash_type_paper": "Paber/puit",
  "label_trash_type_tyres": "Rehvid",
  "label_trash_type_dom_waste": "Majapidamisjäätmed",
  "label_trash_type_furniture": "Mööbel",
  "label_trash_type_org_waste": "Orgaanilised jäätmed",
  "label_header_tc": "Kasutustingimused",
  "label_button_tc_agree": "Nõustun kasutustingimustega",
  "label_header_map": "Kaart",
  "label_text_popover_subtitle": "Liitu prügi kaardistajatega!",
  "label_text_popover_text": "Alustada prügi punktide kaardistamist, et muuta oma ümbrus puhtamaks.",
  "label_header_activity": "Minu panus",
  "label_text_activity_empty_subtitle": "Pole veel midagi näidata!",
  "label_text_activity_empty_text": "Sa ei ole lisanud veel ühtegi prügi punkti. Kui lisad uue punkti, siis see ilmub siia.",
  "label_text_activity_empty_hint": "Lisa prügi punkt!",
  "label_header_notific": "Teated",
  "label_text_notific_empty_subtitle": "Pole veel midagi näidata!",
  "label_text_notific_empty_text": "Me ei ole uusi teateid näidata, kuid need saabuvas, siis kuvame neid siin!",
  "label_header_profile": "Minu profiil",
  "label_header_settings": "Konto sätted",
  "label_button_country_empty": "Riik",
  "label_text_country": "Riik",
  "label_header_select_country": "Valige riik",
  "label_text_select_country_hint": "Otsing",
  "label_button_tc": "Kasutustingimused",
  "label_button_logout": "Logi välja",
  "label_text_congrats_image": "Prügi pildistatud",
  "label_text_congrats_subtitle": "Hästi tehtud!",
  "label_text_congrats_text": "Lisa täiendavad andmed ja salvesta punkt.",
  "label_header_createTP": "Loo uus prügi punkt",
  "label_button_createTP_editloc": "Redigeeri asukohta",
  "label_header_edit_loc": "Redigeeri asukohta",
  "label_button_edit_loc_set": "Määra punkti asukoht",
  "label_text_createTP_status_subtitle": "Punkti staatus",
  "label_text_createTP_status_text": "Kui kiire tegutsemine on vajalik (mürgine, raskmetallid), palun märgi punkt kui ohtlik.",
  "label_text_createTP_add_photos": "Lisa prügist fotod",
  "label_text_createTP_select_amount": "Vali prügi kogus",
  "label_text_createTP_select_type": "Vali prügi liik",
  "label_text_createTP_add_hashtags": "Lisa täiendavaid märksõnu",
  "label_text_createTP_add_hashtags_hint": "N: #tootenimi, #purgid",
  "label_button_createTP_confirm_create": "Loo uus prügi punkt",
  "label_alert_createTP_success": "Prügi punkt edukalt loodud",
  "label_text_detailsTP_photos": "Prügi fotod",
  "label_text_detailsTP_amount": "Prügi kogus",
  "label_text_detailsTP_type": "Prügi tüüp",
  "label_text_editTP_ask": "Kas punkti info on õige ja ajakohane?",
  "label_text_editTP_letsconfirm": "Jah, kinnitan",
  "label_alert_editTP_confirm": "Prügi punkt edukalt kinnitatud",
  "label_text_editTP_letsedit": "Ei, muuta infot",
  "label_header_editTP": "Redigeeri prügi punkti",
  "label_button_editTP_save": "Salvesta muudatused",
  "label_alert_editTP_edit": "Prügi punkt edukalt uuendatud",
  "label_alert_editTP_delete": "Prügi punkt edukalt kustutatud",
  "label_error_editTP_out_of_rng_subtitle": "Vahemikust väljas",
  "label_error_editTP_out_of_rng_text": "Punkti saate muuta ainult siis, kui olete 100 meetri raadiuses.",
  "label_error_saveTP_subtitle": "Salvesta prügi punkt",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "Meist",
  "label_edit_trashpoint_button": "Redigeeri prügi punkti",
  "label_100m_limit_modal": "Punkti saate muuta ainult siis, kui olete 100 meetri raadiuses.",
  "label_retry_button": "Proovi uuesti",
  "label_country_picker_placeholder": "Valige riik",
  "label_camera_permission_warning_ios": "You must change camera access permissions. To do this, go to Settings > Privacy > Camera",
  "label_camera_permission_warning_android": "You must change camera access permissions. To do this, go to Settings > Apps",
  "label_camera_error_title": "Juurdepääs kaamerale keelatud",
  "label_error_modal_default_title": "Oh ei!",
  "label_error_modal_default_subtitle": "The fail whale detected a server error!",
  "label_location_permission_warning_ios": "You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Enable location",
  "label_network_off_warning_title": "No network connection",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Almost there...",
  "label_loading_image_subtext": "Please wait while we save your actions.",
  "label_create_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Kustuta",
  "label_delete_photo_title": "Kustuta foto",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_button_editTP_delete": "Kustuta prügi punkt",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}