{
  "label_text_app_subtitle": "Koristame koos terve maailma ära!",
  "label_button_facebook": "Logi sisse Facebookiga",
  "label_button_google": " Logi sisse Google'iga",
  "label_button_try_app": "Proovi rakendust ilma sisselogimata",
  "label_button_acknowledge": "Selge, sain aru!",
  "label_button_cancel": "Loobu",
  "label_button_continue": "Jätka",
  "label_trash_status_threat": "oht",
  "label_trash_status_regular": "tavaline",
  "label_trash_status_cleaned": "koristatud",
  "label_trash_status_outdated": "aegunud",
  "label_trash_status_user": "kasutaja",
  "label_trash_status_change_location": "muuda asukohta",
  "label_trash_status_state_threat": "Ohtlik prügipunkt!",
  "label_trash_status_state_regular": "Sage prügi leiukoht.",
  "label_trash_status_state_cleaned": "Koristatud prügipunkt!",
  "label_trash_status_state_outdated": "Aegunud prügipunkt!",
  "label_TP_created_date": "Loodud",
  "label_TP_updated_date": "Uuendatud",
  "label_TP_by": " ",
  "label_trash_amount_handful": "peotäis",
  "label_trash_amount_bagful": "kotitäis",
  "label_trash_amount_cartloadl": "kärutäis",
  "label_trash_amount_truckload": "autokoorem",
  "label_trash_type_plastic": "Plastik",
  "label_trash_type_metal": "Metall",
  "label_trash_type_glass": "Klaas",
  "label_trash_type_electro": "Elektroonika",
  "label_trash_type_paper": "Paber/puit",
  "label_trash_type_tyres": "Rehvid",
  "label_trash_type_dom_waste": "Majapidamisjäätmed",
  "label_trash_type_furniture": "Mööbel",
  "label_trash_type_org_waste": "Orgaanilised jäätmed",
  "label_header_tc": "Kasutustingimused",
  "label_button_tc_agree": "Nõustun kasutustingimustega",
  "label_header_map": "Kaart",
  "label_text_popover_subtitle": "Liitu prügi kaardistajatega!",
  "label_text_popover_text": "Alusta prügi leiukohtade kaardistamist, et muuta oma ümbrus puhtamaks.",
  "label_header_activity": "Minu panus",
  "label_text_activity_empty_subtitle": "Ei paista midagi!",
  "label_text_activity_empty_text": "Sa ei ole lisanud veel ühtegi prügi leiukohta. Kui lisad uue leiukoha, siis see ilmub siia.",
  "label_text_activity_empty_hint": "Lisa prügi leiukoht!",
  "label_header_notific": "Teated",
  "label_text_notific_empty_subtitle": "Ei paista midagi!",
  "label_text_notific_empty_text": "Uusi teateid pole, ent kui need saabuvad, siis kuvame neid siin!",
  "label_header_profile": "Minu profiil",
  "label_header_settings": "Konto sätted",
  "label_button_country_empty": "Riik",
  "label_text_country": "Riik",
  "label_header_select_country": "Valige riik",
  "label_text_select_country_hint": "Otsing",
  "label_button_tc": "Kasutustingimused",
  "label_button_logout": "Logi välja",
  "label_text_congrats_image": "Prügi pildistatud",
  "label_text_congrats_subtitle": "Hästi tehtud!",
  "label_text_congrats_text": "Lisa täiendavad andmed ja salvesta leiukoht.",
  "label_header_createTP": "Loo uus prügi leiukoht",
  "label_button_createTP_editloc": "Redigeeri asukohta",
  "label_header_edit_loc": "Redigeeri asukohta",
  "label_button_edit_loc_set": "Määra prügi leiukoha asukoht",
  "label_text_createTP_status_subtitle": "Leiukoha staatus",
  "label_text_createTP_status_text": "Kui kiire tegutsemine on vajalik (mürgine, raskmetallid), palun märgi leiukoht ohtlikuks.",
  "label_text_createTP_add_photos": "Lisa prügist fotod",
  "label_text_createTP_select_amount": "Vali prügi kogus",
  "label_text_createTP_select_type": "Vali prügi liik",
  "label_text_createTP_add_hashtags": "Lisa täiendavaid märksõnu",
  "label_text_createTP_add_hashtags_hint": "näiteks: #tootenimi, #purgid",
  "label_button_createTP_confirm_create": "Loo uus prügi leiukoht",
  "label_alert_createTP_success": "Prügi leiukoht edukalt loodud",
  "label_text_detailsTP_photos": "Prügi fotod",
  "label_text_detailsTP_amount": "Prügi kogus",
  "label_text_detailsTP_type": "Prügi tüüp",
  "label_text_editTP_ask": "Kas prügi leiukoha info on täpne ja ajakohastatud?",
  "label_text_editTP_letsconfirm": "Jah, kinnitan",
  "label_alert_editTP_confirm": "Prügi leiukoht edukalt kinnitatud",
  "label_text_editTP_letsedit": "Ei, muuta infot",
  "label_header_editTP": "Redigeeri prügi leiukohta",
  "label_button_editTP_save": "Salvesta muudatused",
  "label_alert_editTP_edit": "Prügi leiukoht edukalt ajakohastatud",
  "label_alert_editTP_delete": "Prügi punkt edukalt kustutatud",
  "label_error_editTP_out_of_rng_subtitle": "Vahemikust väljas",
  "label_error_editTP_out_of_rng_text": "Punkti saate muuta ainult siis, kui olete 100 meetri raadiuses.",
  "label_error_saveTP_subtitle": "Salvesta prügi punkt",
  "label_error_saveTP_pic_and_type": "Palun lisa pilt prügi punktist ning määra prügi tüüp.",
  "label_error_saveTP_picture": "Meile on kasulikum kui teed enne salvestamist prügi punktist vähemalt ühe pildi.",
  "label_error_saveTP_trash_type": "Meile on kasulikum kui määrad enne salvestamist prügi punkti tüübi.",
  "label_error_change_loc_subtitle": "Väljaspool lubatud piire",
  "label_error_change_loc_text": "Palun asetage punkt oma asukohast 100 meetri raadiusesse.",
  "label_error_generic_error_subtitle": "Väljaspool lubatud piire",
  "label_error_generic_error_text": "Serveris esines viga.",
  "label_error_network_subtitle": "Võrguühendus puudub",
  "label_error_network_text": "Mobiilne andmeside on välja lülitatud. Rakenduse kasutamiseks lülitage andmeside sisse või ühendage telefon Wi-Fi võrku.",
  "label_error_location_subtitle": "Lubage asukoha määramine",
  "label_error_location_text": "Asukohateenused on välja lülitatud. Rakenduse kasutamiseks lülitage seadetest GPS teenused sisse.",
  "label_error_loc_permission_text": "Asukohateenused ei ole lubatud. Rakenduse kasutamiseks võimaldage asukohateenused.",
  "label_trash_details_header": "Prügipunkti üksikasjad",
  "label_privacy_policy_header": "Privaatsuspoliitika",
  "label_about_header": "Meist",
  "label_edit_trashpoint_button": "Redigeeri prügi punkti",
  "label_100m_limit_modal": "Punkti saate muuta ainult siis, kui olete 100 meetri raadiuses.",
  "label_retry_button": "Proovi uuesti",
  "label_country_picker_placeholder": "Valige riik",
  "label_camera_permission_warning_ios": "Teil tuleb kaamera juurdepääsuõigusi muuta. Selleks avage Sätted > Privaatsus > Kaamera",
  "label_camera_permission_warning_android": "Teil tuleb kaamera juurdepääsuõigusi muuta. Selleks avage Sätted > Rakendused",
  "label_camera_error_title": "Juurdepääs kaamerale keelatud",
  "label_error_modal_default_title": "Oh ei!",
  "label_error_modal_default_subtitle": "Serveri viga!",
  "label_location_permission_warning_ios": "Teil tuleb asukohateenuse õigusi muuta. Selleks avage Sätted > Privaatsus > Asukohateenused.",
  "label_location_permission_warning_android": "Teil tuleb asukohateenuse õigusi muuta. Selleks avage Sätted > Rakendused.",
  "label_location_off_warning": "Asukohateenused on välja lülitatud. Rakenduse kasutamiseks lülitage seadetest GPS teenused sisse.",
  "label_location_modal_title": "Lubage asukoha määramine",
  "label_network_off_warning_title": "Võrguühendus puudub",
  "label_network_off_warning": "Mobiilne andmeside on välja lülitatud. Rakenduse kasutamiseks lülitage andmeside sisse või ühendage telefon Wi-Fi võrku.",
  "label_loading_image_text": "Peaaegu valmis...",
  "label_loading_image_subtext": "Palun oodake kuni me salvestame teie tegevusi.",
  "label_create_marker_missing_photos": "Märgistusfotosid ei olnud võimalik üles laadida. Palun proovi need uuesti lisada.",
  "label_edit_marker_missing_photos": "Märgistusfotosid ei olnud võimalik üles laadida. Palun proovi need uuesti lisada.",
  "label_confirm_marker_missing_photos": "Märgistusfotosid ei olnud võimalik üles laadida. Palun proovi need uuesti lisada.",
  "label_button_delete": "Kustuta",
  "label_delete_photo_title": "Kustuta foto",
  "label_delete_photo_subtitle": "Kas oled kindel, et soovid pildi kustutada? Seda tegevust ei saa tagasi võtta.",
  "label_text_about_1": "See rakendus on Let's Do It! World'i algatus",
  "label_text_about_2": "Kõik ülemaailmsete kasutajate poolt kogutud andmed on nähtavad globaalsel prügikaardil, et üle maailma koristuspäevi, maailmakoristuspäeval, 15 september 2018, ellu kutsuda",
  "label_text_about_3": "See rakendus on ühine koostöö",
  "label_text_about_4": "Eesti toode, riigi ja valitsuse poolt toetatud",
  "label_text_about_5": "Rahastajad: Keskkonnaministeerium, Välisministeerium, Eesti Vabariik 100",
  "label_button_editTP_delete": "Kustuta prügi punkt",
  "label_locked_account_warning": "Teie konto on lukustatud. Lisateabe saamiseks pöörduge administraatori poole."
}