{
  "label_text_app_subtitle": "Linisin natin ang mundo ng sama-sama!",
  "label_button_facebook": "Magpatuloy gamit ang Facebook",
  "label_button_google": "Magpatuloy gamita ang Google",
  "label_button_try_app": "Subukan ang mga app ng walang account",
  "label_button_acknowledge": "Ok, nakuha ko!",
  "label_button_cancel": "Kanselahin",
  "label_button_continue": "Magpatuloy",
  "label_trash_status_threat": "banta",
  "label_trash_status_regular": "regular",
  "label_trash_status_cleaned": "nalinis na",
  "label_trash_status_outdated": "lipas na sa panahon",
  "label_trash_status_user": "user",
  "label_trash_status_change_location": "baguhin ang Lokasyon",
  "label_trash_status_state_threat": "Ang puntong ito ay isang banta!",
  "label_trash_status_state_regular": "Ito ay isang regular na trashpoint.",
  "label_trash_status_state_cleaned": "Ang lugar na ito ay nalinis na!",
  "label_trash_status_state_outdated": "Ang lugar na ito ay lipas na sa panahon!",
  "label_TP_created_date": "Nalikha na",
  "label_TP_updated_date": "Na-update na",
  "label_TP_by": " mula kay ",
  "label_trash_amount_handful": "isang dakot",
  "label_trash_amount_bagful": "isang supot",
  "label_trash_amount_cartloadl": "isang kariton",
  "label_trash_amount_truckload": "isang trak",
  "label_trash_type_plastic": "Plastik",
  "label_trash_type_metal": "Metal",
  "label_trash_type_glass": "Salamin",
  "label_trash_type_electro": "Electronics",
  "label_trash_type_paper": "Papel/Kahoy",
  "label_trash_type_tyres": "Mga gulong",
  "label_trash_type_dom_waste": "Basurang mula sa tahanan",
  "label_trash_type_furniture": "Kasangkapan sa bahay",
  "label_trash_type_org_waste": "Basurang organiko",
  "label_header_tc": "Mga tuntunin at kondisyon",
  "label_button_tc_agree": "Sumasang-ayon ako sa mga tuntunin & kundisyon",
  "label_header_map": "Mapa",
  "label_text_popover_subtitle": "Sumali sa iba pang mga tao na nagmamapa ng basura!",
  "label_text_popover_text": "Magsimulang lumikha ng mga trashpoints upang gawing mas malinis at malusog ang iyong komunidad.",
  "label_header_activity": "Aking mga aktibidad",
  "label_text_activity_empty_subtitle": "Walang makikita dito!",
  "label_text_activity_empty_text": "Hindi ka pa nagdaradag ng anumang trashpoints. Kapag nagdagdag ka ng trashpoint, iyon ay mai-lilista dito.",
  "label_text_activity_empty_hint": "Magdagdag ng isang trashpoint!",
  "label_header_notific": "Mga notification",
  "label_text_notific_empty_subtitle": "Walang makikita dito!",
  "label_text_notific_empty_text": "Hindi pa kami nakakita ng anumang notification, ngunit ipapaalam sa iyo kapag mayroon na!",
  "label_header_profile": "Aking profile",
  "label_header_settings": "Mga setting ng account",
  "label_button_country_empty": "Bansa",
  "label_text_country": "Bansa",
  "label_header_select_country": "Pumili ng bansa",
  "label_text_select_country_hint": "Maghanap",
  "label_button_tc": "Mga tuntunin at kondisyon",
  "label_button_logout": "Mag-logout",
  "label_text_congrats_image": "Nakunang basura",
  "label_text_congrats_subtitle": "Mahusay!",
  "label_text_congrats_text": "Ngayon i-save ang lugar sa pamamagitan ng nagpapatunay na mga datos.",
  "label_header_createTP": "Lumikha ng isang trashpoint",
  "label_button_createTP_editloc": "Mag-edit ng lokasyon",
  "label_header_edit_loc": "Mag-edit ng lokasyon",
  "label_button_edit_loc_set": "Magtakda ng lokasyon ng trashpoint",
  "label_text_createTP_status_subtitle": "Katayuan ng lugar",
  "label_text_createTP_status_text": "Kung ang isang mabilis na pagkilos ay kinakailangang (nakakalason, heavy metal), mangyaring itakda bilang banta.",
  "label_text_createTP_add_photos": "Magdagdag ng mga larawan ng basura",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Mga detalye ng Trashpoint",
  "label_privacy_policy_header": "Patakaran sa privacy",
  "label_about_header": "Tungkol sa",
  "label_edit_trashpoint_button": "I-edit ang trashpoint",
  "label_100m_limit_modal": "Ang isang lugar ay maaari lamang i-edit kung ikaw ay nasa loob ng 100 metro nito.",
  "label_retry_button": "Subukang muli",
  "label_country_picker_placeholder": "Piliin ang iyong bansa",
  "label_camera_permission_warning_ios": "Kailangan mong baguhin ang mga permiso sa akses ng kamera. Upang gawin ito, pumunta sa Settings > Privacy > Camera",
  "label_camera_permission_warning_android": "Kailangan mong baguhin ang mga permiso sa akses ng kamera. Upang gawin ito, pumunta sa Settings > Apps",
  "label_camera_error_title": "Hindi pinayagan ang akses sa camera",
  "label_error_modal_default_title": "Ah hindi!",
  "label_error_modal_default_subtitle": "Ang fail whale ay nakapansin ng server error!",
  "label_location_permission_warning_ios": "Kailangan mong baguhin ang mga pahintulot sa lokasyon. Upang gawin ito, pumunta sa Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "Kailangan mong baguhin ang mga pahintulot sa lokasyon. Upang gawin ito, pumunta sa Settings > Apps.",
  "label_location_off_warning": "Ang Location Services ay nakapatay. Mangyaring paganahin ang GPS mo sa iyong mga setting upang gamitin ang application na ito.",
  "label_location_modal_title": "Paganahin ang lokasyon",
  "label_network_off_warning_title": "Walang koneksyon sa network",
  "label_network_off_warning": "Hindi pinagagana ang mobile data. Paganahin ang mobile data o ikonekta ang iyong telepono sa Wi-Fi para gamitin ang application na ito.",
  "label_loading_image_text": "Halos tapos na...",
  "label_loading_image_subtext": "Mangyaring maghintay habang isina-save natin ang iyong mga aksyon.",
  "label_create_marker_missing_photos": "Hindi nai-upload ang mga marker na larawan. Pakisubukang idagdag muli ang mga ito.",
  "label_edit_marker_missing_photos": "Hindi mai-upload ang mga marker na larawan. Pakisubukang idagdag muli ang mga ito.",
  "label_confirm_marker_missing_photos": "Hindi mai-upload ang mga marker na larawan. Pakisubukang idagdag muli ang mga ito.",
  "label_button_delete": "Burahin",
  "label_delete_photo_title": "Burahin ang larawan",
  "label_delete_photo_subtitle": "Tiyak ka bang gusto mong burahin ang larawan? Hindi mo na maibabalik ito.",
  "label_text_about_1": "Ang app na ito ay isang inisyatibo ng Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "Ang app ay isang magkasanib na pakikipagtulungan sa",
  "label_text_about_4": "Estonian product, itinataguyod ng bansa at pamahalaan",
  "label_text_about_5": "Mga Natatag: Ministro ng Kapaligiran ng Estonia, Ministro ng Panglabas na Pikikipagugnayan ng Republika ng Estonia, Programa ng Republika ng Estonia 100",
  "label_button_editTP_delete": "Burahin ang trashpoint",
  "label_locked_account_warning": "Naka-lock ang account mo. Para sa mga detalye makipag-ugnayan sa administrator."
}