{
  "label_text_app_subtitle": "Nettoyons la planète tous ensemble ! ",
  "label_button_facebook": "Continuer avec Facebook",
  "label_button_google": "Continuer avec Google",
  "label_button_try_app": "Essayez l'application sans compte",
  "label_button_acknowledge": "Ok, pigé ! ",
  "label_button_cancel": "Annuler",
  "label_button_continue": "Continuer",
  "label_trash_status_threat": "danger",
  "label_trash_status_regular": "normal",
  "label_trash_status_cleaned": "nettoyé",
  "label_trash_status_outdated": "obsolète",
  "label_trash_status_user": "utilisateur",
  "label_trash_status_change_location": "Changer de location",
  "label_trash_status_state_threat": "Ce point est un danger ! ",
  "label_trash_status_state_regular": "This is a regular trashpoint.",
  "label_trash_status_state_cleaned": "This point is cleaned!",
  "label_trash_status_state_outdated": "This point is outdated!",
  "label_TP_created_date": "Créé",
  "label_TP_updated_date": "Actualisé",
  "label_TP_by": "par",
  "label_trash_amount_handful": "poignée",
  "label_trash_amount_bagful": "sac",
  "label_trash_amount_cartloadl": "charette",
  "label_trash_amount_truckload": "Chargement de camion",
  "label_trash_type_plastic": "Plastique",
  "label_trash_type_metal": "Métal",
  "label_trash_type_glass": "Verre",
  "label_trash_type_electro": "Electronique",
  "label_trash_type_paper": "Papier/Bois",
  "label_trash_type_tyres": "Pneus",
  "label_trash_type_dom_waste": "Ordures ménagères",
  "label_trash_type_furniture": "Meubles",
  "label_trash_type_org_waste": "Déchets organiques",
  "label_header_tc": "Termes et conditions",
  "label_button_tc_agree": "J'accepte les termes et conditions",
  "label_header_map": "Carte",
  "label_text_popover_subtitle": "Rejoignez d'autres personnes qui cartographient les déchets ! ",
  "label_text_popover_text": "Start creating trashpoints to make your community cleaner and healthier.",
  "label_header_activity": "Mon activité",
  "label_text_activity_empty_subtitle": "Rien à voir ici ! ",
  "label_text_activity_empty_text": "You haven't added any trashpoints yet. When you do, they will be listed here.",
  "label_text_activity_empty_hint": "Add a trashpoint!",
  "label_header_notific": "Notifications",
  "label_text_notific_empty_subtitle": "Rien à voir ici ! ",
  "label_text_notific_empty_text": "Nous n'avons pas reçu de notifications pour le moment, mais vous serez prévenu dès réception.",
  "label_header_profile": "Mon profil",
  "label_header_settings": "Paramètres du compte",
  "label_button_country_empty": "Pays",
  "label_text_country": "Pays",
  "label_header_select_country": "Sélectionnez un pays",
  "label_text_select_country_hint": "Search",
  "label_button_tc": "Terms and Conditions",
  "label_button_logout": "Log out",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Great job!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Edit location",
  "label_header_edit_loc": "Edit location",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Les services de localisation ne sont pas autorisés. S'il vous plaît, activez les pour utiliser l'application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Politique de confidentialité",
  "label_about_header": "A propos",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Réessayer ",
  "label_country_picker_placeholder": "Choisissez votre pays",
  "label_camera_permission_warning_ios": "Vous devez modifier les permissions d'accès à la caméra. Pour ce faire, allez dans paramètres > confidentialité > caméra",
  "label_camera_permission_warning_android": "Vous devez modifier les permissions d'accès à la caméra. Pour ce faire, allez dans paramètres > applications",
  "label_camera_error_title": "Accès à la caméra refusé",
  "label_error_modal_default_title": "Oh nan ! ",
  "label_error_modal_default_subtitle": "La baleine échouée à détecté une erreur de serveur ! ",
  "label_location_permission_warning_ios": "Vous devez changer les permissions de localisations. Pour ce faire, allez dans Paramètres > Confidentialité > Service de locations",
  "label_location_permission_warning_android": "Vous devez changer les permissions de localisations. Pour ce faire, allez dans Paramètres > Applications.",
  "label_location_off_warning": "Les services de locations sont désactivés. Veuillez activer votre GPS dans vos paramètres pour utiliser l'application. ",
  "label_location_modal_title": "Activer la localisation",
  "label_network_off_warning_title": "Aucune connexion réseau",
  "label_network_off_warning": "Les données mobiles sont désactivées. Activez les données mobiles ou connectez votre téléphone à un Wi-Fi pour utiliser l'application.",
  "label_loading_image_text": "On y est presque...",
  "label_loading_image_subtext": "Veuillez patientez pendant que nous enregistrons vos actions. ",
  "label_create_marker_missing_photos": "Les photos de repères n'ont pas pu être téléchargées. S'il vous plaît, essayez à nouveau. ",
  "label_edit_marker_missing_photos": "Les photos de repères n'ont pas pu être téléchargées. S'il vous plaît, essayez à nouveau. ",
  "label_confirm_marker_missing_photos": "Les photos de repères n'ont pas pu être téléchargées. S'il vous plaît, essayez à nouveau. ",
  "label_button_delete": "Supprimer",
  "label_delete_photo_title": "Supprimer la photo",
  "label_delete_photo_subtitle": "Êtes-vous sûr de vouloir supprimer la photo ? Vous ne pourrez plus annuler. ",
  "label_text_about_1": "Cette application est une initiative de Let's Do It World",
  "label_text_about_2": "Toutes les données recueillies par les utilisateurs dans le monde entier vont être visualisables sur notre carte mondiale de déchets. Cela permettra d'initier des nettoyages dans le monde entier pendant le World Cleanup Day, le 15 septembre 2018.",
  "label_text_about_3": "Cette application est une collaboration avec",
  "label_text_about_4": "Produit Estonien, financé par le pays et le gouvernement",
  "label_text_about_5": "Bailleurs de fonds : le Ministère de l'environnement Estonien, le Ministère des affaires étrangères Estonien et le programme Estonien \"100 program\"",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Votre compte est verrouillé. Pour plus d'informations, veuillez contacter un administrateur. "
}