{
  "label_text_app_subtitle": "Nettoyons la planète tous ensemble ! ",
  "label_button_facebook": "Continuer avec Facebook",
  "label_button_google": "Continuer avec Google",
  "label_button_try_app": "Essayez l'application sans inscription",
  "label_button_acknowledge": "Ok, c'est noté !",
  "label_button_cancel": "Annuler",
  "label_button_continue": "Continuer",
  "label_trash_status_threat": "danger",
  "label_trash_status_regular": "standard",
  "label_trash_status_cleaned": "nettoyé",
  "label_trash_status_outdated": "obsolète",
  "label_trash_status_user": "utilisateur",
  "label_trash_status_change_location": "Changer de location",
  "label_trash_status_state_threat": "Ce point est un danger ! ",
  "label_trash_status_state_regular": "C'est une décharge de déchets standards.",
  "label_trash_status_state_cleaned": "Cette décharge a été nettoyée !",
  "label_trash_status_state_outdated": "Cette décharge n'existe plus !",
  "label_TP_created_date": "Créé",
  "label_TP_updated_date": "Actualisé",
  "label_TP_by": "par",
  "label_trash_amount_handful": "poignée",
  "label_trash_amount_bagful": "contenu d'un sac",
  "label_trash_amount_cartloadl": "contenu d'un chariot",
  "label_trash_amount_truckload": "chargement de camion",
  "label_trash_type_plastic": "Plastique",
  "label_trash_type_metal": "Métal",
  "label_trash_type_glass": "Verre",
  "label_trash_type_electro": "Électronique",
  "label_trash_type_paper": "Papier/Bois",
  "label_trash_type_tyres": "Pneus",
  "label_trash_type_dom_waste": "Ordures ménagères",
  "label_trash_type_furniture": "Meubles",
  "label_trash_type_org_waste": "Déchets organiques",
  "label_header_tc": "Termes et Conditions",
  "label_button_tc_agree": "J'accepte les Termes et Conditions",
  "label_header_map": "Carte",
  "label_text_popover_subtitle": "Rejoignez d'autres personnes qui cartographient les déchets !",
  "label_text_popover_text": "Commencez à cartographier les spots de déchets pour rendre votre quartier plus propre et plus agréable.",
  "label_header_activity": "Mon activité",
  "label_text_activity_empty_subtitle": "Rien à voir ici ! ",
  "label_text_activity_empty_text": "Vous n'avez pas encore cartographié de spots de déchets. Vos spots apparaîtront ici.",
  "label_text_activity_empty_hint": "Ajouter un spot de déchets !",
  "label_header_notific": "Notifications",
  "label_text_notific_empty_subtitle": "Rien à voir ici ! ",
  "label_text_notific_empty_text": "Nous n'avons pas reçu de notifications pour le moment, mais vous serez prévenu dès réception.",
  "label_header_profile": "Mon profil",
  "label_header_settings": "Paramètres du compte",
  "label_button_country_empty": "Pays",
  "label_text_country": "Pays",
  "label_header_select_country": "Sélectionnez un pays",
  "label_text_select_country_hint": "Rechercher",
  "label_button_tc": "Termes et Conditions",
  "label_button_logout": "Se déconnecter",
  "label_text_congrats_image": "Décharge saisie",
  "label_text_congrats_subtitle": "Bien joué !",
  "label_text_congrats_text": "Maintenant, sauvegardez la localisation en vérifiant les données.",
  "label_header_createTP": "Ajouter une décharge",
  "label_button_createTP_editloc": "Modifier la localisation",
  "label_header_edit_loc": "Modifier la localisation",
  "label_button_edit_loc_set": "Enregistrer la localisation de la décharge",
  "label_text_createTP_status_subtitle": "État de la décharge",
  "label_text_createTP_status_text": "Si une intervention urgente est nécessaire (toxiques, métaux lourds...), veuillez choisir \"dangereux\".",
  "label_text_createTP_add_photos": "Ajoutez des photos des déchets",
  "label_text_createTP_select_amount": "Indiquer la quantité de déchets",
  "label_text_createTP_select_type": "Indiquer le type de déchets",
  "label_text_createTP_add_hashtags": "Ajouter des hashtags supplémentaires",
  "label_text_createTP_add_hashtags_hint": "ex : #NomDeMarque , #canettes",
  "label_button_createTP_confirm_create": "Localiser la décharge",
  "label_alert_createTP_success": "Décharge localisée avec succès",
  "label_text_detailsTP_photos": "Photos des déchets",
  "label_text_detailsTP_amount": "Quantité de déchets",
  "label_text_detailsTP_type": "Type de déchets",
  "label_text_editTP_ask": "Les informations sur cette décharge sont-elles toujours à jour ?",
  "label_text_editTP_letsconfirm": "Oui, je confirme",
  "label_alert_editTP_confirm": "Localisation de la décharge confirmée",
  "label_text_editTP_letsedit": "Non, modifier la localisation de la décharge",
  "label_header_editTP": "Modifier la localisation d'une décharge",
  "label_button_editTP_save": "Enregistrer les modifications",
  "label_alert_editTP_edit": "Mise à jour de la localisation de la décharge effectuée",
  "label_alert_editTP_delete": "Spot supprimé",
  "label_error_editTP_out_of_rng_subtitle": "Hors de portée",
  "label_error_editTP_out_of_rng_text": "Une localisation ne peut être éditée que si vous vous trouvez à 100 mètres de celle-ci.",
  "label_error_saveTP_subtitle": "Sauvegarder la localisation de la décharge",
  "label_error_saveTP_pic_and_type": "Il est plus utile pour nous que vous preniez au moins une photo de la décharge et que vous indiquiez le type de déchet.",
  "label_error_saveTP_picture": "Il est plus utile pour nous que vous preniez au moins une photo de décharge avant de sauvegarder.",
  "label_error_saveTP_trash_type": "Il est plus utile pour nous que vous indiquiez le type de déchet avant de sauvegarder.",
  "label_error_change_loc_subtitle": "Intitulé trop long",
  "label_error_change_loc_text": "S'il vous plait, ne repérez que les décharges situées à moins de 100 mètres de votre position.",
  "label_error_generic_error_subtitle": "Intitulé trop long",
  "label_error_generic_error_text": "Une erreur est survenue sur le serveur.",
  "label_error_network_subtitle": "Pas de connexion réseau",
  "label_error_network_text": "Les données mobiles sont désactivées. Activez les données mobiles ou connectez votre téléphone à un réseau Wi-Fi pour utiliser l'application.",
  "label_error_location_subtitle": "Activer la géolocalisation",
  "label_error_location_text": "Les Services de Géolocalisation sont désactivés. Activez le GPS dans les Paramètres pour pouvoir utiliser l'application.",
  "label_error_loc_permission_text": "Votre appareil n'autorise pas les Services de Géolocalisation. S'il vous plaît, autorisez les Services de Géolocalisation pour pouvoir utiliser l'application.",
  "label_trash_details_header": "Détails du spot",
  "label_privacy_policy_header": "Politique de Confidentialité",
  "label_about_header": "A propos",
  "label_edit_trashpoint_button": "Éditer une décharge",
  "label_100m_limit_modal": "Une décharge ne peut être éditée que si elle se trouve à moins de 100 mètres de votre position.",
  "label_retry_button": "Réessayer",
  "label_country_picker_placeholder": "Choisissez votre pays",
  "label_camera_permission_warning_ios": "Vous devez modifier les autorisations d'accès à l'appareil photo. Pour ce faire, allez dans Paramètres > Confidentialité > Appareil photo",
  "label_camera_permission_warning_android": "Vous devez modifier les autorisations d'accès à l'appareil photo. Pour ce faire, allez dans Paramètres > Applications",
  "label_camera_error_title": "Accès à l'appareil photo refusé",
  "label_error_modal_default_title": "Oh zut !",
  "label_error_modal_default_subtitle": "La baleine échouée à détecté une erreur de serveur ! ",
  "label_location_permission_warning_ios": "Vous devez changer les autorisations de géolocalisation. Pour ce faire, allez dans Paramètres > Confidentialité > Services de localisation.",
  "label_location_permission_warning_android": "Vous devez changer les autorisations de géolocalisation. Pour ce faire, allez dans Paramètres > Applications.",
  "label_location_off_warning": "Les Services de Géolocalisation sont désactivés. Veuillez activer votre GPS dans vos Paramètres pour pouvoir utiliser l'application.",
  "label_location_modal_title": "Activer la géolocalisation",
  "label_network_off_warning_title": "Aucune connexion réseau",
  "label_network_off_warning": "Les données mobiles sont désactivées. Activez les données mobiles ou connectez votre téléphone à un réseau Wi-Fi pour pouvoir utiliser l'application.",
  "label_loading_image_text": "On y est presque...",
  "label_loading_image_subtext": "Veuillez patienter pendant que nous enregistrons vos actions.",
  "label_create_marker_missing_photos": "Les photos de repérage n'ont pas pu être téléchargées. Veuillez essayer de les envoyer à nouveau.",
  "label_edit_marker_missing_photos": "Les photos de repérage n'ont pas pu être téléchargées. Veuillez essayer de les envoyer à nouveau.",
  "label_confirm_marker_missing_photos": "Les photos de repérage n'ont pas pu être téléchargées. Veuillez essayer de les envoyer à nouveau.",
  "label_button_delete": "Supprimer",
  "label_delete_photo_title": "Supprimer la photo",
  "label_delete_photo_subtitle": "Êtes-vous sûr de vouloir supprimer la photo ? Cette action ne pourra pas être annulée.",
  "label_text_about_1": "Cette application est une initiative de Let's Do It World",
  "label_text_about_2": "Toutes les données recueillies par les utilisateurs dans le monde entier vont être visualisables sur notre carte mondiale de déchets. Cela permettra d'initier des nettoyages dans le monde entier pendant le World Cleanup Day, le 15 septembre 2018.",
  "label_text_about_3": "Cette application a été réalisée en collaboration avec",
  "label_text_about_4": "Produit Estonien, financé par le pays et le gouvernement",
  "label_text_about_5": "Donateurs : Ministère de l'Environnement Estonien, Ministère des Affaires Étrangères Estonien et le programme Estonien \"Estonia100\"",
  "label_button_editTP_delete": "Supprimer ce spot",
  "label_locked_account_warning": "Votre compte est verrouillé. Pour plus d'informations, veuillez contacter un administrateur."
}