{
  "label_text_app_subtitle": "Mari bersihkan dunia ini bersama!",
  "label_button_facebook": "Lanjutkan dengan Facebook",
  "label_button_google": "Lanjutkan dengan Google",
  "label_button_try_app": "Mencoba aplikasi tanpa akun",
  "label_button_acknowledge": "Ok, mengerti!",
  "label_button_cancel": "Batal",
  "label_button_continue": "Lanjutkan",
  "label_trash_status_threat": "ancaman",
  "label_trash_status_regular": "reguler",
  "label_trash_status_cleaned": "di bersihkan",
  "label_trash_status_outdated": "ketinggalan jaman",
  "label_trash_status_user": "pengguna",
  "label_trash_status_change_location": "ganti lokasi",
  "label_trash_status_state_threat": "Poin ini adalah ancaman!",
  "label_trash_status_state_regular": "Ini adalah tempat sampah biasa.",
  "label_trash_status_state_cleaned": "Titik ini dibersihkan!",
  "label_trash_status_state_outdated": "Titik ini sudah ketinggalan jaman!",
  "label_TP_created_date": "Membuat",
  "label_TP_updated_date": "Diperbarui",
  "label_TP_by": " oleh ",
  "label_trash_amount_handful": "segenggam",
  "label_trash_amount_bagful": "tas penuh",
  "label_trash_amount_cartloadl": "segerobak penuh",
  "label_trash_amount_truckload": "sepenuh truk",
  "label_trash_type_plastic": "Plastik",
  "label_trash_type_metal": "Logam",
  "label_trash_type_glass": "Kaca",
  "label_trash_type_electro": "Elektronik",
  "label_trash_type_paper": "Kertas / Kayu",
  "label_trash_type_tyres": "Ban",
  "label_trash_type_dom_waste": "Limbah rumah tangga",
  "label_trash_type_furniture": "Mebel",
  "label_trash_type_org_waste": "Limbah organik",
  "label_header_tc": "Syarat dan ketentuan",
  "label_button_tc_agree": "Saya setuju dengan Syarat & Ketentuan",
  "label_header_map": "Peta",
  "label_text_popover_subtitle": "Bergabunglah dengan orang lain yang pemetaan sampah!",
  "label_text_popover_text": "Mulai buat tempat sampah untuk membuat komunitas Anda lebih bersih dan lebih sehat.",
  "label_header_activity": "Aktivitas saya",
  "label_text_activity_empty_subtitle": "Tidak ada yang bisa dilihat di sini!",
  "label_text_activity_empty_text": "Anda belum menambahkan tempat sampah. Bila Anda melakukannya, mereka akan tercantum di sini.",
  "label_text_activity_empty_hint": "Tambahkan tempat sampah!",
  "label_header_notific": "Pemberitahuan",
  "label_text_notific_empty_subtitle": "Tidak ada yang bisa dilihat di sini!",
  "label_text_notific_empty_text": "Kami belum melihat ada pemberitahuan masuk, namun kami akan memberi tahu Anda saat kami melakukannya!",
  "label_header_profile": "Profil saya",
  "label_header_settings": "Pengaturan akun",
  "label_button_country_empty": "Negara",
  "label_text_country": "Negara",
  "label_header_select_country": "Pilih sebuah negara",
  "label_text_select_country_hint": "Pencarian",
  "label_button_tc": "Syarat dan ketentuan",
  "label_button_logout": "Keluar",
  "label_text_congrats_image": "Sampah ditangkap",
  "label_text_congrats_subtitle": "Kerja bagus!",
  "label_text_congrats_text": "Sekarang simpan intinya dengan melakukan verifikasi data.",
  "label_header_createTP": "Buat tempat sampah",
  "label_button_createTP_editloc": "Edit lokasi",
  "label_header_edit_loc": "Edit lokasi",
  "label_button_edit_loc_set": "Setel lokasi tempat sampah",
  "label_text_createTP_status_subtitle": "Status titik",
  "label_text_createTP_status_text": "Jika diperlukan tindakan cepat (racun, logam berat), tolong ditetapkan sebagai ancaman.",
  "label_text_createTP_add_photos": "Tambahkan foto sampah",
  "label_text_createTP_select_amount": "Pilih jumlah sampah",
  "label_text_createTP_select_type": "Pilih jenis sampah",
  "label_text_createTP_add_hashtags": "Tag tambahan",
  "label_text_createTP_add_hashtags_hint": "yaitu. #nama merek, #kaleng",
  "label_button_createTP_confirm_create": "Buat tempat sampah",
  "label_alert_createTP_success": "Sampah berhasil dibuat",
  "label_text_detailsTP_photos": "Foto sampah",
  "label_text_detailsTP_amount": "Jumlah sampah",
  "label_text_detailsTP_type": "Jenis sampah",
  "label_text_editTP_ask": "Apakah informasi tempat sampah ini masih benar dan mutakhir?",
  "label_text_editTP_letsconfirm": "Ya, saya konfirmasi",
  "label_alert_editTP_confirm": "Tempat sampah berhasil dikonfirmasi",
  "label_text_editTP_letsedit": "Tidak, mari kita edit",
  "label_header_editTP": "Edit tempat sampah",
  "label_button_editTP_save": "Simpan perubahan tempat sampah",
  "label_alert_editTP_edit": "Tempat sampah berhasil diperbarui",
  "label_alert_editTP_delete": "Tempat sampah berhasil dihapus",
  "label_error_editTP_out_of_rng_subtitle": "Diluar jangkauan",
  "label_error_editTP_out_of_rng_text": "Sebuah titik hanya dapat diedit jika Anda berada dalam jarak 100 meter darinya.",
  "label_error_saveTP_subtitle": "Simpan tempat sampah",
  "label_error_saveTP_pic_and_type": "Ini lebih berguna bagi kita jika Anda mengambil setidaknya satu gambar tempat sampah dan mengatur jenis sampahnya.",
  "label_error_saveTP_picture": "Ini lebih berguna bagi kita jika Anda mengambil setidaknya satu gambar tempat sampah sebelum menabung.",
  "label_error_saveTP_trash_type": "Ini lebih berguna bagi kita jika Anda mengatur tipe tempat sampah sebelum menabung.",
  "label_error_change_loc_subtitle": "Di luar batas",
  "label_error_change_loc_text": "Mohon tempatkan titik dalam radius 100 meter dari lokasi Anda.",
  "label_error_generic_error_subtitle": "Di luar batas",
  "label_error_generic_error_text": "Terjadi kesalahan pada server.",
  "label_error_network_subtitle": "Tidak ada koneksi jaringan",
  "label_error_network_text": "Data seluler dinonaktifkan. Aktifkan data seluler atau hubungkan ponsel Anda ke Wi-Fi untuk menggunakan aplikasi ini.",
  "label_error_location_subtitle": "Aktifkan lokasi",
  "label_error_location_text": "Layanan Lokasi dimatikan. Harap aktifkan GPS Anda di Pengaturan Anda untuk menggunakan aplikasi ini.",
  "label_error_loc_permission_text": "Layanan Lokasi tidak diizinkan. Izinkan mereka untuk menggunakan aplikasi ini.",
  "label_trash_details_header": "Rincian tempat sampah",
  "label_privacy_policy_header": "Kebijakan privasi",
  "label_about_header": "Tentang",
  "label_edit_trashpoint_button": "Edit tempat sampah",
  "label_100m_limit_modal": "Sebuah titik hanya bisa diedit jika Anda berada dalam jarak 100 meter darinya.",
  "label_retry_button": "Mencoba kembali",
  "label_country_picker_placeholder": "Pilih negaramu",
  "label_camera_permission_warning_ios": "Anda harus mengubah hak akses kamera. Untuk melakukannya, buka Setelan> Privasi> Kamera",
  "label_camera_permission_warning_android": "Anda harus mengubah hak akses kamera. Untuk melakukannya, buka Setelan> Aplikasi",
  "label_camera_error_title": "Akses Kamera Ditolak",
  "label_error_modal_default_title": "Oh tidak!",
  "label_error_modal_default_subtitle": "Paus gagal mendeteksi kesalahan server!",
  "label_location_permission_warning_ios": "Anda harus mengubah izin lokasi. Untuk melakukannya, buka Setelan> Privasi> Layanan lokasi.",
  "label_location_permission_warning_android": "Anda harus mengubah izin lokasi. Untuk melakukannya, buka Setelan> Aplikasi.",
  "label_location_off_warning": "Layanan Lokasi dimatikan. Harap aktifkan GPS Anda di Pengaturan Anda untuk menggunakan aplikasi ini.",
  "label_location_modal_title": "Aktifkan lokasi",
  "label_network_off_warning_title": "Tidak ada koneksi jaringan",
  "label_network_off_warning": "Data seluler dinonaktifkan. Aktifkan data seluler atau hubungkan ponsel Anda ke Wi-Fi untuk menggunakan aplikasi ini.",
  "label_loading_image_text": "Hampir sampai...",
  "label_loading_image_subtext": "Mohon tunggu sementara kami menyimpan tindakanmu.",
  "label_create_marker_missing_photos": "Foto penanda tidak dapat diunggah. Coba tambahkan lagi.",
  "label_edit_marker_missing_photos": "Foto penanda tidak dapat diunggah. Coba tambahkan lagi.",
  "label_confirm_marker_missing_photos": "Foto penanda tidak dapat diunggah. Coba tambahkan lagi.",
  "label_button_delete": "Menghapus",
  "label_delete_photo_title": "Menghapus foto",
  "label_delete_photo_subtitle": "Yakin ingin menghapus foto itu? Anda tidak bisa membatalkan ini.",
  "label_text_about_1": "Aplikasi ini merupakan inisiatif oleh Ayo Lakukan di Dunia",
  "label_text_about_2": "Semua data yang dikumpulkan oleh pengguna di seluruh dunia akan divisualisasikan di peta sampah global untuk memulai acara pembersihan seluruh dunia pada Hari Pembersihan Dunia, 15 September 2018",
  "label_text_about_3": "Aplikasi ini merupakan kerjasama dengan Pt",
  "label_text_about_4": "Produk Estonia, disponsori oleh negara dan pemerintah",
  "label_text_about_5": "Pendiri: Kementerian Lingkungan Hidup Estonia, Kementerian Luar Negeri Republik Estonia, program 100 Republik Estonia",
  "label_button_editTP_delete": "Hapus tempat sampah",
  "label_locked_account_warning": "Akun anda terkunci Untuk informasi lebih lanjut, hubungi administrator."
}