{
  "label_text_app_subtitle": "चलो मिलकर विश्व की साफ़ सफाई करें!",
  "label_button_facebook": "फेसबुक के साथ आगे बढे",
  "label_button_google": "गूगल के साथ आगे बढे",
  "label_button_try_app": "बिना खाते के एप्लिकेशन को आज़माएं|",
  "label_button_acknowledge": "ठीक है, समझ गया!",
  "label_button_cancel": "रद्द करें",
  "label_button_continue": "आगे बढे",
  "label_trash_status_threat": "ख़तरा",
  "label_trash_status_regular": "सामान्य",
  "label_trash_status_cleaned": "साफ की",
  "label_trash_status_outdated": "अप्रचलित",
  "label_trash_status_user": "उपयोगकर्ता",
  "label_trash_status_change_location": "स्थान बदले",
  "label_trash_status_state_threat": "यह स्थल एक खतरा है!",
  "label_trash_status_state_regular": "यह एक सामान्य कचरे का स्थल है।",
  "label_trash_status_state_cleaned": "यह स्थल साफ की गयी है!",
  "label_trash_status_state_outdated": "यह स्थल अप्रचलित है!",
  "label_TP_created_date": "बनाया गया",
  "label_TP_updated_date": "Updated",
  "label_TP_by": " के द्वारा ",
  "label_trash_amount_handful": "मुट्ठीभर",
  "label_trash_amount_bagful": "थैलीभर",
  "label_trash_amount_cartloadl": "गाड़ीभार",
  "label_trash_amount_truckload": "ट्रकभार",
  "label_trash_type_plastic": "प्लास्टिक",
  "label_trash_type_metal": "धातु",
  "label_trash_type_glass": "कांच",
  "label_trash_type_electro": "इलेक्ट्रॉनिक्स",
  "label_trash_type_paper": "कागज/लकड़ी",
  "label_trash_type_tyres": "टायर",
  "label_trash_type_dom_waste": "घरेलू उपव्ययता",
  "label_trash_type_furniture": "असबाब",
  "label_trash_type_org_waste": "जैविक उपव्ययता",
  "label_header_tc": "Terms and Conditions",
  "label_button_tc_agree": "मैं नियम एवं शर्तें के साथ सहमत हूँ",
  "label_header_map": "नक्शा",
  "label_text_popover_subtitle": "अन्य लोगों के साथ शामिल होये जो कचरे का मानचित्रण कर रहे हैं!",
  "label_text_popover_text": "Start creating trashpoints to make your community cleaner and healthier.",
  "label_header_activity": "मेरी कार्यकलाप",
  "label_text_activity_empty_subtitle": "देखने के लिए कुछ नहीं है यहां!",
  "label_text_activity_empty_text": "You haven't added any trashpoints yet. When you do, they will be listed here.",
  "label_text_activity_empty_hint": "एक कचरे का स्थल जोड़ें!",
  "label_header_notific": "सूचनाएं",
  "label_text_notific_empty_subtitle": "Nothing to see here!",
  "label_text_notific_empty_text": "We haven't seen any notifications come in yet, but we'll let you know when we do!",
  "label_header_profile": "मेरी पार्श्वचित्र",
  "label_header_settings": "खाते के सेटिंग्स",
  "label_button_country_empty": "देश",
  "label_text_country": "देश",
  "label_header_select_country": "एक देश का चयन करें",
  "label_text_select_country_hint": "खोज",
  "label_button_tc": "Terms and Conditions",
  "label_button_logout": "लोग आउट करें",
  "label_text_congrats_image": "कचरा कब्जा किया गया",
  "label_text_congrats_subtitle": "बहुत अच्छा काम!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "एक कचरे का स्थल का निर्माण करे",
  "label_button_createTP_editloc": "स्थान को संपादित करें",
  "label_header_edit_loc": "स्थान को संपादित करें",
  "label_button_edit_loc_set": "कचरे का स्थल का स्थान सेट करें",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "कचरा तस्वीरें जोड़ें",
  "label_text_createTP_select_amount": "कचरे के राशि का चयन करें",
  "label_text_createTP_select_type": "कचरे के प्रकार का चयन करें",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "अर्थात #ब्रांडनाम, #डिब्बे",
  "label_button_createTP_confirm_create": "कचरे का स्थल का निर्माण करे",
  "label_alert_createTP_success": "कचरे का स्थल का निर्माण सफल हुआ",
  "label_text_detailsTP_photos": "कचरा तस्वीरें",
  "label_text_detailsTP_amount": "कचरे की राशि",
  "label_text_detailsTP_type": "कचरे का प्रकार",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "हां, मैं पुष्टि करता हूं",
  "label_alert_editTP_confirm": "कचरे का स्थल का सफलतापूर्वक पुष्टि हुआ",
  "label_text_editTP_letsedit": "नहीं, चलो संपादित करते हैं",
  "label_header_editTP": "एक कचरे का स्थल को संपादित करें",
  "label_button_editTP_save": "कचरे का स्थल के बदलाव को सहेजें",
  "label_alert_editTP_edit": "कचरे का स्थल सफलतापूर्वक अद्यतन हुआ",
  "label_alert_editTP_delete": "कचरे का स्थल सफलतापूर्वक हटाया गया",
  "label_error_editTP_out_of_rng_subtitle": "श्रेणी से बाहर",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "कचरे का स्थल को सहेजें",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "सीमा के बाहर",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "सीमा के बाहर",
  "label_error_generic_error_text": "सर्वर पर एक भूल हो गयी|",
  "label_error_network_subtitle": "कोई भी नेटवर्क कनेक्शन नहीं",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "स्थान को सक्षम करें",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "कचरे का स्थल के विवरण",
  "label_privacy_policy_header": "गोपनीयता नीति",
  "label_about_header": "के बारे मैं",
  "label_edit_trashpoint_button": "कचरे का स्थल को संपादित करें",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "फिर से कोशिश करें",
  "label_country_picker_placeholder": "आपका देश चुने",
  "label_camera_permission_warning_ios": "आपको कैमरा पहुँच अनुमतियाँ को बदलना होगा। ऐसा करने के लिए, सेटिंग्स > गोपनीयता > कैमरा जाएँ",
  "label_camera_permission_warning_android": "आपको कैमरा पहुँच अनुमतियाँ को बदलना होगा। ऐसा करने के लिए, सेटिंग्स > ऐप्स जाएँ",
  "label_camera_error_title": "कैमरा तक पहुंच अस्वीकृत",
  "label_error_modal_default_title": "अरे नहीं!",
  "label_error_modal_default_subtitle": "चूक व्हले ने एक सर्वर एरर का पता लगाया!",
  "label_location_permission_warning_ios": "आपको स्थान अनुमतियों को बदलना होगा। ऐसा करने के लिए, सेटिंग्स > गोपनीयता > स्थान सेवाएं जाएँ",
  "label_location_permission_warning_android": "आपको स्थान अनुमतियों को बदलना होगा। ऐसा करने के लिए, सेटिंग्स > ऐप्स जाएँ",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "स्थान को सक्षम करें",
  "label_network_off_warning_title": "कोई भी नेटवर्क कनेक्शन नहीं",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "करीब-करीब वहाँ...",
  "label_loading_image_subtext": "Please wait while we save your actions.",
  "label_create_marker_missing_photos": "मार्कर तस्वीरेंअपलोड नहीं की जा सकीं| कृपया उन्हें फिर से जोड़ने का प्रयास करें|",
  "label_edit_marker_missing_photos": "मार्कर तस्वीरेंअपलोड नहीं की जा सकीं| कृपया उन्हें फिर से जोड़ने का प्रयास करें|",
  "label_confirm_marker_missing_photos": "मार्कर तस्वीरेंअपलोड नहीं की जा सकीं| कृपया उन्हें फिर से जोड़ने का प्रयास करें|",
  "label_button_delete": "हटाएं",
  "label_delete_photo_title": "तस्वीर हटाएं",
  "label_delete_photo_subtitle": "क्या आपको यकीन है आप इस तस्वीर को हटाना चाहते हैं? आप इसे पूर्ववत नहीं कर सकते।",
  "label_text_about_1": "यह एप्लिकेशन Let's Do It World द्वारा एक पहल है",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "एस्टोनियाई उत्पाद, देश और सरकार द्वारा प्रायोजित किया हुआ",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "कचरे का स्थल को हटाए",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}