{
  "label_text_app_subtitle": "Mari bersihkan dunia ini bersama!",
  "label_button_facebook": "Lanjutkan dengan Facebook",
  "label_button_google": "Lanjutkan dengan Google",
  "label_button_try_app": "Mencoba aplikasi tanpa akun",
  "label_button_acknowledge": "Ok, mengerti!",
  "label_button_cancel": "Batal",
  "label_button_continue": "Lanjutkan",
  "label_trash_status_threat": "ancaman",
  "label_trash_status_regular": "reguler",
  "label_trash_status_cleaned": "di bersihkan",
  "label_trash_status_outdated": "ketinggalan jaman",
  "label_trash_status_user": "pengguna",
  "label_trash_status_change_location": "ganti lokasi",
  "label_trash_status_state_threat": "Poin ini adalah ancaman!",
  "label_trash_status_state_regular": "Ini adalah tempat sampah biasa.",
  "label_trash_status_state_cleaned": "Titik ini dibersihkan!",
  "label_trash_status_state_outdated": "Titik ini sudah ketinggalan jaman!",
  "label_TP_created_date": "Membuat",
  "label_TP_updated_date": "Diperbarui",
  "label_TP_by": " oleh ",
  "label_trash_amount_handful": "segenggam",
  "label_trash_amount_bagful": "tas penuh",
  "label_trash_amount_cartloadl": "segerobak penuh",
  "label_trash_amount_truckload": "sepenuh truk",
  "label_trash_type_plastic": "Plastik",
  "label_trash_type_metal": "Logam",
  "label_trash_type_glass": "Kaca",
  "label_trash_type_electro": "Elektronik",
  "label_trash_type_paper": "Kertas / Kayu",
  "label_trash_type_tyres": "Ban",
  "label_trash_type_dom_waste": "Limbah rumah tangga",
  "label_trash_type_furniture": "Mebel",
  "label_trash_type_org_waste": "Limbah organik",
  "label_header_tc": "Syarat dan ketentuan",
  "label_button_tc_agree": "Saya setuju dengan Syarat & Ketentuan",
  "label_header_map": "Peta",
  "label_text_popover_subtitle": "Bergabunglah dengan orang lain yang pemetaan sampah!",
  "label_text_popover_text": "Mulai buat tempat sampah untuk membuat komunitas Anda lebih bersih dan lebih sehat.",
  "label_header_activity": "Aktivitas saya",
  "label_text_activity_empty_subtitle": "Tidak ada yang bisa dilihat di sini!",
  "label_text_activity_empty_text": "Anda belum menambahkan tempat sampah. Bila Anda melakukannya, mereka akan tercantum di sini.",
  "label_text_activity_empty_hint": "Tambahkan tempat sampah!",
  "label_header_notific": "Pemberitahuan",
  "label_text_notific_empty_subtitle": "Tidak ada yang bisa dilihat di sini!",
  "label_text_notific_empty_text": "Kami belum melihat ada pemberitahuan masuk, namun kami akan memberi tahu Anda saat kami melakukannya!",
  "label_header_profile": "Profil saya",
  "label_header_settings": "Pengaturan akun",
  "label_button_country_empty": "Negara",
  "label_text_country": "Negara",
  "label_header_select_country": "Pilih sebuah negara",
  "label_text_select_country_hint": "Search",
  "label_button_tc": "Terms and Conditions",
  "label_button_logout": "Log out",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Great job!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Edit location",
  "label_header_edit_loc": "Edit location",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Pilih sebuah negara",
  "label_country_picker_placeholder": "Pilih negaramu",
  "label_camera_permission_warning_ios": "Anda harus mengubah hak akses kamera. Untuk melakukannya, buka Setelan> Privasi> Kamera",
  "label_camera_permission_warning_android": "Anda harus mengubah hak akses kamera. Untuk melakukannya, buka Setelan> Aplikasi",
  "label_camera_error_title": "Akses Kamera Ditolak",
  "label_error_modal_default_title": "Oh tidak!",
  "label_error_modal_default_subtitle": "Paus gagal mendeteksi kesalahan server!",
  "label_location_permission_warning_ios": "Anda harus mengubah izin lokasi. Untuk melakukannya, buka Setelan> Privasi> Layanan lokasi.",
  "label_location_permission_warning_android": "Anda harus mengubah izin lokasi. Untuk melakukannya, buka Setelan> Aplikasi.",
  "label_location_off_warning": "Layanan Lokasi dimatikan. Harap aktifkan GPS Anda di Pengaturan Anda untuk menggunakan aplikasi ini.",
  "label_location_modal_title": "Aktifkan lokasi",
  "label_network_off_warning_title": "Tidak ada koneksi jaringan",
  "label_network_off_warning": "Data seluler dinonaktifkan. Aktifkan data seluler atau hubungkan ponsel Anda ke Wi-Fi untuk menggunakan aplikasi ini.",
  "label_loading_image_text": "Hampir sampai...",
  "label_loading_image_subtext": "Mohon tunggu sementara kami menyimpan tindakanmu.",
  "label_create_marker_missing_photos": "Foto penanda tidak dapat diunggah. Coba tambahkan lagi.",
  "label_edit_marker_missing_photos": "Foto penanda tidak dapat diunggah. Coba tambahkan lagi.",
  "label_confirm_marker_missing_photos": "Foto penanda tidak dapat diunggah. Coba tambahkan lagi.",
  "label_button_delete": "Menghapus",
  "label_delete_photo_title": "Menghapus foto",
  "label_delete_photo_subtitle": "Yakin ingin menghapus foto itu? Anda tidak bisa membatalkan ini.",
  "label_text_about_1": "Aplikasi ini merupakan inisiatif oleh Ayo Lakukan di Dunia",
  "label_text_about_2": "Semua data yang dikumpulkan oleh pengguna di seluruh dunia akan divisualisasikan di peta sampah global untuk memulai acara pembersihan seluruh dunia pada Hari Pembersihan Dunia, 15 September 2018",
  "label_text_about_3": "Aplikasi ini merupakan kerjasama dengan Pt",
  "label_text_about_4": "Produk Estonia, disponsori oleh negara dan pemerintah",
  "label_text_about_5": "Pendiri: Kementerian Lingkungan Hidup Estonia, Kementerian Luar Negeri Republik Estonia, program 100 Republik Estonia",
  "label_button_editTP_delete": "Hapus tempat sampah",
  "label_locked_account_warning": "Akun anda terkunci Untuk informasi lebih lanjut, hubungi administrator."
}