{
  "label_text_app_subtitle": "Puliamo il mondo insieme!",
  "label_button_facebook": "Continua con Facebook",
  "label_button_google": "Continua con Google",
  "label_button_try_app": "Prova l'app senza account",
  "label_button_acknowledge": "Ok, ho capito!",
  "label_button_cancel": "Cancella",
  "label_button_continue": "Continua",
  "label_trash_status_threat": "minaccia",
  "label_trash_status_regular": "regolare",
  "label_trash_status_cleaned": "pulito",
  "label_trash_status_outdated": "obsoleto",
  "label_trash_status_user": "utente",
  "label_trash_status_change_location": "cambia posizione",
  "label_trash_status_state_threat": "Questo punto è una minaccia!",
  "label_trash_status_state_regular": "Questo è un regolare punto di rifiuti.",
  "label_trash_status_state_cleaned": "Questo punto è pulito!",
  "label_trash_status_state_outdated": "Questo punto è obsoleto!",
  "label_TP_created_date": "Creato",
  "label_TP_updated_date": "Aggiornato",
  "label_TP_by": " da ",
  "label_trash_amount_handful": "manciata",
  "label_trash_amount_bagful": "sacco pieno",
  "label_trash_amount_cartloadl": "cartload",
  "label_trash_amount_truckload": "camion",
  "label_trash_type_plastic": "Plastica",
  "label_trash_type_metal": "Metallo",
  "label_trash_type_glass": "Vetro",
  "label_trash_type_electro": "Elettronica",
  "label_trash_type_paper": "Carta/Legno",
  "label_trash_type_tyres": "Pneumatici",
  "label_trash_type_dom_waste": "Rifiuti domestici",
  "label_trash_type_furniture": "Mobili",
  "label_trash_type_org_waste": "Rifiuti organici",
  "label_header_tc": "Termini e Condizioni",
  "label_button_tc_agree": "Accetto i Termini e le Condizioni",
  "label_header_map": "Mappa",
  "label_text_popover_subtitle": "Unisciti ad altre persone che stanno mappando i rifiuti!",
  "label_text_popover_text": "Start creating trashpoints to make your community cleaner and healthier.",
  "label_header_activity": "My activity",
  "label_text_activity_empty_subtitle": "Niente da vedere qui!",
  "label_text_activity_empty_text": "You haven't added any trashpoints yet. When you do, they will be listed here.",
  "label_text_activity_empty_hint": "Add a trashpoint!",
  "label_header_notific": "Notifiche",
  "label_text_notific_empty_subtitle": "Niente da vedere qui!",
  "label_text_notific_empty_text": "We haven't seen any notifications come in yet, but we'll let you know when we do!",
  "label_header_profile": "Il mio profilo",
  "label_header_settings": "Impostazioni dell'account",
  "label_button_country_empty": "Paese",
  "label_text_country": "Paese",
  "label_header_select_country": "Seleziona un paese",
  "label_text_select_country_hint": "Cerca",
  "label_button_tc": "Termini e Condizioni",
  "label_button_logout": "Log out",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Ottimo lavoro!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Edit location",
  "label_header_edit_loc": "Edit location",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Abilitare la geolocalizzazione",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Informativa sulla Privacy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "Un punto può essere modificato solo se sei nel raggio di 100 metri da esso.",
  "label_retry_button": "Riprova",
  "label_country_picker_placeholder": "Scegli il tuo paese",
  "label_camera_permission_warning_ios": "E' necessario modificare i permessi dell'accesso alla fotocamera. Per fare questo, vai su Impostazioni>Privacy>Fotocamera",
  "label_camera_permission_warning_android": "E' necessario modificare i permessi dell'accesso alla fotocamera. Per fare questo, vai su Impostazioni>Applicazioni",
  "label_camera_error_title": "Negato l'accesso alla fotocamera",
  "label_error_modal_default_title": "Oh no!",
  "label_error_modal_default_subtitle": "La whale fail ha rilevato un errpre del server!",
  "label_location_permission_warning_ios": "È necessario modificare i permessi di localizazzione. Per fare questo, vai su Impostazioni > Privacy> Servizi di localizazzione.",
  "label_location_permission_warning_android": "È necessario modificare i permessi di localizazzione. Per fare questo, vai su Impostazioni > applicazioni.",
  "label_location_off_warning": "Servizi di localizzazione sono disattivati. Si prega di attivare il GPS nell'impostazioni per utilizzare l'applicazione.",
  "label_location_modal_title": "Abilitare la localizzazione",
  "label_network_off_warning_title": "Nessuna connessione di rete",
  "label_network_off_warning": "La data mobile è disabilitata. Attiva la data mobile o connetti il tuo cellulare al Wi-Fi per usare l'applicazione.",
  "label_loading_image_text": "Ci siamo quasi...",
  "label_loading_image_subtext": "Si prega di attendere mentre salviamo le tue azioni.",
  "label_create_marker_missing_photos": "Le marker photos potrebbe non essere caricate. Vi preghiamo di provare nuovamente ad aggiungerli.",
  "label_edit_marker_missing_photos": "Le marker photos potrebbe non essere caricate. Vi preghiamo di provare nuovamente ad aggiungerli.",
  "label_confirm_marker_missing_photos": "Le marker photos potrebbe non essere caricate. Si prega di riprovare ad aggiungerli.",
  "label_button_delete": "Elimina",
  "label_delete_photo_title": "Elimina la foto",
  "label_delete_photo_subtitle": "Sei sicuro di che voler cancellare la foto? Non è possibile annullare questo.",
  "label_text_about_1": "Questa app è un iniziativa di Let's Do It World",
  "label_text_about_2": "Tutti i dati che sono raccolti dagli utenti in tutto il mondo verranno visualizzati nella mappatura globale dei rifiuti per l'avvio l'evento mondiale clean-up (pulizia) nel giorno World Cleanup (pulizia mondiale), 15 Settembre 2018",
  "label_text_about_3": "Questa app è una collaborazione congiunta con",
  "label_text_about_4": "Prodotti estone, sponsorizzati dal paese e dal governo",
  "label_text_about_5": "Finanziatori: Ministero dell'ambiente Estone, Ministero degli affari esteri della Repubblica d'Estonia, Repubblica di Estonia 100 programmi",
  "label_button_editTP_delete": "Cancella il punto di rifiuti",
  "label_locked_account_warning": "Il tuo account è bloccato. Per ulteriori informazioni contattare un amministratore."
}