{
  "label_text_app_subtitle": "La oss rydde verden sammen!",
  "label_button_facebook": "Fortsett med Facebook",
  "label_button_google": "Fortsett med Google",
  "label_button_try_app": "Prøv appen uten en konto",
  "label_button_acknowledge": "OK, har det!",
  "label_button_cancel": "Avbryt",
  "label_button_continue": "Fortsett",
  "label_trash_status_threat": "trussel",
  "label_trash_status_regular": "vanlig",
  "label_trash_status_cleaned": "ryddet",
  "label_trash_status_outdated": "utdatert",
  "label_trash_status_user": "bruker",
  "label_trash_status_change_location": "bytt plassering",
  "label_trash_status_state_threat": "Dette punktet er en trussel!",
  "label_trash_status_state_regular": "Dette er et vanlig søppelpunkt.",
  "label_trash_status_state_cleaned": "Dette punktet er ryddet!",
  "label_trash_status_state_outdated": "Dette punktet er utdatert!",
  "label_TP_created_date": "Opprettet",
  "label_TP_updated_date": "Oppdatert",
  "label_TP_by": " av ",
  "label_trash_amount_handful": "nok til å tas med hånden",
  "label_trash_amount_bagful": "nok til å fylle en sekk",
  "label_trash_amount_cartloadl": "nok til å fylle en kjerre",
  "label_trash_amount_truckload": "nok til å fylle en lastebil",
  "label_trash_type_plastic": "Plastikk",
  "label_trash_type_metal": "Metall",
  "label_trash_type_glass": "Glass",
  "label_trash_type_electro": "Elektronikk",
  "label_trash_type_paper": "Papir/Treverk",
  "label_trash_type_tyres": "Dekk",
  "label_trash_type_dom_waste": "Husholdningsavfall",
  "label_trash_type_furniture": "Møbler",
  "label_trash_type_org_waste": "Organisk avfall",
  "label_header_tc": "Vilkår og betingelser",
  "label_button_tc_agree": "Jeg er enig med vilkårene & betingelsene",
  "label_header_map": "Kart",
  "label_text_popover_subtitle": "Bli med andre mennesker som kartlegger søppel!",
  "label_text_popover_text": "Begynn å opprette søppelpunkter for å gjøre samfunnet ditt renere og sunnere.",
  "label_header_activity": "Aktiviteten min",
  "label_text_activity_empty_subtitle": "Ingenting å se her!",
  "label_text_activity_empty_text": "Du har ikke lagt til noen søppelpunkter ennå. Når du gjør, vil de vises her.",
  "label_text_activity_empty_hint": "Legg til et søppelpunkt!",
  "label_header_notific": "Varsler",
  "label_text_notific_empty_subtitle": "Ingenting å se her!",
  "label_text_notific_empty_text": "Vi har ikke sett noen varsler komme inn ennå, men vi lar deg vite når vi gjør!",
  "label_header_profile": "Profilen min",
  "label_header_settings": "Kontoinnstillinger",
  "label_button_country_empty": "Land",
  "label_text_country": "Land",
  "label_header_select_country": "Velg et land",
  "label_text_select_country_hint": "Søk",
  "label_button_tc": "Vilkår og betingelser",
  "label_button_logout": "Logg ut",
  "label_text_congrats_image": "Søppel fanget",
  "label_text_congrats_subtitle": "Bra jobbet!",
  "label_text_congrats_text": "Nå lagr punktet ved å bekrefte dataene.",
  "label_header_createTP": "Opprett et søppelpunkt",
  "label_button_createTP_editloc": "Redigér plassering",
  "label_header_edit_loc": "Redigér plassering",
  "label_button_edit_loc_set": "Angi søppelpunktplassering",
  "label_text_createTP_status_subtitle": "Punktstatus",
  "label_text_createTP_status_text": "Hvis en rask handling er nødvendig (giftig, tunge metaller), vennligst bruk trussel.",
  "label_text_createTP_add_photos": "Legg til bilder av søppelet",
  "label_text_createTP_select_amount": "Velg søppelmengde",
  "label_text_createTP_select_type": "Velg søppeltype",
  "label_text_createTP_add_hashtags": "Ekstra stikkord",
  "label_text_createTP_add_hashtags_hint": "f.eks. #merkenavn, #kanner",
  "label_button_createTP_confirm_create": "Opprett søppelpunkt",
  "label_alert_createTP_success": "Søppelpunkt vellykket opprettet",
  "label_text_detailsTP_photos": "Bilder av søppelet",
  "label_text_detailsTP_amount": "Søppelmengde",
  "label_text_detailsTP_type": "Søppeltype",
  "label_text_editTP_ask": "Er informasjonen til dette søppelpunktet fortsatt riktig?",
  "label_text_editTP_letsconfirm": "Ja, jeg bekrefter",
  "label_alert_editTP_confirm": "Søppelpunkt vellykket bekreftet",
  "label_text_editTP_letsedit": "Nei, la oss redigere",
  "label_header_editTP": "Redigér et søppelpunkt",
  "label_button_editTP_save": "Lagr endringer",
  "label_alert_editTP_edit": "Søppelpunkt vellykket oppdatert",
  "label_alert_editTP_delete": "Søppelpunkt vellykket slettet",
  "label_error_editTP_out_of_rng_subtitle": "Utenfor rekkevidde",
  "label_error_editTP_out_of_rng_text": "Et punkt kan kun redigeres hvis du er innen 100 meter fra det.",
  "label_error_saveTP_subtitle": "Lagr søppelpunkt",
  "label_error_saveTP_pic_and_type": "Det er nyttigere for oss hvis du tar minst ett bilde av søppelpunktet og angir søppeltype.",
  "label_error_saveTP_picture": "Det er nyttigere for oss hvis du tar minst ett bilde av søppelpunktet før lagring.",
  "label_error_saveTP_trash_type": "Det er nyttigere for oss hvis du angir søppelpunktets type før lagring.",
  "label_error_change_loc_subtitle": "Utenfor rekkevidde",
  "label_error_change_loc_text": "Vennligst plassér et punkt innen 100 meter fra posisjonen din.",
  "label_error_generic_error_subtitle": "Utenfor rekkevidde",
  "label_error_generic_error_text": "Det oppsto en serverfeil.",
  "label_error_network_subtitle": "Ingen nettverkstilkobling",
  "label_error_network_text": "Mobildata er av. Skru på mobildata eller kobl telefonen din til WiFi for å bruke applikasjonen.",
  "label_error_location_subtitle": "Tillat plassering",
  "label_error_location_text": "Posisjonstjenester er av. Vennligst skru dem på i innstillingene dine for å bruke applikasjonen.",
  "label_error_loc_permission_text": "Posisjonstjenester er av. Vennligst skru dem på for å bruke applikasjonen.",
  "label_trash_details_header": "Søppelpunktdetaljer",
  "label_privacy_policy_header": "Personvern",
  "label_about_header": "Om",
  "label_edit_trashpoint_button": "Redigér søppelpunkt",
  "label_100m_limit_modal": "Et punkt kan kun redigeres hvis du er innen 100 meter fra det.",
  "label_retry_button": "Prøv igjen",
  "label_country_picker_placeholder": "Velg landet ditt",
  "label_camera_permission_warning_ios": "Du må tillate kameratilgang.",
  "label_camera_permission_warning_android": "Du må tillate kameratilgang.",
  "label_camera_error_title": "Kameratilgang nektet",
  "label_error_modal_default_title": "Fillern!",
  "label_error_modal_default_subtitle": "Vi oppdaget en serverfeil!",
  "label_location_permission_warning_ios": "Du må tillate posisjonstjenester.",
  "label_location_permission_warning_android": "Du må tillate posisjonstjenester.",
  "label_location_off_warning": "Posisjonstjenester er av. Vennligst skru dem på i innstillingene dine for å bruke applikasjonen.",
  "label_location_modal_title": "Tillat plassering",
  "label_network_off_warning_title": "Ingen nettverkstilkobling",
  "label_network_off_warning": "Mobildata er av. Skru på mobildata eller kobl telefonen din til WiFi for å bruke applikasjonen.",
  "label_loading_image_text": "Nesten der...",
  "label_loading_image_subtext": "Vennligst vent mens vi lagrer handlingene dine.",
  "label_create_marker_missing_photos": "Bildene kunne ikke lastes opp. Vennligst prøv å legge dem til igjen.",
  "label_edit_marker_missing_photos": "Bildene kunne ikke lastes opp. Vennligst prøv å legge dem til igjen.",
  "label_confirm_marker_missing_photos": "Bildene kunne ikke lastes opp. Vennligst prøv å legge dem til igjen.",
  "label_button_delete": "Slett",
  "label_delete_photo_title": "Slett bilde",
  "label_delete_photo_subtitle": "Er du sikker på at du vil slette bildet? Du kan ikke få det tilbake.",
  "label_text_about_1": "Denne appen er en skapelse fra Let's Do It World",
  "label_text_about_2": "All dataen samlet fra brukere over hele verden vil vises på det globale søppelkartet for å sette i gang verdensomspennende ryddebegivenheter på Verdens Ryddedag, 15. september, 2018",
  "label_text_about_3": "Denne appen er i samarbeid med",
  "label_text_about_4": "Estisk produkt, sponset av landet og regjeringen",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Slett søppelpunkt",
  "label_locked_account_warning": "Kontoen din er låst. For detaljer, ta kontakt med en administrator."
}