{
  "label_text_app_subtitle": "Vamos limpar o mundo juntos!",
  "label_button_facebook": "Continuar com o Facebook",
  "label_button_google": "Continuar com o Google",
  "label_button_try_app": "Experimentar a aplicação sem criar uma conta",
  "label_button_acknowledge": "Ok, percebi!",
  "label_button_cancel": "Cancelar",
  "label_button_continue": "Continuar",
  "label_trash_status_threat": "ameaça",
  "label_trash_status_regular": "regular",
  "label_trash_status_cleaned": "limpo",
  "label_trash_status_outdated": "desatualizado",
  "label_trash_status_user": "utilizador",
  "label_trash_status_change_location": "mudarLocalizacao",
  "label_trash_status_state_threat": "Este ponto é perigoso!",
  "label_trash_status_state_regular": "Este é um ponto de lixo regular.",
  "label_trash_status_state_cleaned": "Este ponto está limpo!",
  "label_trash_status_state_outdated": "Este ponto está desatualizado!",
  "label_TP_created_date": "Criado",
  "label_TP_updated_date": "Atualizado",
  "label_TP_by": " por ",
  "label_trash_amount_handful": "um punhado",
  "label_trash_amount_bagful": "bagful",
  "label_trash_amount_cartloadl": "cartload",
  "label_trash_amount_truckload": "truckload",
  "label_trash_type_plastic": "Plástico",
  "label_trash_type_metal": "Metal",
  "label_trash_type_glass": "Vidro",
  "label_trash_type_electro": "Material Electrónico",
  "label_trash_type_paper": "Papel/madeira",
  "label_trash_type_tyres": "Pneus",
  "label_trash_type_dom_waste": "Lixo doméstico",
  "label_trash_type_furniture": "Mobília",
  "label_trash_type_org_waste": "Lixo orgânico",
  "label_header_tc": "Termos e condições",
  "label_button_tc_agree": "Concordo com os termos e condições",
  "label_header_map": "Mapa",
  "label_text_popover_subtitle": "Junte-se a outras pessoas que estão a mapear o lixo!",
  "label_text_popover_text": "Comece a criar pontos de lixo para tornar a sua comunidade mais limpa e mais saudável.",
  "label_header_activity": "Minha atividade",
  "label_text_activity_empty_subtitle": "Nada para ver aqui!",
  "label_text_activity_empty_text": "Ainda não adicionou nenhum ponto de lixo. Quando o fizer, eles serão listados aqui.",
  "label_text_activity_empty_hint": "Adicione um ponto de lixo!",
  "label_header_notific": "Notificações",
  "label_text_notific_empty_subtitle": "Nada para ver aqui!",
  "label_text_notific_empty_text": "Não recebemos ainda notificações, mas será avisado quando isso acontecer!",
  "label_header_profile": "Meu perfil",
  "label_header_settings": "Configurar conta",
  "label_button_country_empty": "País",
  "label_text_country": "País",
  "label_header_select_country": "Selecione um país",
  "label_text_select_country_hint": "Pesquisar",
  "label_button_tc": "Termos e condições",
  "label_button_logout": "Sair",
  "label_text_congrats_image": "Lixo capturado",
  "label_text_congrats_subtitle": "Muito bem!",
  "label_text_congrats_text": "Agora salve o ponto de lixo através da verificação dos dados.",
  "label_header_createTP": "Criar um ponto de lixo",
  "label_button_createTP_editloc": "Editar localização",
  "label_header_edit_loc": "Editar localização",
  "label_button_edit_loc_set": "Definir localização de ponto de lixo",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "Se uma ação rápida é necessária (lixo tóxico, metais pesados), defina como perigoso.",
  "label_text_createTP_add_photos": "Adicione fotos do lixo",
  "label_text_createTP_select_amount": "Selecione a quantidade de lixo",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Criar um ponto de lixo",
  "label_alert_createTP_success": "Ponto de lixo atualizado com sucesso",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Quantidade de lixo",
  "label_text_detailsTP_type": "Tipo de lixo",
  "label_text_editTP_ask": "A informação sobre este ponto de lixo ainda está correta e atualizada?",
  "label_text_editTP_letsconfirm": "Sim, confirmo",
  "label_alert_editTP_confirm": "Ponto de lixo confirmado com sucesso",
  "label_text_editTP_letsedit": "Não, vamos editar",
  "label_header_editTP": "Editar um ponto de lixo",
  "label_button_editTP_save": "Guardar as alterações do ponto de lixo",
  "label_alert_editTP_edit": "Ponto de lixo atualizado com sucesso",
  "label_alert_editTP_delete": "Ponto de lixo apagado com sucesso",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "Houve um erro no servidor.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Permitir a localização",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "Sobre",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Tente novamente",
  "label_country_picker_placeholder": "Escolha o seu país",
  "label_camera_permission_warning_ios": "Precisa alterar as permissões de acesso à câmara. Para fazer isso, vá a Configurações > Privacidade > Câmara",
  "label_camera_permission_warning_android": "You must change camera access permissions. To do this, go to Settings > Apps",
  "label_camera_error_title": "Camera Access Denied",
  "label_error_modal_default_title": "Oh não!",
  "label_error_modal_default_subtitle": "A baleia da falha encontrou um erro do servidor!",
  "label_location_permission_warning_ios": "Deve alterar as permissões de localização. Para fazer isso, dirija-se a Definições > Privacidade > Serviços de localização",
  "label_location_permission_warning_android": "Deve alterar as permissões de localização. Para fazer isso, dirija-se a Definições > Aplicações",
  "label_location_off_warning": "Serviços de localização estão desligados. Por favor ligue o seu GPS nas sua configurações para usar a aplicação.",
  "label_location_modal_title": "Permitir a localização",
  "label_network_off_warning_title": "Sem ligação à internet",
  "label_network_off_warning": "Dados móveis encontram-se desligados. Ligue os dados móveis ou conecte o seu telefone ao Wi-Fi para usar a aplicação.",
  "label_loading_image_text": "Quase lá...",
  "label_loading_image_subtext": "Por favor espere, enquanto guardamos as suas acções.",
  "label_create_marker_missing_photos": "As fotos do mercador não conseguiram ser carregadas. Por favor tente adicioná-las novamente.",
  "label_edit_marker_missing_photos": "As fotos do mercador não conseguiram ser carregadas. Por favor tente adicioná-las novamente.",
  "label_confirm_marker_missing_photos": "As fotos do mercador não conseguiram ser carregadas. Por favor tente adicioná-las novamente.",
  "label_button_delete": "Apagar",
  "label_delete_photo_title": "Apagar foto",
  "label_delete_photo_subtitle": "Tem a certeza que quer apagar a foto? Não pode voltar a recuperá-la.",
  "label_text_about_1": "Esta app é uma iniciativa da Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}