{
  "label_text_app_subtitle": "Let's clean up the world together!",
  "label_button_facebook": "Continuă cu Facebook",
  "label_button_google": "Continuă cu Google",
  "label_button_try_app": "Încercă aplicația fără să fi autentificat",
  "label_button_acknowledge": "Ok, am înțeles!",
  "label_button_cancel": "Revocare",
  "label_button_continue": "Continuă",
  "label_trash_status_threat": "ameninţare",
  "label_trash_status_regular": "normal",
  "label_trash_status_cleaned": "curățat",
  "label_trash_status_outdated": "outdated",
  "label_trash_status_user": "utilizator",
  "label_trash_status_change_location": "schimbăLocația",
  "label_trash_status_state_threat": "Acest loc este o ameninţare!",
  "label_trash_status_state_regular": "Acesta este un loc normal cu deșeuri.",
  "label_trash_status_state_cleaned": "Acest loc este curățat!",
  "label_trash_status_state_outdated": "Acest loc nu este actualizat!",
  "label_TP_created_date": "Creat",
  "label_TP_updated_date": "Actualizat",
  "label_TP_by": " de ",
  "label_trash_amount_handful": "handful",
  "label_trash_amount_bagful": "bagful",
  "label_trash_amount_cartloadl": "cartload",
  "label_trash_amount_truckload": "truckload",
  "label_trash_type_plastic": "Plastic",
  "label_trash_type_metal": "Metal",
  "label_trash_type_glass": "Sticlă",
  "label_trash_type_electro": "Electronice",
  "label_trash_type_paper": "Hârtie/Lemn",
  "label_trash_type_tyres": "Anvelope",
  "label_trash_type_dom_waste": "Gunoi menajer",
  "label_trash_type_furniture": "Mobilier",
  "label_trash_type_org_waste": "Deşeuri organice",
  "label_header_tc": "Termeni și condiții",
  "label_button_tc_agree": "Sunt de acord cu termenii & condiţiile",
  "label_header_map": "Hartă",
  "label_text_popover_subtitle": "Alătură-te persoanelor care mapează gunoiul!",
  "label_text_popover_text": "Începe să mapezi puncte cu gunoi pentru a face comunitatea ta mai curată și sănătoasă.",
  "label_header_activity": "Activitatea mea",
  "label_text_activity_empty_subtitle": "Nimic de văzut aici!",
  "label_text_activity_empty_text": "Nu ai adăugat încă nici o locație cu gunoi. După ce vei adăuga, vor fi listate aici.",
  "label_text_activity_empty_hint": "Adaugă o locație cu gunoi!",
  "label_header_notific": "Notificări",
  "label_text_notific_empty_subtitle": "Nimic de văzut aici!",
  "label_text_notific_empty_text": "Încă nu sunt notificări, te vom anunța atunci când o să fie!",
  "label_header_profile": "Profilul meu",
  "label_header_settings": "Setări cont",
  "label_button_country_empty": "Țara",
  "label_text_country": "Țara",
  "label_header_select_country": "Selectează o ţară",
  "label_text_select_country_hint": "Căutare",
  "label_button_tc": "Termeni și condiții",
  "label_button_logout": "Deconectare",
  "label_text_congrats_image": "Gunoi capturat",
  "label_text_congrats_subtitle": "Great job!",
  "label_text_congrats_text": "Acum salvează locația verificând datele.",
  "label_header_createTP": "Crează un loc cu gunoi",
  "label_button_createTP_editloc": "Editare locație",
  "label_header_edit_loc": "Editare locație",
  "label_button_edit_loc_set": "Setează locația locului cu gunoi",
  "label_text_createTP_status_subtitle": "Starea locului",
  "label_text_createTP_status_text": "Dacă este nevoie de o acțiune rapidă (toxicitate, metale gerele), vă rugăm să setați ca amenințare.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Retry",
  "label_country_picker_placeholder": "Alege ţara ta",
  "label_camera_permission_warning_ios": "Trebuie să modificaţi permisiunile de acces ale camerei. Pentru a face acest lucru, mergeţi la setări > confidenţialitate > cameră",
  "label_camera_permission_warning_android": "Trebuie să modificaţi permisiunile de acces ale camerei. Pentru a face acest lucru, mergeţi la setări > aplicații",
  "label_camera_error_title": "Camera Access Denied",
  "label_error_modal_default_title": "Oh noes!",
  "label_error_modal_default_subtitle": "The fail whale detected a server error!",
  "label_location_permission_warning_ios": "You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Enable location",
  "label_network_off_warning_title": "No network connection",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Almost there...",
  "label_loading_image_subtext": "Please wait while we save your actions.",
  "label_create_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Delete",
  "label_delete_photo_title": "Delete photo",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}