{
  "label_text_app_subtitle": "Давайте очистим мир вместе!",
  "label_button_facebook": "Продолжить через Фейсбук",
  "label_button_google": "Продолжить через Гугл",
  "label_button_try_app": "Испытайте приложение, не создавая аккаунт",
  "label_button_acknowledge": "Окей, понятно!",
  "label_button_cancel": "Отмена",
  "label_button_continue": "Продолжить",
  "label_trash_status_threat": "опасность",
  "label_trash_status_regular": "обычный",
  "label_trash_status_cleaned": "очищенный",
  "label_trash_status_outdated": "неактуально",
  "label_trash_status_user": "пользователь",
  "label_trash_status_change_location": "изменитьМестоположение",
  "label_trash_status_state_threat": "Эта точка опасна!",
  "label_trash_status_state_regular": "Обыкновенное место сбора мусора",
  "label_trash_status_state_cleaned": "Точка была очищена!",
  "label_trash_status_state_outdated": "Данные о точке устарели!",
  "label_TP_created_date": "Создано",
  "label_TP_updated_date": "Обновлено",
  "label_TP_by": " по ",
  "label_trash_amount_handful": "небольшая куча мусора",
  "label_trash_amount_bagful": "полный мешок",
  "label_trash_amount_cartloadl": "воз",
  "label_trash_amount_truckload": "грузовик",
  "label_trash_type_plastic": "Пластик",
  "label_trash_type_metal": "Металл",
  "label_trash_type_glass": "Стекло",
  "label_trash_type_electro": "Электроника",
  "label_trash_type_paper": "Бумага/дерево",
  "label_trash_type_tyres": "Шины",
  "label_trash_type_dom_waste": "Бытовые отходы",
  "label_trash_type_furniture": "Мебель",
  "label_trash_type_org_waste": "Органические отходы",
  "label_header_tc": "Условия использования приложения",
  "label_button_tc_agree": "Я согласен с условиями пользования приложением",
  "label_header_map": "Карта",
  "label_text_popover_subtitle": "Присоединяйтесь к людям, которые наносят мусор на карту!",
  "label_text_popover_text": "Начните создание мест для сбора мусора, чтобы сделать ваше сообщество чище и здоровее.",
  "label_header_activity": "Моя деятельность",
  "label_text_activity_empty_subtitle": "Здесь ничего нет!",
  "label_text_activity_empty_text": "Вы пока еще не добавили ни одного места для сбора мусора. Когда вы это сделаете, точки будут отображены здесь.",
  "label_text_activity_empty_hint": "Добавить место для сбора мусора!",
  "label_header_notific": "Уведомления",
  "label_text_notific_empty_subtitle": "Здесь ничего нет!",
  "label_text_notific_empty_text": "Пока никаких уведомлений не поступало, но мы сообщим, когда они появятся!",
  "label_header_profile": "Мой профиль",
  "label_header_settings": "Настройки аккаунта",
  "label_button_country_empty": "Страна",
  "label_text_country": "Страна",
  "label_header_select_country": "Выберите страну",
  "label_text_select_country_hint": "Поиск",
  "label_button_tc": "Условия и положения",
  "label_button_logout": "Выйти",
  "label_text_congrats_image": "Мусор зафиксирован",
  "label_text_congrats_subtitle": "Отлично! Молодец!",
  "label_text_congrats_text": "Теперь сохраните точку, проверив данные.",
  "label_header_createTP": "Создать место для сбора мусора",
  "label_button_createTP_editloc": "Изменить месторасположение",
  "label_header_edit_loc": "Изменить месторасположение",
  "label_button_edit_loc_set": "Установить место для сбора мусора",
  "label_text_createTP_status_subtitle": "Статус точки",
  "label_text_createTP_status_text": "Если нужно отреагировать незамедлительно (ядовитые отходы, тяжелые металлы), просим отметить точку как опасную.",
  "label_text_createTP_add_photos": "Добавить фотографии мусора",
  "label_text_createTP_select_amount": "Выбрать количество мусора",
  "label_text_createTP_select_type": "Выбрать тип мусора",
  "label_text_createTP_add_hashtags": "Добавить дополнительные метки",
  "label_text_createTP_add_hashtags_hint": "например: #название изделия, #банки",
  "label_button_createTP_confirm_create": "Создать место для сбора мусора",
  "label_alert_createTP_success": "Место для сбора мусора успешно создано",
  "label_text_detailsTP_photos": "Фотографии мусора",
  "label_text_detailsTP_amount": "Количество мусора",
  "label_text_detailsTP_type": "Тип мусора",
  "label_text_editTP_ask": "Верны ли эти данные и не устарели ли они?",
  "label_text_editTP_letsconfirm": "Да, я подтверждаю",
  "label_alert_editTP_confirm": "Место для сбора мусора успешно утверждено",
  "label_text_editTP_letsedit": "Нет, нужно отредактировать",
  "label_header_editTP": "Редактировать место для сбора мусора",
  "label_button_editTP_save": "Сохранить изменения о месте для сбора мусора",
  "label_alert_editTP_edit": "Место для сбора мусора успешно обновлено",
  "label_alert_editTP_delete": "Место для сбора мусора успешно удалено",
  "label_error_editTP_out_of_rng_subtitle": "Вне досягаемости",
  "label_error_editTP_out_of_rng_text": "Мусорную точку можно изменить, находясь от нее в пределах 100 м.",
  "label_error_saveTP_subtitle": "Сохранить место для сбора мусора",
  "label_error_saveTP_pic_and_type": "Просим добавить фотографию места для сбора мусора и определить тип мусора.",
  "label_error_saveTP_picture": "Будет полезнее, если вы сделаете хотя бы одну фотографию места для сбора мусора перед его сохранением.",
  "label_error_saveTP_trash_type": "Будет полезнее, если вы отметите тип места для сбора мусора перед его сохранением.",
  "label_error_change_loc_subtitle": "За пределами допустимых границ",
  "label_error_change_loc_text": "Просим отметить точку в радиусе 100 м от вашего местонахождения.",
  "label_error_generic_error_subtitle": "За пределами допустимых границ",
  "label_error_generic_error_text": "На сервере произошла ошибка.",
  "label_error_network_subtitle": "Нет сетевого соединения",
  "label_error_network_text": "Мобильные данные отключены. Чтобы использовать приложение, включите мобильные данные или подключите ваш смартфон к Wi-Fi.",
  "label_error_location_subtitle": "Разрешить определить местонахождение",
  "label_error_location_text": "Услуга определения местоположения отключена. Чтобы использовать приложение, включите услугу GPS.",
  "label_error_loc_permission_text": "Услуга определения местоположения не разрешена. Просим разрешить услугу, чтобы использовать приложение.",
  "label_trash_details_header": "О месте для сбора мусора",
  "label_privacy_policy_header": "Политика конфиденциальности",
  "label_about_header": "О нас",
  "label_edit_trashpoint_button": "Редактировать место для сбора мусора",
  "label_100m_limit_modal": "Точка может быть отредактирована, только если вы находитесь от нее в радиусе 100 метров.",
  "label_retry_button": "Попробуйте еще раз",
  "label_country_picker_placeholder": "Выберите вашу страну",
  "label_camera_permission_warning_ios": "Вы должны изменить права доступа к фотокамере. Чтобы сделать это, перейдите на страницу Настройки > Конфиденциальность > Камера",
  "label_camera_permission_warning_android": "Вы должны изменить права доступа к фотокамере. Чтобы сделать это, перейдите на страницу Настройки > Конфиденциальность > Камера",
  "label_camera_error_title": "Отказ в доступе к камере",
  "label_error_modal_default_title": "О, нет!",
  "label_error_modal_default_subtitle": "Обнаружена ошибка сервера!",
  "label_location_permission_warning_ios": "Необходимо изменить разрешение для определения местоположения. Чтобы сделать это, зайдите в Настройки > Конфиденциальность > Сервис локализации.",
  "label_location_permission_warning_android": "Необходимо изменить разрешения для определения местоположения. Чтобы сделать это, зайдите в Настройки - Приложений.",
  "label_location_off_warning": "Услуга определения местонахождения отключена. Чтобы использовать приложение, просим включить GPS в ваших настройках.",
  "label_location_modal_title": "Разрешить определение местонахождения",
  "label_network_off_warning_title": "Нет интернет-соединения",
  "label_network_off_warning": "Передача мобильных данных отключена. Чтобы использовать приложение, разрешите передавать мобильные данные или подключите ваш смартфон к Wi-Fi.",
  "label_loading_image_text": "Почти готово...",
  "label_loading_image_subtext": "Просим подождать, пока мы сохраняем ваши данные.",
  "label_create_marker_missing_photos": "Фотографии точки не удалось загрузить. Просим добавить их еще раз.",
  "label_edit_marker_missing_photos": "Фотографии точки не удалось загрузить. Просим добавить их еще раз.",
  "label_confirm_marker_missing_photos": "Фотографии точки не удалось загрузить. Просим попробовать добавить их еще раз.",
  "label_button_delete": "Удалить",
  "label_delete_photo_title": "Удалить фото",
  "label_delete_photo_subtitle": "Вы уверены, что желаете удалить фотографию? Это действие нельзя отменить.",
  "label_text_about_1": "Данное приложение является инициативой Let's Do it World",
  "label_text_about_2": "Все данные, поступившие от пользователей со всего мира, доступны на глобальной мусорной карте, чтобы Всемирная уборка 15.09.2018 г. была бы организована наилучшим образом во всех уголках земного шара",
  "label_text_about_3": "Данное приложение родилось в ходе сотрудничества с",
  "label_text_about_4": "Эстонский продукт; создан при поддержке страны и правительства",
  "label_text_about_5": "Спонсоры: Министерство окружающей среды, Министерство иностранных дел Эстонской Республики, юбилейная программа \"Эстонской Республике -100\"",
  "label_button_editTP_delete": "Удалить место для сбора мусора",
  "label_locked_account_warning": "Ваш аккаунт заблокирован. Обратитесь к администратору за подробностями."
}