{
  "label_text_app_subtitle": "Давайте очистим мир вместе !",
  "label_button_facebook": "Продолжить с Фейсбук",
  "label_button_google": "Продолжить с Гугл",
  "label_button_try_app": "Испытай приложение не создавая аккаунт",
  "label_button_acknowledge": "Ок, понятно!",
  "label_button_cancel": "Отмена",
  "label_button_continue": "Продолжить",
  "label_trash_status_threat": "угроза",
  "label_trash_status_regular": "обычный",
  "label_trash_status_cleaned": "очищенный",
  "label_trash_status_outdated": "неактуально",
  "label_trash_status_user": "пользователь",
  "label_trash_status_change_location": "изменитьМестоположение",
  "label_trash_status_state_threat": "Эта точка представляет собой угрозу!",
  "label_trash_status_state_regular": "Обыкновенный мусорный пункт.",
  "label_trash_status_state_cleaned": "Место было очищено!",
  "label_trash_status_state_outdated": "Данное место неактуально!",
  "label_TP_created_date": "Создано",
  "label_TP_updated_date": "Обновлено",
  "label_TP_by": " by ",
  "label_trash_amount_handful": "горсть",
  "label_trash_amount_bagful": "мешок",
  "label_trash_amount_cartloadl": "воз",
  "label_trash_amount_truckload": "грузовик",
  "label_trash_type_plastic": "Пластик",
  "label_trash_type_metal": "Металл",
  "label_trash_type_glass": "Стекло",
  "label_trash_type_electro": "Электроника",
  "label_trash_type_paper": "Бумага/дерево",
  "label_trash_type_tyres": "Шины",
  "label_trash_type_dom_waste": "Бытовые отходы",
  "label_trash_type_furniture": "Мебель",
  "label_trash_type_org_waste": "Органические отходы",
  "label_header_tc": "Условия контракта",
  "label_button_tc_agree": "Я согласен с условиями договора",
  "label_header_map": "Карта",
  "label_text_popover_subtitle": "Присоединяйтесь к другим людей, которые наносят мусор на карту!",
  "label_text_popover_text": "Начните создание мусорных пунктов, чтобы сделать ваше сообщество более чистым и здоровым.",
  "label_header_activity": "Моя деятельность",
  "label_text_activity_empty_subtitle": "Здесь ничего нет!",
  "label_text_activity_empty_text": "Вы пока еще не добавили ни один мусорный пункт. Когда вы сделаете это, они будут перечислены здесь.",
  "label_text_activity_empty_hint": "Добавить мусорный пункт!",
  "label_header_notific": "Уведомления",
  "label_text_notific_empty_subtitle": "Здесь ничего нет!",
  "label_text_notific_empty_text": "Пока никаких уведомлений не поступало, но мы дадим вам знать, когда они появятся!",
  "label_header_profile": "Мой профиль",
  "label_header_settings": "Настройки аккаунта",
  "label_button_country_empty": "Страна",
  "label_text_country": "Страна",
  "label_header_select_country": "Выберите страну",
  "label_text_select_country_hint": "Search",
  "label_button_tc": "Terms and Conditions",
  "label_button_logout": "Log out",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Great job!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Edit location",
  "label_header_edit_loc": "Edit location",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "Место может быть отредактировано, только если вы находитесь в пределах 100 метров от него.",
  "label_retry_button": "Повтор",
  "label_country_picker_placeholder": "Выберите вашу страну",
  "label_camera_permission_warning_ios": "Вы должны изменить права доступа фото камеры. Чтобы сделать это, перейдите на страницу Настройки > Конфиденциальность > Камера",
  "label_camera_permission_warning_android": "Вы должны изменить права доступа фото камеры. Чтобы сделать это, перейдите на страницу Настройки > Конфиденциальность > Камера",
  "label_camera_error_title": "Отказ доступа к камере",
  "label_error_modal_default_title": "О нет!",
  "label_error_modal_default_subtitle": "Обнаружена ошибка сервера!",
  "label_location_permission_warning_ios": "Вы должны изменить права доступа фото камеры. Чтобы сделать это, перейдите на страницу Настройки > Конфиденциальность > Камера.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Enable location",
  "label_network_off_warning_title": "No network connection",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Almost there...",
  "label_loading_image_subtext": "Please wait while we save your actions.",
  "label_create_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Delete",
  "label_delete_photo_title": "Delete photo",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}