{
  "label_text_app_subtitle": "Ta pastrojmë botën sëbashku!",
  "label_button_facebook": "Vazhdo me Facebook",
  "label_button_google": "Vazhdo me Google",
  "label_button_try_app": "Provo App pa llogari",
  "label_button_acknowledge": "Ok, e kuptova!",
  "label_button_cancel": "Anullo",
  "label_button_continue": "Vazhdo",
  "label_trash_status_threat": "kërcënim",
  "label_trash_status_regular": "normale",
  "label_trash_status_cleaned": "pastruar",
  "label_trash_status_outdated": "i vjetruar",
  "label_trash_status_user": "përdorues",
  "label_trash_status_change_location": "ndrroVendodhjen",
  "label_trash_status_state_threat": "Kjo pikë është një kërcënim!",
  "label_trash_status_state_regular": "Kjo është një pikë normale mbeturinash.",
  "label_trash_status_state_cleaned": "Kjo pikë është pastruar!",
  "label_trash_status_state_outdated": "Kjo pikë është e vjetëruar!",
  "label_TP_created_date": "Krijuar",
  "label_TP_updated_date": "Përditësuar",
  "label_TP_by": " nga ",
  "label_trash_amount_handful": "një dorë",
  "label_trash_amount_bagful": "thes",
  "label_trash_amount_cartloadl": "karrocë",
  "label_trash_amount_truckload": "kamion",
  "label_trash_type_plastic": "Plastik",
  "label_trash_type_metal": "Metal",
  "label_trash_type_glass": "Qelq",
  "label_trash_type_electro": "Elektronike",
  "label_trash_type_paper": "Letër/Dru",
  "label_trash_type_tyres": "Goma",
  "label_trash_type_dom_waste": "Mbetje shtëpiake",
  "label_trash_type_furniture": "Mobilje",
  "label_trash_type_org_waste": "Mbetje organike",
  "label_header_tc": "Terma dhe Kushte",
  "label_button_tc_agree": "Pajtohem me Termat & Kushtet",
  "label_header_map": "Harta",
  "label_text_popover_subtitle": "Bashkohu me njerëzit që hartizojnë mbeturinat!",
  "label_text_popover_text": "Shënoni vendndodhjen e mbeturinave që ta bëni hapësirën komunitare më të pastër dhe më të shëndetshme.",
  "label_header_activity": "Aktiviteti im",
  "label_text_activity_empty_subtitle": "Nuk ka asgjë për të parë këtu!",
  "label_text_activity_empty_text": "You haven't added any trashpoints yet. When you do, they will be listed here.",
  "label_text_activity_empty_hint": "Add a trashpoint!",
  "label_header_notific": "Njoftime",
  "label_text_notific_empty_subtitle": "Nothing to see here!",
  "label_text_notific_empty_text": "We haven't seen any notifications come in yet, but we'll let you know when we do!",
  "label_header_profile": "Profili im",
  "label_header_settings": "Account settings",
  "label_button_country_empty": "Shteti",
  "label_text_country": "Shteti",
  "label_header_select_country": "Zgjidh një shtet",
  "label_text_select_country_hint": "Kërko",
  "label_button_tc": "Terma dhe Kushte",
  "label_button_logout": "Dilni",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Punë e mrekullueshme!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Ndrysho vendodhjen",
  "label_header_edit_loc": "Ndrysho vendodhjen",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Statusi i pikës",
  "label_text_createTP_status_text": "Nëse nevojitet një veprim i shpejtë (toksike, metale të rënda), vedoseni si kërcënim.",
  "label_text_createTP_add_photos": "Shto foto mbeturinash",
  "label_text_createTP_select_amount": "Përcakto sasinë e mbeturinave",
  "label_text_createTP_select_type": "Përcakto llojin e mbeturinave",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "psh. #emriimarkës, #kanaçe",
  "label_button_createTP_confirm_create": "Krijo pikë mbeturinash",
  "label_alert_createTP_success": "Pika e mbeturinave u krijua me sukses",
  "label_text_detailsTP_photos": "Foto mbeturinash",
  "label_text_detailsTP_amount": "Sasia e mbeturinave",
  "label_text_detailsTP_type": "Lloji i mbeturinave",
  "label_text_editTP_ask": "A është imformacioni i kësaj pike mbeturinash i saktë dhe i përditësuar?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Pika e mbeturinave u konfirmua me sukses",
  "label_text_editTP_letsedit": "Jo, ta ndryshojmë",
  "label_header_editTP": "Ndrysho një pikë mbeturinash",
  "label_button_editTP_save": "Ruaj ndryshimet e pikës së mbeturinave",
  "label_alert_editTP_edit": "Pika e mbeturinave u përditësua me sukses",
  "label_alert_editTP_delete": "Pika e mbeturinave u fshi me sukses",
  "label_error_editTP_out_of_rng_subtitle": "Jashtë rrezes",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Retry",
  "label_country_picker_placeholder": "Choose your country",
  "label_camera_permission_warning_ios": "You must change camera access permissions. To do this, go to Settings > Privacy > Camera",
  "label_camera_permission_warning_android": "You must change camera access permissions. To do this, go to Settings > Apps",
  "label_camera_error_title": "Camera Access Denied",
  "label_error_modal_default_title": "Oh noes!",
  "label_error_modal_default_subtitle": "The fail whale detected a server error!",
  "label_location_permission_warning_ios": "You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Enable location",
  "label_network_off_warning_title": "No network connection",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Almost there...",
  "label_loading_image_subtext": "Prisni sa të ruajmë veprimet tuaja.",
  "label_create_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Fshi",
  "label_delete_photo_title": "Fshi foto",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}