{
  "label_text_app_subtitle": "Tuungane pamoja tusafishe Dunia!",
  "label_button_facebook": "Endelea na usajili wa Facebook",
  "label_button_google": "Endelea na usajili wa kwenye mtandao wa google",
  "label_button_try_app": "Jaribu kufungua programu bila kujisajili kwenye akaunti mpya",
  "label_button_acknowledge": "Ndio, imekubali!",
  "label_button_cancel": "Futa",
  "label_button_continue": "Endelea",
  "label_trash_status_threat": "hatari",
  "label_trash_status_regular": "kawaida",
  "label_trash_status_cleaned": "safi",
  "label_trash_status_outdated": "muda wa matumizi umeisha",
  "label_trash_status_user": "mtumiaji",
  "label_trash_status_change_location": "badili eneo",
  "label_trash_status_state_threat": "Eneo hili ni hatari!",
  "label_trash_status_state_regular": "Hili ni eneo lenye taka za kawaida.",
  "label_trash_status_state_cleaned": "Eneo hili limesafishwa!",
  "label_trash_status_state_outdated": "Eneo hili muda wake umepita!",
  "label_TP_created_date": "Imetengenezwa",
  "label_TP_updated_date": "Imeboreshwa",
  "label_TP_by": " kwa ",
  "label_trash_amount_handful": "kiganja",
  "label_trash_amount_bagful": "mfuko",
  "label_trash_amount_cartloadl": "mkokoteni",
  "label_trash_amount_truckload": "lori",
  "label_trash_type_plastic": "Plastiki",
  "label_trash_type_metal": "Chuma",
  "label_trash_type_glass": "Kioo",
  "label_trash_type_electro": "Vifaa vya umeme",
  "label_trash_type_paper": "Karatasi/Mbao",
  "label_trash_type_tyres": "Tairi",
  "label_trash_type_dom_waste": "Taka za majumbani",
  "label_trash_type_furniture": "Samani",
  "label_trash_type_org_waste": "Taka ozo",
  "label_header_tc": "Vigezo na masharti",
  "label_button_tc_agree": "Nakubaliana na vigezo na masharti",
  "label_header_map": "Ramani",
  "label_text_popover_subtitle": "Ungana na watu wanao chora ramani sehemu zenye taka!",
  "label_text_popover_text": "Anza kuunda maeneo yenye taka, kufanya jamii yako safi na salama.",
  "label_header_activity": "Shughuli yangu",
  "label_text_activity_empty_subtitle": "Hamna kitu!",
  "label_text_activity_empty_text": "Hakuna eneo lenye taka lilioongezwa. likiwekwa, litaorodheshwa hapa.",
  "label_text_activity_empty_hint": "Weka eneo lenye taka!",
  "label_header_notific": "Taarifa",
  "label_text_notific_empty_subtitle": "Hamna kitu!",
  "label_text_notific_empty_text": "Bado hatujaona taarifa yeyote ikiingia, tutakujulisha pindi tutakapofanya!",
  "label_header_profile": "Maelezo mafupi",
  "label_header_settings": "Kufungua akaunti",
  "label_button_country_empty": "Nchi",
  "label_text_country": "Nchi",
  "label_header_select_country": "Chagua nchi",
  "label_text_select_country_hint": "Tafuta",
  "label_button_tc": "Vigezo na masharti",
  "label_button_logout": "Aga",
  "label_text_congrats_image": "Taka zimepigwa picha",
  "label_text_congrats_subtitle": "Kazi nzuri!",
  "label_text_congrats_text": "Sasa hifadhi eneo lenye taka kwa kuhakikisha taarifa.",
  "label_header_createTP": "Unda eneo lenye taka",
  "label_button_createTP_editloc": "Hariri mahali",
  "label_header_edit_loc": "Hariri mahali",
  "label_button_edit_loc_set": "Seti eneo lenye taka",
  "label_text_createTP_status_subtitle": "Hali ya eneo",
  "label_text_createTP_status_text": "Kama hatua za haraka zinahitajika (sumu, metali nzito), Tafadhali weka alama ya tishio.",
  "label_text_createTP_add_photos": "Ongeza picha ya takataka",
  "label_text_createTP_select_amount": "Chagua kiwango cha taka",
  "label_text_createTP_select_type": "Chagua aina ya taka",
  "label_text_createTP_add_hashtags": "Lebo ya ziada iliyoongezwa",
  "label_text_createTP_add_hashtags_hint": "kama. #jinalakampuni, #kopo",
  "label_button_createTP_confirm_create": "Unda eneo lenye taka",
  "label_alert_createTP_success": "Eneo lenye taka limefanikiwa kuundwa",
  "label_text_detailsTP_photos": "Picha ya takataka",
  "label_text_detailsTP_amount": "Kiasi cha taka",
  "label_text_detailsTP_type": "Aina ya taka",
  "label_text_editTP_ask": "Taarifa ya eneo lenye taka bado ni sahihi na imesahihishwa?",
  "label_text_editTP_letsconfirm": "Ndio, Nathibitisha",
  "label_alert_editTP_confirm": "Eneo lenye taka limefanikiwa kuthibitishwa",
  "label_text_editTP_letsedit": "Hapana, hebu turekebishe",
  "label_header_editTP": "Hariri eneo lenye taka",
  "label_button_editTP_save": "Kuhifadhi mabadiliko ya eneo lenye taka",
  "label_alert_editTP_edit": "Eneo lenye taka limefanikiwa kusahihishwa",
  "label_alert_editTP_delete": "Eneo lenye taka limefanikiwa kufutwa",
  "label_error_editTP_out_of_rng_subtitle": "Haipatikani",
  "label_error_editTP_out_of_rng_text": "Eneo lenye taka linaweza kuhaririwa, kama utakuwa umbali wa mita 100 toka kwenye eneo hilo.",
  "label_error_saveTP_subtitle": "Hifadhi eneo lenye taka",
  "label_error_saveTP_pic_and_type": "Ni muhimu zaidi kwa ajili yetu kama unaweza kuchukua picha angalau moja ya eneo lenye taka na kuweka aina ya taka.",
  "label_error_saveTP_picture": "Ni muhimu zaidi kwetu kama wewe kuchukua picha angalau moja ya eneo lenye taka kabla ya kuhifadhi.",
  "label_error_saveTP_trash_type": "Ni muhimu zaidi kwa ajili yetu kama unaweza kuweka aina ya eneo lenye taka kabla ya kuhifadhi.",
  "label_error_change_loc_subtitle": "Nje ya mipaka",
  "label_error_change_loc_text": "Tafadhali weka pointi ndani ya mita 100 za eneo lako.",
  "label_error_generic_error_subtitle": "Nje ya mipaka",
  "label_error_generic_error_text": "Kulikuwa na kosa katika seva.",
  "label_error_network_subtitle": "Hakuna mtandao uliounganishwa",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "Eneo lenye taka linaweza kuhaririwa, kama utakuwa umbali wa mita 100 toka kwenye eneo hilo.",
  "label_retry_button": "Jaribu tena",
  "label_country_picker_placeholder": "Chagua nchi yako",
  "label_camera_permission_warning_ios": "Unahitaji kubadili namna ya kupata kamera. Kufanya hivyo, nenda sehemu ya setting >Privacy >camera",
  "label_camera_permission_warning_android": "Unahitaji kubadili namna ya kupata kamera. Kufanya hivyo, nenda sehemu ya setting >Apps>camera",
  "label_camera_error_title": "Kamera haipatikani",
  "label_error_modal_default_title": "Hapana!",
  "label_error_modal_default_subtitle": "Huduma haipatikani kwa sasa!",
  "label_location_permission_warning_ios": "Unahitaji kubadili namna ya kupata eneo. Kufanya hivyo, nenda sehemu ya setting >Privacy >Location service.",
  "label_location_permission_warning_android": "Unahitaji kubadili namna ya kupata eneo. Kufanya hivyo, nenda sehemu ya setting >programu.",
  "label_location_off_warning": "Huduma ya eneo imefungwa, Tafadhari washa GPS yako kwenye kibadilishio kwa kutumia programu.",
  "label_location_modal_title": "Washa intaneti kwenye eneo ulilopo",
  "label_network_off_warning_title": "Hakuna mtandao uliounganishwa",
  "label_network_off_warning": "Simu yako haijaunganishwa na intaneti, washa intaneti au unganisha simu yako na Wi-Fi ili utumie programu.",
  "label_loading_image_text": "Karibu unafanikiwa...",
  "label_loading_image_subtext": "Tafadhari subiri wakati tunathibitisha taarifa zako.",
  "label_create_marker_missing_photos": "Picha zilizowekwa alama, hazijafanikiwa kuwekwa kwenye mtandao, Tafadhari jaribu tena.",
  "label_edit_marker_missing_photos": "Picha zilizowekwa alama, hazijafanikiwa kuwekwa kwenye mtandao, Tafadhari jaribu tena.",
  "label_confirm_marker_missing_photos": "Picha zilizowekwa alama, hazijafanikiwa kuwekwa kwenye mtandao, Tafadhari jaribu tena.",
  "label_button_delete": "Futa",
  "label_delete_photo_title": "Futa picha",
  "label_delete_photo_subtitle": "Una uhakika kwamba unahitaji kufuta hii picha? ikifutika huwezi kuirudisha tena.",
  "label_text_about_1": "Programu hii ni mpango wa Let's Do It World",
  "label_text_about_2": "Taarifa zote zitakazo kusanywa na watumiaji duniani kote zitaoneshwa kwenye ramani kubwa ya taka ya dunia, ili kuanzisha harakati za kusafisha dunia kwenye tukio kubwa la kusafisha dunia, tarehe 15 Septemba 2018",
  "label_text_about_3": "Programu hii ni ushirikiano wa",
  "label_text_about_4": "Estonia product, umedhaminiwa na nchi na serikali",
  "label_text_about_5": "Wadhamini: Wizara ya mazingira ya Estonia, Wizara ya mambo ya kigeni ya Jamhuri ya Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Futa eneo lenye taka",
  "label_locked_account_warning": "Akaunti yako imefungwa. kwa taarifa zaidi wasiliana na uongozi."
}