{
  "label_text_app_subtitle": "Tuungane pamoja tusafishe Dunia!",
  "label_button_facebook": "Endelea na usajili wa Facebook",
  "label_button_google": "Endelea na usajili wa kwenye mtandao wa google",
  "label_button_try_app": "Jaribu kufungua programu bila kujisajili kwenye akaunti mpya",
  "label_button_acknowledge": "Ndio, imekubali!",
  "label_button_cancel": "Futa",
  "label_button_continue": "Endelea",
  "label_trash_status_threat": "hatari",
  "label_trash_status_regular": "kawaida",
  "label_trash_status_cleaned": "safi",
  "label_trash_status_outdated": "muda wa matumizi umeisha",
  "label_trash_status_user": "mtumiaji",
  "label_trash_status_change_location": "badili eneo",
  "label_trash_status_state_threat": "Eneo hili ni hatari!",
  "label_trash_status_state_regular": "Hili ni eneo lenye taka za kawaida.",
  "label_trash_status_state_cleaned": "Eneo hili limesafishwa!",
  "label_trash_status_state_outdated": "Eneo hili muda wake umepita!",
  "label_TP_created_date": "Imetengenezwa",
  "label_TP_updated_date": "Imeboreshwa",
  "label_TP_by": " kwa ",
  "label_trash_amount_handful": "kiganja",
  "label_trash_amount_bagful": "mfuko",
  "label_trash_amount_cartloadl": "mkokoteni",
  "label_trash_amount_truckload": "lori",
  "label_trash_type_plastic": "Plastiki",
  "label_trash_type_metal": "Chuma",
  "label_trash_type_glass": "Kioo",
  "label_trash_type_electro": "Vifaa vya umeme",
  "label_trash_type_paper": "Karatasi/Mbao",
  "label_trash_type_tyres": "Tairi",
  "label_trash_type_dom_waste": "Taka za majumbani",
  "label_trash_type_furniture": "Samani",
  "label_trash_type_org_waste": "Taka ozo",
  "label_header_tc": "Vigezo na masharti",
  "label_button_tc_agree": "Nakubaliana na vigezo na masharti",
  "label_header_map": "Ramani",
  "label_text_popover_subtitle": "Ungana na watu wanao chora ramani sehemu zenye taka!",
  "label_text_popover_text": "Anza kuunda maeneo yenye taka, kufanya jamii yako safi na salama.",
  "label_header_activity": "My activity",
  "label_text_activity_empty_subtitle": "Hamna kitu!",
  "label_text_activity_empty_text": "Hakuna eneo lenye taka lilioongezwa. likiwekwa, litaorodheshwa hapa.",
  "label_text_activity_empty_hint": "Weka eneo lenye taka!",
  "label_header_notific": "Taarifa",
  "label_text_notific_empty_subtitle": "Hamna kitu!",
  "label_text_notific_empty_text": "Bado hatujaona taarifa yeyote ikiingia, tutakujulisha pindi tutakapofanya!",
  "label_header_profile": "Maelezo mafupi",
  "label_header_settings": "Kufungua akaunti",
  "label_button_country_empty": "Nchi",
  "label_text_country": "Nchi",
  "label_header_select_country": "Chagua nchi",
  "label_text_select_country_hint": "Search",
  "label_button_tc": "Terms and Conditions",
  "label_button_logout": "Log out",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Great job!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Edit location",
  "label_header_edit_loc": "Edit location",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "Eneo lenye taka linaweza kuhaririwa, kama utakuwa umbali wa mita 100 toka kwenye eneo hilo.",
  "label_retry_button": "Jaribu tena",
  "label_country_picker_placeholder": "Chagua nchi yako",
  "label_camera_permission_warning_ios": "Unahitaji kubadili namna ya kupata kamera. Kufanya hivyo, nenda sehemu ya setting >Privacy >camera",
  "label_camera_permission_warning_android": "Unahitaji kubadili namna ya kupata kamera. Kufanya hivyo, nenda sehemu ya setting >Apps>camera",
  "label_camera_error_title": "Kamera haipatikani",
  "label_error_modal_default_title": "Hapana!",
  "label_error_modal_default_subtitle": "Huduma haipatikani kwa sasa!",
  "label_location_permission_warning_ios": "Unahitaji kubadili namna ya kupata eneo. Kufanya hivyo, nenda sehemu ya setting >Privacy >Location service.",
  "label_location_permission_warning_android": "Unahitaji kubadili namna ya kupata eneo. Kufanya hivyo, nenda sehemu ya setting >programu.",
  "label_location_off_warning": "Huduma ya eneo imefungwa, Tafadhari washa GPS yako kwenye kibadilishio kwa kutumia programu.",
  "label_location_modal_title": "Washa intaneti kwenye eneo ulilopo",
  "label_network_off_warning_title": "Hakuna mtandao uliounganishwa",
  "label_network_off_warning": "Simu yako haijaunganishwa na intaneti, washa intaneti au unganisha simu yako na Wi-Fi ili utumie programu.",
  "label_loading_image_text": "Karibu unafanikiwa...",
  "label_loading_image_subtext": "Tafadhari subiri wakati tunathibitisha taarifa zako.",
  "label_create_marker_missing_photos": "Picha zilizowekwa alama, hazijafanikiwa kuwekwa kwenye mtandao, Tafadhari jaribu tena.",
  "label_edit_marker_missing_photos": "Picha zilizowekwa alama, hazijafanikiwa kuwekwa kwenye mtandao, Tafadhari jaribu tena.",
  "label_confirm_marker_missing_photos": "Picha zilizowekwa alama, hazijafanikiwa kuwekwa kwenye mtandao, Tafadhari jaribu tena.",
  "label_button_delete": "Futa",
  "label_delete_photo_title": "Futa picha",
  "label_delete_photo_subtitle": "Una uhakika kwamba unahitaji kufuta hii picha? ikifutika huwezi kuirudisha tena.",
  "label_text_about_1": "Programu hii ni mpango wa Let's Do It World",
  "label_text_about_2": "Taarifa zote zitakazo kusanywa na watumiaji duniani kote zitaoneshwa kwenye ramani kubwa ya taka ya dunia, ili kuanzisha harakati za kusafisha dunia kwenye tukio kubwa la kusafisha dunia, tarehe 15 Septemba 2018",
  "label_text_about_3": "Programu hii ni ushirikiano wa",
  "label_text_about_4": "Estonia product, umedhaminiwa na nchi na serikali",
  "label_text_about_5": "Wadhamini: Wizara ya mazingira ya Estonia, Wizara ya mambo ya kigeni ya Jamhuri ya Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Futa eneo lenye taka",
  "label_locked_account_warning": "Akaunti yako imefungwa. kwa taarifa zaidi wasiliana na uongozi."
}