{
  "label_text_app_subtitle": "Sabay-sabay nating linisin ang mundo!",
  "label_button_facebook": "Magpatuloy gamit ang Facebook",
  "label_button_google": "Magpatuloy gamit ang Google",
  "label_button_try_app": "Subukan ang app nang walang account",
  "label_button_acknowledge": "Ok, nakuha ko!",
  "label_button_cancel": "Kanselahin",
  "label_button_continue": "Magpatuloy",
  "label_trash_status_threat": "banta",
  "label_trash_status_regular": "regular",
  "label_trash_status_cleaned": "nalinis na",
  "label_trash_status_outdated": "hindi updated",
  "label_trash_status_user": "user",
  "label_trash_status_change_location": "palitan ang lokasyon",
  "label_trash_status_state_threat": "Ang puntong ito ay isang banta!",
  "label_trash_status_state_regular": "Isa itong regular na trashpoint.",
  "label_trash_status_state_cleaned": "Ang puntong ito ay nalinis na!",
  "label_trash_status_state_outdated": "Ang puntong ito ay hindi updated!",
  "label_TP_created_date": "Nagawa na",
  "label_TP_updated_date": "Updated",
  "label_TP_by": " mula kay ",
  "label_trash_amount_handful": "isang dakot",
  "label_trash_amount_bagful": "isang supot",
  "label_trash_amount_cartloadl": "isang kariton",
  "label_trash_amount_truckload": "isang trak",
  "label_trash_type_plastic": "Supot",
  "label_trash_type_metal": "Metal",
  "label_trash_type_glass": "Salamin",
  "label_trash_type_electro": "Electronics",
  "label_trash_type_paper": "Papel/Kahoy",
  "label_trash_type_tyres": "Gulong",
  "label_trash_type_dom_waste": "Dumi mula sa mga kabahayan",
  "label_trash_type_furniture": "Gamit sa bahay",
  "label_trash_type_org_waste": "Organikong dumi",
  "label_header_tc": "Mga Termino at Kundisyon",
  "label_button_tc_agree": "Sumasangayon ako sa mga Termino at Kundisyon",
  "label_header_map": "Mapa",
  "label_text_popover_subtitle": "Samahan ang iba pa sa paglapat sa mapa ng mga basura!",
  "label_text_popover_text": "Umpisahan ang paggawa ng trashpoints upang magawang mas malinis at malusog ang iyong komunidad.",
  "label_header_activity": "Aking aktibidades",
  "label_text_activity_empty_subtitle": "Walang makikita dito!",
  "label_text_activity_empty_text": "Hindi ka pa nakapagdaragdag ng trashpoints. Kapag nakagawa ka na, malilista ang ito dito.",
  "label_text_activity_empty_hint": "Magdagdag ng trashpoint!",
  "label_header_notific": "Mga Abiso",
  "label_text_notific_empty_subtitle": "Walang makikita dito!",
  "label_text_notific_empty_text": "Wala pang mga abisong dumating, kapag mayroon na ay ipapaalam namin sa iyo!",
  "label_header_profile": "Aking Profile",
  "label_header_settings": "Mga setting ng account",
  "label_button_country_empty": "Bansa",
  "label_text_country": "Bansa",
  "label_header_select_country": "Pumili ng bansa",
  "label_text_select_country_hint": "Hanapin",
  "label_button_tc": "Mga Termini at Kundisyon",
  "label_button_logout": "Mag-log out",
  "label_text_congrats_image": "Ang basura ay nakuhanan na",
  "label_text_congrats_subtitle": "Magaling!",
  "label_text_congrats_text": "Ngayon ay i-save ang datos sa pamamagitan ng pagberipika nito.",
  "label_header_createTP": "Gumawa ng trashpoint",
  "label_button_createTP_editloc": "Ibahin ang lokasyon",
  "label_header_edit_loc": "Ibahin ang lokasyon",
  "label_button_edit_loc_set": "I-set ang lokasyon ng trashpoint",
  "label_text_createTP_status_subtitle": "Katayuan ng datos",
  "label_text_createTP_status_text": "Kung kinakailangan ng agarang tugon (nakalalason, mabibigat na metal), itakda bilang banta.",
  "label_text_createTP_add_photos": "Magdagdag ng mga litrato ng basura",
  "label_text_createTP_select_amount": "Pumili ng dami ng basura",
  "label_text_createTP_select_type": "Pumili ng uri ng basura",
  "label_text_createTP_add_hashtags": "Karagdagang tags",
  "label_text_createTP_add_hashtags_hint": "hal. #pangalanngbrand, #lata",
  "label_button_createTP_confirm_create": "Gumawa ng trashpoint",
  "label_alert_createTP_success": "Matagumpay na nalikha ang trashpoint",
  "label_text_detailsTP_photos": "Mga Litrato ng basura",
  "label_text_detailsTP_amount": "Dami ng basura",
  "label_text_detailsTP_type": "Uri ng basura",
  "label_text_editTP_ask": "Tama pa ba ang impormasyon ukol sa trashpoint na ito?",
  "label_text_editTP_letsconfirm": "Oo, kinukumpirma ko",
  "label_alert_editTP_confirm": "Matagumpay na nakumpirma ang trashpoint",
  "label_text_editTP_letsedit": "Hindi, baguhin natin",
  "label_header_editTP": "Baguhin ang trashpoint",
  "label_button_editTP_save": "I-save ang mga pagbabago sa trashpoint",
  "label_alert_editTP_edit": "Matagumpay na na-update ang trashpoint",
  "label_alert_editTP_delete": "Matagumpay na natanggal ang trashpoint",
  "label_error_editTP_out_of_rng_subtitle": "Hindi abot ang lawak",
  "label_error_editTP_out_of_rng_text": "Maaari lamang baguhin ang datos kung ikaw ay nasa loob ng 100 metros nito.",
  "label_error_saveTP_subtitle": "I-save ang trashpoint",
  "label_error_saveTP_pic_and_type": "Mas makatutulong sa amin kung makapagbibigay ka ng kahit isang litrato ng trashpoint at itakda ang tipo nito.",
  "label_error_saveTP_picture": "Mas makatutulong sa amin kung magbibigay ka ng kahit isang litrato ng trashpoint bago ito i-save.",
  "label_error_saveTP_trash_type": "Mas makatutulong sa amin kung iyong itatakda ang tipo ng basura bago ito i-save.",
  "label_error_change_loc_subtitle": "Sa labas ng hangganan",
  "label_error_change_loc_text": "Maglagay ng isang punto na nasa loob ng 100 metros ng iyong lokasyon.",
  "label_error_generic_error_subtitle": "Sa labas ng hangganan",
  "label_error_generic_error_text": "Mayroong error sa serber.",
  "label_error_network_subtitle": "Walang koneksyon sa network",
  "label_error_network_text": "Hindi naka-on ang mobile data. I-on ang mobile data o di kaya'y ikonekta sa Wi-Fi ang iyong telepono upang magamit ang application.",
  "label_error_location_subtitle": "Paganahin ang Location",
  "label_error_location_text": "Nakapatay ang iyong Location Services. Paganagin ang iyong GPS sa iyong Settings upang magamit ang application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Retry",
  "label_country_picker_placeholder": "Choose your country",
  "label_camera_permission_warning_ios": "You must change camera access permissions. To do this, go to Settings > Privacy > Camera",
  "label_camera_permission_warning_android": "You must change camera access permissions. To do this, go to Settings > Apps",
  "label_camera_error_title": "Camera Access Denied",
  "label_error_modal_default_title": "Oh noes!",
  "label_error_modal_default_subtitle": "The fail whale detected a server error!",
  "label_location_permission_warning_ios": "You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Enable location",
  "label_network_off_warning_title": "No network connection",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Almost there...",
  "label_loading_image_subtext": "Please wait while we save your actions.",
  "label_create_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Delete",
  "label_delete_photo_title": "Delete photo",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}