{
  "label_text_app_subtitle": "Hadi hep beraber dünyayı temizleyelim!",
  "label_button_facebook": "Facebook'la devam et",
  "label_button_google": "Google’la devam et",
  "label_button_try_app": "Uygulamayı hesapla açmadan dene",
  "label_button_acknowledge": "Tamam, anladım!",
  "label_button_cancel": "İptal et",
  "label_button_continue": "Devam et",
  "label_trash_status_threat": "tehdit",
  "label_trash_status_regular": "regular",
  "label_trash_status_cleaned": "temizlenmiş",
  "label_trash_status_outdated": "eski",
  "label_trash_status_user": "kullanıcı",
  "label_trash_status_change_location": "konumDeğiştir",
  "label_trash_status_state_threat": "Bu bir tehdit noktası!",
  "label_trash_status_state_regular": "Bu devamlı bir cöp alanı.",
  "label_trash_status_state_cleaned": "Bu alan temizlendi!",
  "label_trash_status_state_outdated": "Bu nokta güncel değil!",
  "label_TP_created_date": "Oluşturulan",
  "label_TP_updated_date": "Güncellendi",
  "label_TP_by": " tarafından ",
  "label_trash_amount_handful": "bir avuç",
  "label_trash_amount_bagful": "bir çanta",
  "label_trash_amount_cartloadl": "bir araba dolusu",
  "label_trash_amount_truckload": "bir kamyon dolusu",
  "label_trash_type_plastic": "Plastik",
  "label_trash_type_metal": "Metal",
  "label_trash_type_glass": "Cam",
  "label_trash_type_electro": "Elektronik eşya",
  "label_trash_type_paper": "Kağıt/Tahta",
  "label_trash_type_tyres": "Araba lastiği",
  "label_trash_type_dom_waste": "Ev atığı",
  "label_trash_type_furniture": "Mobilya",
  "label_trash_type_org_waste": "Organik atık",
  "label_header_tc": "Şartlar be koşullar",
  "label_button_tc_agree": "Şartlar ve koşulları kabul ediyorum",
  "label_header_map": "Harita",
  "label_text_popover_subtitle": "Yerleri paspaslayan diger insanlara katıl!",
  "label_text_popover_text": "Topluluğunuzu daha temiz ve sağlıklı hale getirmek için çöp puanı oluşturmaya başlayın.",
  "label_header_activity": "Etkinliğim",
  "label_text_activity_empty_subtitle": "Burada görecek bir şey yok!",
  "label_text_activity_empty_text": "Henüz herhangi bir çöp puanı eklemediniz. Ne zaman yaparsan, burada listelenecekler.",
  "label_text_activity_empty_hint": "Çöp kutusu ekleyin!",
  "label_header_notific": "Bildirimler",
  "label_text_notific_empty_subtitle": "Burada görecek bir şey yok!",
  "label_text_notific_empty_text": "Henüz daha bir bildirim gelmediğini görüyoruz, ancak ne zaman yaptığımız konusunda sizi bilgilendiririz!",
  "label_header_profile": "Profilim",
  "label_header_settings": "Hesap ayarları",
  "label_button_country_empty": "Ülke",
  "label_text_country": "Ülke",
  "label_header_select_country": "Ülke seçin",
  "label_text_select_country_hint": "Search",
  "label_button_tc": "Terms and Conditions",
  "label_button_logout": "Log out",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Great job!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Edit location",
  "label_header_edit_loc": "Edit location",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "100 metrelik bir mesafe içinde bu iseniz bir noktası yalnızca düzenlenebilirsin.",
  "label_retry_button": "Yeniden deneme",
  "label_country_picker_placeholder": "Ülkenizi seçin",
  "label_camera_permission_warning_ios": "Kamera erişim izinlerini değiştirmeniz gerekir. Bunu yapmak için, Ayarlar> Gizlilik> Kamera'ya gidin",
  "label_camera_permission_warning_android": "Konum izinlerini değiştirmelisiniz. Bunu yapmak için Ayarlar> Uygulamalar'a gidin",
  "label_camera_error_title": "Kamera erişimi reddedildi",
  "label_error_modal_default_title": "Oh hayır!",
  "label_error_modal_default_subtitle": "Hatalı balina bir sunucu hatası tespit etti!",
  "label_location_permission_warning_ios": "Konum izlenimini değiştirmelisiniz. Bunu yapmak için Ayarlar>Gizlilik>Konum servisine gidin.",
  "label_location_permission_warning_android": "Konum izlenimini değiştirmelisiniz. Bunu yapmak için Ayarlar>Gizlilik>Konum servisine gidin.",
  "label_location_off_warning": "Konum Hizmetleri kapalı. Uygulamayı kullanmak için lütfen GPS'inizi Ayarlar'da etkinleştirin.",
  "label_location_modal_title": "Konumu etkinleştir",
  "label_network_off_warning_title": "Ağ bağlantısı yok",
  "label_network_off_warning": "Mobil veri devre dışı. Uygulamayı kullanmak için mobil verileri etkinleştirin veya telefonunuzu Wi-Fi'ye bağlayın.",
  "label_loading_image_text": "Neredeyse tamam...",
  "label_loading_image_subtext": "Lütfen eylemlerinizi kaydederken bekleyin.",
  "label_create_marker_missing_photos": "İşaretlenen fotoğraflar yüklenemedi. Lütfen tekrar eklemeyi deneyin.",
  "label_edit_marker_missing_photos": "İşaretlenen fotoğraflar yüklenemedi. Lütfen tekrar eklemeyi deneyin.",
  "label_confirm_marker_missing_photos": "İşaretlenen fotoğraflar yüklenemedi. Lütfen tekrar eklemeyi deneyin.",
  "label_button_delete": "Sil",
  "label_delete_photo_title": "Fotoğrafı sil",
  "label_delete_photo_subtitle": "Fotoğrafı silmek istediğinizden emin misiniz? Bunu geri alamazsınız.",
  "label_text_about_1": "Bu uygulama Let's Do It World girişimidir",
  "label_text_about_2": "Dünya çapındaki kullanıcılar tarafından toplanan tüm veriler, 15 Eylül 2018 Dünya Temizleme Günü'nde dünya çapında temizlik etkinlikleri başlatmak için kullanılan genel çöp kutusu haritasında görselleştirilecektir",
  "label_text_about_3": "Bu uygulama bir müşterek işbirliğidir ile",
  "label_text_about_4": "Estonya ürünü, ülke ve hükümet sponsorluğunda",
  "label_text_about_5": "Kaynaklar: Estonya Çevre Bakanlığı, Estonya Cumhuriyeti Dışişleri Bakanlığı, Estonya Cumhuriyeti 100 programı",
  "label_button_editTP_delete": "Çöp kutusunu sil",
  "label_locked_account_warning": "Hesabınız kilitli. Ayrıntılar için yönetici ile iletişime geçin."
}