{
  "label_text_app_subtitle": "Hadi hep beraber dünyayı temizleyelim!",
  "label_button_facebook": "Facebook’la",
  "label_button_google": "Google’la devam et",
  "label_button_try_app": "Uygulamayı hesapla giriş yapmadan dene",
  "label_button_acknowledge": "Tamam, anladım!",
  "label_button_cancel": "İptal et",
  "label_button_continue": "Devam et",
  "label_trash_status_threat": "tehdit",
  "label_trash_status_regular": "düzenli",
  "label_trash_status_cleaned": "temiz",
  "label_trash_status_outdated": "eski",
  "label_trash_status_user": "kullanıcı",
  "label_trash_status_change_location": "konum değiştir",
  "label_trash_status_state_threat": "Bu nokta bir tehdittir!",
  "label_trash_status_state_regular": "Birası devamlı bir çöp alanı.",
  "label_trash_status_state_cleaned": "Bu alan temizlendi!",
  "label_trash_status_state_outdated": "Bu nokta güncel değil!",
  "label_TP_created_date": "Oluşturulan",
  "label_TP_updated_date": "Güncellendi",
  "label_TP_by": " tarafından ",
  "label_trash_amount_handful": "bir avuç",
  "label_trash_amount_bagful": "bir çanta",
  "label_trash_amount_cartloadl": "bir araba dolusu",
  "label_trash_amount_truckload": "bir kamyon dolusu",
  "label_trash_type_plastic": "Plastik",
  "label_trash_type_metal": "Metal",
  "label_trash_type_glass": "Cam",
  "label_trash_type_electro": "Elektronik eşya",
  "label_trash_type_paper": "Kağıt/Tahta",
  "label_trash_type_tyres": "Araba lastiği",
  "label_trash_type_dom_waste": "Ev atığı",
  "label_trash_type_furniture": "Mobilya",
  "label_trash_type_org_waste": "Organik atık",
  "label_header_tc": "Şartlar be koşullar",
  "label_button_tc_agree": "Şartları ve koşulları kabul ediyorum",
  "label_header_map": "Harita",
  "label_text_popover_subtitle": "Çöp haritalayan diğer kişilere katılın!",
  "label_text_popover_text": "Topluluğunuzu daha temiz ve sağlıklı hale getirmek için çöp puanı oluşturmaya başlayın.",
  "label_header_activity": "Benim etkinliğim",
  "label_text_activity_empty_subtitle": "Burada görecek bir şey yok!",
  "label_text_activity_empty_text": "Henüz herhangi bir çöp puanı eklemediniz. Ne zaman yaparsan, burada listelenecekler.",
  "label_text_activity_empty_hint": "Çöp kutusu ekleyin!",
  "label_header_notific": "Bildirimler",
  "label_text_notific_empty_subtitle": "Burada görecek bir şey yok!",
  "label_text_notific_empty_text": "Henüz bir bildirim gelmediğini görüyoruz, ancak ne zaman yaptığımız konusunda sizi bilgilendiririz!",
  "label_header_profile": "Profilim",
  "label_header_settings": "Hesap ayarları",
  "label_button_country_empty": "Ülke",
  "label_text_country": "Ülke",
  "label_header_select_country": "Bir ülke seçin",
  "label_text_select_country_hint": "Arama",
  "label_button_tc": "Şartlar ve koşullar",
  "label_button_logout": "Çıkış",
  "label_text_congrats_image": "Yakalanan çöp",
  "label_text_congrats_subtitle": "Harika iş!",
  "label_text_congrats_text": "Şimdi verileri doğrulayarak noktayı kaydedin.",
  "label_header_createTP": "Çöp kutusu yarat",
  "label_button_createTP_editloc": "Konumu Düzenle",
  "label_header_edit_loc": "Konumu Düzenle",
  "label_button_edit_loc_set": "Çöp yeri konumunu ayarla",
  "label_text_createTP_status_subtitle": "Puan durumu",
  "label_text_createTP_status_text": "Hızlı bir eyleme ihtiyaç duyarsanız (zehirli, ağır metaller) lütfen tehdit oluşturun.",
  "label_text_createTP_add_photos": "Çöp kutusu fotoğrafları ekleyin",
  "label_text_createTP_select_amount": "Çöp miktarı seçin",
  "label_text_createTP_select_type": "Çöp kutusu türünü seçin",
  "label_text_createTP_add_hashtags": "Ek eklenen Etiketler",
  "label_text_createTP_add_hashtags_hint": "yani. #brandname, #cans",
  "label_button_createTP_confirm_create": "Çöp kutusu yarat",
  "label_alert_createTP_success": "Çöp kutusu başarıyla oluşturuldu",
  "label_text_detailsTP_photos": "Çöp fotoğraflar",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Retry",
  "label_country_picker_placeholder": "Choose your country",
  "label_camera_permission_warning_ios": "You must change camera access permissions. To do this, go to Settings > Privacy > Camera",
  "label_camera_permission_warning_android": "You must change camera access permissions. To do this, go to Settings > Apps",
  "label_camera_error_title": "Camera Access Denied",
  "label_error_modal_default_title": "Oh noes!",
  "label_error_modal_default_subtitle": "The fail whale detected a server error!",
  "label_location_permission_warning_ios": "You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Enable location",
  "label_network_off_warning_title": "No network connection",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Almost there...",
  "label_loading_image_subtext": "Please wait while we save your actions.",
  "label_create_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Delete",
  "label_delete_photo_title": "Delete photo",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}