{
  "label_text_app_subtitle": "Зробімо світ чистіше разом!",
  "label_button_facebook": "Увійти через Facebook",
  "label_button_google": "Увійти через Google",
  "label_button_try_app": "Продовжити без аккаунту",
  "label_button_acknowledge": "Добре, зрозумів!",
  "label_button_cancel": "Скасувати",
  "label_button_continue": "Продовжити",
  "label_trash_status_threat": "небезпечно",
  "label_trash_status_regular": "регулярно",
  "label_trash_status_cleaned": "прибрано",
  "label_trash_status_outdated": "застаріло",
  "label_trash_status_user": "користувач",
  "label_trash_status_change_location": "змінити місце розташування",
  "label_trash_status_state_threat": "Ця точка становить небезпеку!",
  "label_trash_status_state_regular": "Це регулярне сміттєзвалище.",
  "label_trash_status_state_cleaned": "Це місце прибрано!",
  "label_trash_status_state_outdated": "Це місце застаріло!",
  "label_TP_created_date": "Створено",
  "label_TP_updated_date": "Оновлено",
  "label_TP_by": " за ",
  "label_trash_amount_handful": "ручна поклажа",
  "label_trash_amount_bagful": "мішок",
  "label_trash_amount_cartloadl": "віз",
  "label_trash_amount_truckload": "вантажівка",
  "label_trash_type_plastic": "Пластик",
  "label_trash_type_metal": "Метал",
  "label_trash_type_glass": "Скло",
  "label_trash_type_electro": "Електроніка",
  "label_trash_type_paper": "Папір/Дерево",
  "label_trash_type_tyres": "Шини",
  "label_trash_type_dom_waste": "Побутові відходи",
  "label_trash_type_furniture": "Меблі",
  "label_trash_type_org_waste": "Органічні відходи",
  "label_header_tc": "Правила та умови",
  "label_button_tc_agree": "Я згоден з правилами та умовами",
  "label_header_map": "Карта",
  "label_text_popover_subtitle": "Приєднуйтесь до інших людей, що відмічають сміттєзвалища!",
  "label_text_popover_text": "Розпочни відмічати засмічені місця, щоб зробити своє оточення чистіше і здоровіше.",
  "label_header_activity": "Моя активність",
  "label_text_activity_empty_subtitle": "Тут нічого не видно!",
  "label_text_activity_empty_text": "Ви ще не додали жодної засміченої точки. Коли ти додаси точку, вона буде відображена тут.",
  "label_text_activity_empty_hint": "Додати забруднену точку!",
  "label_header_notific": "Оголошення",
  "label_text_notific_empty_subtitle": "Тут нічого не видно!",
  "label_text_notific_empty_text": "Поки що ми не помітили ніяких оголошень, проте ми повідомимо вам якщо ми отримаємо їх!",
  "label_header_profile": "Мій профіль",
  "label_header_settings": "Налаштування профілю",
  "label_button_country_empty": "Країна",
  "label_text_country": "Країна",
  "label_header_select_country": "Обрати країну",
  "label_text_select_country_hint": "Пошук",
  "label_button_tc": "Правила та умови",
  "label_button_logout": "Вийти",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Чудова робота!",
  "label_text_congrats_text": "Тепер збережіть точку, перевіривши дані.",
  "label_header_createTP": "Створити забруднену точку",
  "label_button_createTP_editloc": "Редагувати місцезнаходження",
  "label_header_edit_loc": "Редагувати місцезнаходження",
  "label_button_edit_loc_set": "Встановити розташування сміттєзвалища",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Додати фотографії сміття",
  "label_text_createTP_select_amount": "Оберіть кількість сміття",
  "label_text_createTP_select_type": "Оберіть тип сміття",
  "label_text_createTP_add_hashtags": "Додаткові теги",
  "label_text_createTP_add_hashtags_hint": "наприклад #бренд, #бляшанка",
  "label_button_createTP_confirm_create": "Створити забруднену точку",
  "label_alert_createTP_success": "Забруднена точка успішно створена",
  "label_text_detailsTP_photos": "Фотографії сміттєзвалища",
  "label_text_detailsTP_amount": "Кількість сміття",
  "label_text_detailsTP_type": "Тип сміття",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Так, я підтверджую",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "Ні, давайте редагувати",
  "label_header_editTP": "Редагувати забруднену точку",
  "label_button_editTP_save": "Зберегти зміни",
  "label_alert_editTP_edit": "Забруднена точка успішно оновлена",
  "label_alert_editTP_delete": "Забруднена точка успішно видалена",
  "label_error_editTP_out_of_rng_subtitle": "Поза зоною досяжності",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Зберегти забруднену точку",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Порушено межі",
  "label_error_change_loc_text": "Будь ласка, розташуйте точку в межах 100 метрів від вашого розташування.",
  "label_error_generic_error_subtitle": "Порушено межі",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "Немає підключення до мережі",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Політика конфіденційності",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Редагувати забруднену точку",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Повторити спробу",
  "label_country_picker_placeholder": "Виберіть свою країну",
  "label_camera_permission_warning_ios": "Необхідно отримати доступ до камери. Для цього, виберіть Налаштування (Settings) > Конфіденційність (Privacy) > Камера (Camera)",
  "label_camera_permission_warning_android": "Необхідно отримати доступ до камери. Для цього, виберіть Налаштування> Додатки",
  "label_camera_error_title": "Відмовлено у доступі до камери",
  "label_error_modal_default_title": "Oh noes!",
  "label_error_modal_default_subtitle": "Кит виявив помилку сервера!",
  "label_location_permission_warning_ios": "Слід отримати доступ до місця знаходження. Для цього, перейдіть в Налаштування>Конфіденційність> Визначення місця знаходження.",
  "label_location_permission_warning_android": "Слід змінити доступ до місцезнаходження. Для цього, перейдіть в Налаштування> Додатки.",
  "label_location_off_warning": "Сервіс визначення місцезнаходження вимкнено. Будь ласка увімкніть GPS в Налаштуваннях для користування додатком.",
  "label_location_modal_title": "Увімкнути місцезнаходження",
  "label_network_off_warning_title": "Немає підключення до мережі",
  "label_network_off_warning": "Передачу даних вимкнено. Увімкніть передачу даних або підключіться до Wi-Fi щоб користуватися застосунком.",
  "label_loading_image_text": "Майже все...",
  "label_loading_image_subtext": "Зачекайте, поки ми збережемо ваші дії.",
  "label_create_marker_missing_photos": "Не вдалося передати фотографії. Будь ласка, спробуйте знову додати їх.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Видалити",
  "label_delete_photo_title": "Видалити фото",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Видалити забруднену точку",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}