{
  "label_text_app_subtitle": "Hãy cùng nhau làm sạch thế giới!",
  "label_button_facebook": "Tiếp tục với Facebook",
  "label_button_google": "Tiếp tục với Google",
  "label_button_try_app": "Thử ứng dụng không có tài khoản",
  "label_button_acknowledge": "Ok, hiểu rồi!",
  "label_button_cancel": "Hủy bỏ",
  "label_button_continue": "Tiếp tục",
  "label_trash_status_threat": "sự nguy hại",
  "label_trash_status_regular": "thường xuyên",
  "label_trash_status_cleaned": "đã làm sạch",
  "label_trash_status_outdated": "lỗi thời",
  "label_trash_status_user": "người sử dụng",
  "label_trash_status_change_location": "thayđổiVịtrí",
  "label_trash_status_state_threat": "Điểm này là một mối đe dọa!",
  "label_trash_status_state_regular": "Đây là một điểm đổ rác thông thường.",
  "label_trash_status_state_cleaned": "Địa điểm này đã sạch!",
  "label_trash_status_state_outdated": "Địa điểm này là lỗi thời!",
  "label_TP_created_date": "Đã được tạo ra",
  "label_TP_updated_date": "Cập Nhật",
  "label_TP_by": " bởi ",
  "label_trash_amount_handful": "một nắm",
  "label_trash_amount_bagful": "một túi",
  "label_trash_amount_cartloadl": "một rổ",
  "label_trash_amount_truckload": "một tải",
  "label_trash_type_plastic": "Nhựa",
  "label_trash_type_metal": "Kim loại",
  "label_trash_type_glass": "Thủy tinh",
  "label_trash_type_electro": "Thiết bị điện tử",
  "label_trash_type_paper": "Giấy/gỗ",
  "label_trash_type_tyres": "Lốp xe",
  "label_trash_type_dom_waste": "Rác thải sinh hoạt",
  "label_trash_type_furniture": "Đồ nội thất",
  "label_trash_type_org_waste": "Chất thải hữu cơ",
  "label_header_tc": "Điều khoản và Điều kiện",
  "label_button_tc_agree": "Tôi đồng ý với các Điều khoản & Điều kiện",
  "label_header_map": "Bản đồ",
  "label_text_popover_subtitle": "Tham gia cùng với những người đang lập bản đồ rác thải!",
  "label_text_popover_text": "Bắt đầu tạo điểm đổ rác để làm cho cộng đồng có môi trường sạch sẽ và khỏe mạnh hơn.",
  "label_header_activity": "Hoạt động của tôi",
  "label_text_activity_empty_subtitle": "Không có gì để xem ở đây!",
  "label_text_activity_empty_text": "Bạn chưa thêm bất kỳ điểm đổ rác nào. Khi bạn tạo ra một điểm, thì nó sẽ được liệt kê ở đây.",
  "label_text_activity_empty_hint": "Thêm một điểm đổ rác!",
  "label_header_notific": "Thông báo",
  "label_text_notific_empty_subtitle": "Không có gì để xem ở đây!",
  "label_text_notific_empty_text": "Chúng tôi đã không thấy bất kỳ thông báo nào được gửi đến, nhưng chúng tôi sẽ cho bạn biết khi chúng tôi có nó!",
  "label_header_profile": "Hồ sơ của tôi",
  "label_header_settings": "Cài đặt tài khoản",
  "label_button_country_empty": "Quốc gia",
  "label_text_country": "Quốc gia",
  "label_header_select_country": "Chọn một quốc gia",
  "label_text_select_country_hint": "Tìm kiếm",
  "label_button_tc": "Điều khoản và Điều kiện",
  "label_button_logout": "Đăng xuất",
  "label_text_congrats_image": "Đã thu gom rác",
  "label_text_congrats_subtitle": "Tuyệt vời!",
  "label_text_congrats_text": "Bây giờ lưu địa điểm bằng cách kiểm tra dữ liệu.",
  "label_header_createTP": "Tạo một điểm đổ rác",
  "label_button_createTP_editloc": "Chỉnh sửa địa điểm",
  "label_header_edit_loc": "Chỉnh sửa địa điểm",
  "label_button_edit_loc_set": "Thiết lập địa điểm đổ rác",
  "label_text_createTP_status_subtitle": "Trạng thái địa điểm",
  "label_text_createTP_status_text": "Nếu cần một hành động nhanh (chất độc, kim loại nặng), hãy cài đặt mối đe dọa.",
  "label_text_createTP_add_photos": "Thêm hình ảnh của rác",
  "label_text_createTP_select_amount": "Chọn số lượng rác",
  "label_text_createTP_select_type": "Chọn loại rác",
  "label_text_createTP_add_hashtags": "Bổ sung thêm tag",
  "label_text_createTP_add_hashtags_hint": "ví dụ. #tênthươnghiệu, #lon",
  "label_button_createTP_confirm_create": "Tạo một điểm đổ rác",
  "label_alert_createTP_success": "Điểm đổ rác đã được tạo thành công",
  "label_text_detailsTP_photos": "Hình ảnh rác",
  "label_text_detailsTP_amount": "Số lượng rác",
  "label_text_detailsTP_type": "Loại rác",
  "label_text_editTP_ask": "Thông tin điểm đổ rác này vẫn là chính xác và mới cập nhật?",
  "label_text_editTP_letsconfirm": "Yeah, tôi xác nhận",
  "label_alert_editTP_confirm": "Điểm đổ rác xác nhận thành công",
  "label_text_editTP_letsedit": "Không, hãy chỉnh sửa",
  "label_header_editTP": "Chỉnh sửa điểm đổ rác",
  "label_button_editTP_save": "Lưu các thay đổi cho điểm dổ rác",
  "label_alert_editTP_edit": "Điểm đổ rác đã được cập nhật thành công",
  "label_alert_editTP_delete": "Điểm đổ rác đã được xóa thành công",
  "label_error_editTP_out_of_rng_subtitle": "Ngoài phạm vi",
  "label_error_editTP_out_of_rng_text": "Một điểm chỉ có thể chỉnh sửa nếu bạn đang trong phạm vi 100 mét của nó.",
  "label_error_saveTP_subtitle": "Lưu điểm đổ rác",
  "label_error_saveTP_pic_and_type": "Nó sẽ hữu ích hơn đối với chúng ta nếu bạn có ít nhất một hình ảnh của điểm đổ rác và thiết lập loại rác.",
  "label_error_saveTP_picture": "Điều này sẽ có ích hơn với chúng ta nếu bạn có ít nhất một hình ảnh của điểm đổ rác trước khi lưu.",
  "label_error_saveTP_trash_type": "Điều này sẽ có ích hơn đối với chúng ta nếu bạn thiết lập phân loại điểm đổ rác trước khi lưu.",
  "label_error_change_loc_subtitle": "Ngoài giới hạn",
  "label_error_change_loc_text": "Xin vui lòng đặt một địa điểm trong vòng 100 m quanh vị trí của bạn.",
  "label_error_generic_error_subtitle": "Ngoài giới hạn",
  "label_error_generic_error_text": "Đã có lỗi trên máy chủ.",
  "label_error_network_subtitle": "Không có kết nối mạng",
  "label_error_network_text": "Dữ liệu điện thoại di động bị tắt. Bật dữ liệu di động hoặc kết nối điện thoại với Wi-Fi để sử dụng các ứng dụng.",
  "label_error_location_subtitle": "Bật vị trí",
  "label_error_location_text": "Dịch vụ định vị đã tắt. Vui lòng kích hoạt GPS của bạn trong cài đặt để sử dụng các ứng dụng.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Chi tiết địa điểm đổ rác",
  "label_privacy_policy_header": "Chính sách Bảo mật",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Chỉnh sửa điểm đổ rác",
  "label_100m_limit_modal": "Một điểm chỉ có thể chỉnh sửa nếu bạn đang trong phạm vi 100 mét của nó.",
  "label_retry_button": "Thử lại",
  "label_country_picker_placeholder": "Chọn quốc gia của bạn",
  "label_camera_permission_warning_ios": "Bạn phải thay đổi quyền truy cập máy ảnh. Để làm điều này, hãy vào Chỉnh sửa > Riêng tư > Máy ảnh",
  "label_camera_permission_warning_android": "Bạn phải thay đổi quyền truy cập máy ảnh. Để làm điều này, hãy vào Chỉnh sửa > Ứng dụng",
  "label_camera_error_title": "Camera Access Denied",
  "label_error_modal_default_title": "Oh noes!",
  "label_error_modal_default_subtitle": "The fail whale detected a server error!",
  "label_location_permission_warning_ios": "You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Enable location",
  "label_network_off_warning_title": "No network connection",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Almost there...",
  "label_loading_image_subtext": "Please wait while we save your actions.",
  "label_create_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Delete",
  "label_delete_photo_title": "Delete photo",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}