{
  "label_text_app_subtitle": "让我们一起清理世界吧!",
  "label_button_facebook": "在脸书中继续",
  "label_button_google": "在谷歌中继续",
  "label_button_try_app": "无账户试用本应用",
  "label_button_acknowledge": "好的，明白！",
  "label_button_cancel": "取消",
  "label_button_continue": "继续",
  "label_trash_status_threat": "威胁",
  "label_trash_status_regular": "常规",
  "label_trash_status_cleaned": "已清理",
  "label_trash_status_outdated": "已过时",
  "label_trash_status_user": "用户",
  "label_trash_status_change_location": "changeLocation",
  "label_trash_status_state_threat": "该点是一个威胁！",
  "label_trash_status_state_regular": "这是一个常规废弃物点。",
  "label_trash_status_state_cleaned": "该点已清理！",
  "label_trash_status_state_outdated": "该点已过期！",
  "label_TP_created_date": "已创建",
  "label_TP_updated_date": "已更新",
  "label_TP_by": "经由",
  "label_trash_amount_handful": "少数",
  "label_trash_amount_bagful": "中等",
  "label_trash_amount_cartloadl": "多数",
  "label_trash_amount_truckload": "大量",
  "label_trash_type_plastic": "塑料",
  "label_trash_type_metal": "金属",
  "label_trash_type_glass": "玻璃",
  "label_trash_type_electro": "电子设备",
  "label_trash_type_paper": "纸质/木质",
  "label_trash_type_tyres": "轮胎",
  "label_trash_type_dom_waste": "生活废弃物",
  "label_trash_type_furniture": "家具",
  "label_trash_type_org_waste": "有机废弃物",
  "label_header_tc": "条款声明",
  "label_button_tc_agree": "我同意该条款声明",
  "label_header_map": "地图",
  "label_text_popover_subtitle": "加入他人来定位废弃物",
  "label_text_popover_text": "开始创建垃圾点来使社区更加清洁与健康。",
  "label_header_activity": "我的活动",
  "label_text_activity_empty_subtitle": "此处无内容！",
  "label_text_activity_empty_text": "你还未添加垃圾点。当你添加时，它们将在此显示。",
  "label_text_activity_empty_hint": "添加废弃物点！",
  "label_header_notific": "通知",
  "label_text_notific_empty_subtitle": "此处无内容！",
  "label_text_notific_empty_text": "目前我们尚未收到通知，一旦收到将会立即传达给你！",
  "label_header_profile": "个人资料",
  "label_header_settings": "帐户设置",
  "label_button_country_empty": "国家",
  "label_text_country": "国家",
  "label_header_select_country": "选择国家",
  "label_text_select_country_hint": "搜索",
  "label_button_tc": "条款声明",
  "label_button_logout": "注销",
  "label_text_congrats_image": "Trash captured",
  "label_text_congrats_subtitle": "Great job!",
  "label_text_congrats_text": "Now save the point by verifying the data.",
  "label_header_createTP": "Create a trashpoint",
  "label_button_createTP_editloc": "Edit location",
  "label_header_edit_loc": "Edit location",
  "label_button_edit_loc_set": "Set trashpoint location",
  "label_text_createTP_status_subtitle": "Point status",
  "label_text_createTP_status_text": "If a quick action is needed (toxic, heavy metals), please set as threat.",
  "label_text_createTP_add_photos": "Add trash photos",
  "label_text_createTP_select_amount": "Select trash amount",
  "label_text_createTP_select_type": "Select trash type",
  "label_text_createTP_add_hashtags": "Additional added tags",
  "label_text_createTP_add_hashtags_hint": "ie. #brandname, #cans",
  "label_button_createTP_confirm_create": "Create trashpoint",
  "label_alert_createTP_success": "Trashpoint successfully created",
  "label_text_detailsTP_photos": "Trash photos",
  "label_text_detailsTP_amount": "Trash amount",
  "label_text_detailsTP_type": "Trash type",
  "label_text_editTP_ask": "Is this trashpoint information still correct and up to date?",
  "label_text_editTP_letsconfirm": "Yes, I confirm",
  "label_alert_editTP_confirm": "Trashpoint successfully confirmed",
  "label_text_editTP_letsedit": "No, let's edit",
  "label_header_editTP": "Edit a trashpoint",
  "label_button_editTP_save": "Save trashpoint changes",
  "label_alert_editTP_edit": "Trashpoint successfully updated",
  "label_alert_editTP_delete": "Trashpoint successfully deleted",
  "label_error_editTP_out_of_rng_subtitle": "Out of range",
  "label_error_editTP_out_of_rng_text": "A point can only be edx`ited if you are within 100 meters of it.",
  "label_error_saveTP_subtitle": "Save trashpoint",
  "label_error_saveTP_pic_and_type": "It's more useful for us if you to take at least one picture of the trashpoint and set its trash type.",
  "label_error_saveTP_picture": "It's more useful for us if you to take at least one picture of the trashpoint before saving.",
  "label_error_saveTP_trash_type": "It's more useful for us if you set the trashpoint's type before saving.",
  "label_error_change_loc_subtitle": "Out of bounds",
  "label_error_change_loc_text": "Please place a point within 100 meters of your location.",
  "label_error_generic_error_subtitle": "Out of bounds",
  "label_error_generic_error_text": "There was an error on the server.",
  "label_error_network_subtitle": "No network connection",
  "label_error_network_text": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_error_location_subtitle": "Enable location",
  "label_error_location_text": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_error_loc_permission_text": "Location Services are not permitted. Please allow them in order to use the application.",
  "label_trash_details_header": "Trashpoint details",
  "label_privacy_policy_header": "Privacy Policy",
  "label_about_header": "About",
  "label_edit_trashpoint_button": "Edit trashpoint",
  "label_100m_limit_modal": "A point can only be edited if you are within 100 meters of it.",
  "label_retry_button": "Retry",
  "label_country_picker_placeholder": "Choose your country",
  "label_camera_permission_warning_ios": "You must change camera access permissions. To do this, go to Settings > Privacy > Camera",
  "label_camera_permission_warning_android": "你须更改相机访问权限。请转到设置 > 应用",
  "label_camera_error_title": "拒绝访问相机",
  "label_error_modal_default_title": "碰壁了！",
  "label_error_modal_default_subtitle": "检错大鲸发现一个服务器错误！",
  "label_location_permission_warning_ios": "You must change location permissions. To do this, go to Settings > Privacy > Location services.",
  "label_location_permission_warning_android": "You must change location permissions. To do this, go to Settings > Apps.",
  "label_location_off_warning": "Location Services are turned off. Please enable your GPS in your Settings to use the application.",
  "label_location_modal_title": "Enable location",
  "label_network_off_warning_title": "No network connection",
  "label_network_off_warning": "Mobile data is disabled. Enable mobile data or connect your phone to Wi-Fi to use the application.",
  "label_loading_image_text": "Almost there...",
  "label_loading_image_subtext": "Please wait while we save your actions.",
  "label_create_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_edit_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_confirm_marker_missing_photos": "The marker photos could not be uploaded. Please try adding them again.",
  "label_button_delete": "Delete",
  "label_delete_photo_title": "Delete photo",
  "label_delete_photo_subtitle": "Are you sure you want to delete the photo? You cannot undo this.",
  "label_text_about_1": "This app is an initiative by Let's Do It World",
  "label_text_about_2": "All the data collected by users worldwide will be visualised in the global trash map for initiating worldwide clean-up events on World Cleanup Day, 15 September 2018",
  "label_text_about_3": "This app is a joint cooperation with",
  "label_text_about_4": "Estonian product, sponsored by the country and government",
  "label_text_about_5": "Funders: Estonian Ministry of Environment, The Ministry of Foreign Affairs of the Republic of Estonia, Estonian Republic 100 program",
  "label_button_editTP_delete": "Delete trashpoint",
  "label_locked_account_warning": "Your account is locked. For details contact an administrator."
}