# This is a common NodeJS setup reused by most node-based containers in this
# project. Please remember that if you change it you will be affecting several
# containers.

FROM node:8.1.2-alpine
MAINTAINER Qualitance
WORKDIR /src
RUN npm install --loglevel silent --production
RUN cd /src && npm i -g supervisor
CMD ["/usr/local/bin/supervisor", "--no-restart-on", "error", "--watch", "/src/", "--", "--inspect=0.0.0.0:9229", "--nolazy", "/src/app.js"]
