export default {
  FETCH_USERS_REQUEST: 'GET_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  FETCH_USERS_FAILED: 'GET_USERS_FAILED',
  SET_USER_LOCKED: 'SET_USER_LOCKED',
  RESET_USERS: 'RESET_USERS',

  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',
};
