export default {
  TOGGLE_EVENT_WINDOW: 'TOGGLE_EVENT_WINDOW',
  FETCH_ALL_EVENTS_REQUEST: 'FETCH_ALL_EVENTS_REQUEST',
  FETCH_ALL_EVENTS_SUCCESS: 'FETCH_ALL_EVENTS_SUCCESS',
  FETCH_EVENT_DETAILS: 'FETCH_EVENT_DETAILS'
};
