export default {
  TOGGLE_EVENT_WINDOW: 'TOGGLE_EVENT_WINDOW',
  FETCH_ALL_EVENT_MARKERS_REQUEST: 'FETCH_ALL_EVENT_MARKERS_REQUEST',
  FETCH_ALL_EVENT_MARKERS_FAIL: 'FETCH_ALL_EVENT_MARKERS_FAIL',
  FETCH_ALL_EVENT_MARKERS_SUCCESS: 'FETCH_ALL_EVENT_MARKERS_SUCCESS',
  FETCH_ALL_EVENTS_REQUEST: 'FETCH_ALL_EVENTS_REQUEST',
  FETCH_ALL_EVENTS_FAIL: 'FETCH_ALL_EVENTS_FAIL',
  FETCH_ALL_EVENTS_SUCCESS: 'FETCH_ALL_EVENTS_SUCCESS',
  FETCH_EVENT_TITLE: 'FETCH_EVENT_TITLE',
  FETCH_EVENT_DETAILS_REQUEST: 'FETCH_EVENT_DETAILS_REQUEST',
  FETCH_EVENT_DETAILS_FAILED: 'FETCH_EVENT_DETAILS_FAILED',
  FETCH_EVENT_DETAILS_SUCCESS: 'FETCH_EVENT_DETAILS_SUCCESS',
};
