const GOOGLE_LOGIN_ACTION = 'GOOGLE_LOGIN_ACTION';
const FB_LOGIN_ACTION = 'FB_LOGIN_ACTION';


const SET_AUTH_TOKEN = 'auth/SET_TOKEN';
const SET_AUTH_ERROR = 'auth/SET_ERROR';
const REMOVE_AUTH_TOKEN = 'auth/REMOVE_TOKEN';

const FETCH_PROFILE = 'profile/FETCH_PROFILE';
const FETCH_PROFILE_SUCCESS = 'profile/FETCH_PROFILE_SUCCESS';
const FETCH_PROFILE_ERROR = 'profile/FETCH_PROFILE_ERROR';

const UPDATE_PROFILE = 'profile/UPDATE_PROFILE';
const UPDATE_PROFILE_DONE = 'profile/UPDATE_PROFILE_DONE';
const UPDATE_PROFILE_ERROR = 'profile/UPDATE_PROFILE_ERROR';

const UPDATE_PROFILE_STATUS_ACTION = 'profile/UPDATE_PROFILE_PRIVACY_STATUS';
const UPDATE_PROFILE_STATUS_SUCCESS = 'profile/UPDATE_PROFILE_STATUS_SUCCESS';
const UPDATE_PROFILE_STATUS_ERROR = 'profile/UPDATE_PROFILE_STATUS_ERROR';

const TERMS_AGREE = 'profile/TERMS_AGREE';

export default {
    SET_AUTH_TOKEN,
    SET_AUTH_ERROR,
    REMOVE_AUTH_TOKEN,
    FETCH_PROFILE,
    FETCH_PROFILE_SUCCESS,
    FETCH_PROFILE_ERROR,
    TERMS_AGREE,
    UPDATE_PROFILE,
    UPDATE_PROFILE_DONE,
    UPDATE_PROFILE_ERROR,
    GOOGLE_LOGIN_ACTION,
    FB_LOGIN_ACTION,
    UPDATE_PROFILE_STATUS_ACTION,
    UPDATE_PROFILE_STATUS_SUCCESS,
    UPDATE_PROFILE_STATUS_ERROR
};
